### ISSUE TITLE
Add a Content-Secure-Policy meta tag

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#1141]
[Content-Secure-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) allows us to restrict loading of resources from non-HTTPS sources:

``` html
<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline' https:">
```

This will mean that loading of insecure resources, which would now break on live as it's HTTPS, will also fail to load in development environments too - so we don't accidentally try to include insecure resources.

**Comment by deadlight** [comment]
Looking at the previously-submitted and retracted PR for this, we don't want to do it.

Please re-open this with more details if a more complete solution is required.
