### ISSUE TITLE
Navigation at 1024px viewport is broken

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1172]
## Summary

When the viewport is at 1024 wide the navigation breaks

## Process

Visit https://www.ubuntu.com/cloud and resize window to 1024px

## Current and expected result

The main title of the section (in this example "Cloud") should be above the section names (which you can see if you reduce the size of window to mobile). I think this is the only window size where this happens.

## Screenshot

![navigation-1024](https://cloud.githubusercontent.com/assets/223966/20962649/10281fba-bc62-11e6-9e3d-3f384edccd1a.png)

**Comment by barrymcgee** [comment]
@yaili This should now be resolved on all v1 pages, can you confirm? e.g. https://www.ubuntu.com/legal

**Comment by yaili** [comment]
@barrymcgee should it be showing large screen nav now at 1024px?

**Comment by barrymcgee** [comment]
@yaili Yes, the navigation is now built on the Vanilla navigation pattern so the large screen nav appears at $breakpoint-medium (768px)

**Comment by yaili** [comment]
OK 👍
