### ISSUE TITLE
Update images on the burn a DVD macOS page

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#1220]
Following on from #1215, although #1219 replaces instances of "Mac OSX" with "macOS", and images have been replaced in the [create a USB stick](https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-mac-osx), the images on [the DVD page](https://www.ubuntu.com/download/desktop/burn-a-dvd-on-mac-osx) are still old.

Update them to reflect a modern version of masOS.

**Comment by pmahnke** [comment]
they were created on a modern version of macOS at the time of 16.04

**Comment by yaili** [comment]
@pmahnke should this be closed?

**Comment by deadlight** [comment]
These have been moved to the tutorials site. We should still check the the content is up-to-date
