### ISSUE TITLE
302 Redirect Misconfiguration

### ISSUE THREAD

**Issue by dundir** [canonical-websites/www.ubuntu.com#1257]
## Summary

The 302 Redirect from http://developer.ubuntu.com/packaging/html/ incorrectly redirects to http://packaging.ubuntu.com/html/html/ instead of http://packaging.ubuntu.com/html/

## Process

Travel to http://developer.ubuntu.com/packaging/html/. Tested with Chrome v55

## Current and expected result

Curent Result, 404 Not Found, Expected Result 200 OK.

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@WillMoggridge this appears fixed to me... can you confirm?

**Comment by WillMoggridge** [comment]
I think I found the cause and have updated the redirect, wiating on cache to update.

**Comment by WillMoggridge** [comment]
From testing, this works on https and not http.
I have raised a ticket to inspect and refresh the cache.

**Comment by WillMoggridge** [comment]
It is sorted! \o/
