### ISSUE TITLE
Pull quotes at smaller viewports

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1293]
Pull quotes' font size doesn't change dependant on the viewport size, making them look too large at small viewports.

This will be fixed upstream in Vanilla Framework but, in the meantime, I think we should implement a more sensible sizing scheme based on this:
https://www.dropbox.com/work/00_web_team/vanilla/deliverables/Pull%20quote?preview=pull-quote.md

**Comment by yaili** [comment]
Vanilla design spec, for reference: https://github.com/ubuntudesign/vanilla-design/tree/master/Pull%20quote

**Comment by deadlight** [comment]
Check to see if this has been fixed upstream and if it can be fixed with a Vanilla upgrade
