### ISSUE TITLE
Autopilot requires a purchase of Landscape on Premises in addition to the $750 a server purchase

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-websites/www.ubuntu.com#1297]
The website states:
Free to all support customers (which should likely be free to all landscape on premises customers).

And then it also states
How much does it cost?
Free  - Up to ten machines
$750 - Annually, per server

The base server cost to add to Landscape is $750, but you also need a separate license for landscape on premises.

---
*Reported from: https://www.ubuntu.com/cloud/openstack/autopilot*

**Comment by dpb1** [comment]
I think the $2k is of minimal importance to call out here.  It's mentioned on the details page for people that are interested.  A one-time $2k is peanuts, compared to the ~10k anually just to get their foot in the door.

**Comment by pmahnke** [comment]
Hi, we have updated the text on this page... see #2012 update the pricing on /cloud/autopilot and added text about on-premises server being required
