### ISSUE TITLE
update /cloud events card assigned to me

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#1402]
<b>Peter Mahnke</b> assigned me to the <a href="http://ift.tt/2m0h0Xn">update /cloud events</a> card on the <b>TODO</b> list in the <b>Web team task board</b> board at March 2, 2017 at 04:12PM<br><br><i>* data - view-source:http://ift.tt/2mxnlg6 * include - /cloud/shared/_events_overview.html * PR to copy - http://ift.tt/2m0kiKe ## Done - updated the /cloud overview events ## QA 1. go to /cloud 2. see that all the events are current ## Issue / Card [trello card](http://ift.tt/2mxkX9m)</i><br><br><a href="http://ift.tt/2m0h0Xn">View on Trello</a>

**Comment by anthonydillon** [comment]
This work has been merged?

**Comment by pmahnke** [comment]
@anthonydillon yes, I think a bot created this that i was testing...
