### ISSUE TITLE
Ubuntu Budgie is not yet recognized as a flavor on the website

### ISSUE THREAD

**Issue by tsimonq2** [canonical-websites/www.ubuntu.com#1407]
Ubuntu Budgie should be listed on [the "Ubuntu flavours" page](https://www.ubuntu.com/download/ubuntu-flavours) as it's now an official flavor.

Here is what it looks like now:

![Flavors page right now](http://i.imgur.com/wfzSK2M.png)

**Comment by nottrobin** [comment]
Evidence:

- The [technical board meeting](http://ubottu.com/meetingology/logs/ubuntu-meeting-2/2016/ubuntu-meeting-2.2016-11-08-17.01.log.txt) where this was agreed
- The [Ubuntu Budgie announcement](https://budgie-remix.org/2016/11/08/its-official/)

**Comment by nottrobin** [comment]
It should also be updated on [this page](https://www.ubuntu.com/about/about-ubuntu/flavours).

**Comment by anthonydillon** [comment]
@tsimonq2 would you mind providing a description of the project that aligns with the descriptions on the flavours page?

https://www.ubuntu.com/download/ubuntu-flavours

**Comment by fossfreedom** [comment]
@anthonydillon - Ubuntu Budgie project lead here.  How about the following?:

"Ubuntu Budgie provides the budgie-desktop environment which focuses on simplicity and elegance. It provides a traditional desktop metaphor based interface utilising a customisable panel based menu driven system."

**Comment by anthonydillon** [comment]
@fossfreedom Looks great thanks.

**Comment by anthonydillon** [comment]
@fossfreedom Do you have a logo for the flavour?

**Comment by fossfreedom** [comment]
sure - https://github.com/UbuntuBudgie/assets/blob/master/Logos/budgie-remix-logo-medium.svg

**Comment by anthonydillon** [comment]
Thanks for the image. The addition is in review.
