### ISSUE TITLE
Formatting issue - Juju Community

### ISSUE THREAD

**Issue by ae5202** [canonical-websites/www.ubuntu.com#1433]
## Summary

On this page: https://jujucharms.com/community?mkt_tok=eyJpIjoiTkdaak9EUXpOVFUwTkdRMCIsInQiOiIrNTN3U1A2NktBYUlzZkZMcmtqTHRnaHpPZXJFY1padVwvQ0ZydXlidWJ2SVRDZjNSRWRwZzA5YVR3OFRPcE1XZFdKN0NMaDFDUkVLSEJvenNhYU9qK0E9PSJ9 there is a small formatting issue. 

OpenStack solutions is bold whereas the other topic titles are not.

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
Alexia

Could you file the bug on the juju site?  https://github.com/CanonicalLtd/jujucharms.com/issues

This is for www.ubuntu.com.

Closing this.

Thanks

Peter
