### ISSUE TITLE
Old content on wiki

### ISSUE THREAD

**Issue by pvannuff** [canonical-websites/www.ubuntu.com#1440]
Hi

Seeing the slashdot article about upgrading old ubuntu LTS 12.04 installs I wanted to quickly google the nice chart for all various releases and support cycle up to now. But doing a google for 'ubuntu LTS' pointed me to this link:
https://wiki.ubuntu.com/LTS

Instead of:
https://www.ubuntu.com/info/release-end-of-life

Perhaps you could edit the wiki to simply point to the newer up to date information, so there are no longer two spots to keep in sync?

Kind regards

Pieter
 

---
*Reported from: https://www.ubuntu.com/support*

**Comment by pmahnke** [comment]
@pvannuff I updated the wiki... give it a read and let me know if you think it is ok.

**Comment by pvannuff** [comment]
Looks great, thanks a lot!
