### ISSUE TITLE
Twitter Webisite Tag installation request

### ISSUE THREAD

**Issue by Apeshere** [canonical-websites/www.ubuntu.com#1445]
Need to have one of the following code snippets installed on all ubuntu.com pages and insights.ubuntu.com; so that we can better track conversion rate through social channels. 

The image pixel code and AMP code can not be previewed, but you can see the code from the markdown script. let me know if I need to email the code seperately to you.

Instructions from twitter:
--------------------------------

### Install your website tag
If you are the person who will be installing the website tag, download the code snippet and place it at the bottom of all pages on your website before the </body> HTML tag. Visit the [website tag help and troubleshooting page](https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html?utm_source=twitterads&utm_medium=ads&utm_campaign=twitterads) for help.

<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','nwdth');
twq('track','PageView');
</script>

### Image pixel
The image pixel version of the website tag is appropriate for pages that cannot contain third-party JavaScript.

<img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nwdth&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0" />
<img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nwdth&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0" />

### AMP image pixel
If the tag will be placed on an AMP-enabled page, use the following code snippet for compatibility:

<amp-img height="1" width="1" style="display:none;" alt="" src="https://analytics.twitter.com/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nwdth&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0"></amp-img>
<amp-img height="1" width="1" style="display:none;" alt="" src="//t.co/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nwdth&events=%5B%5B%22pageview%22%2Cnull%5D%5D&tw_sale_amount=0&tw_order_quantity=0"></amp-img>

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
@apeshere can you email me the id.. .the markdown suggests that it is 0... and I assume that's wrong.

thanks

also,  what twitter account is this? @ubuntu?

**Comment by pmahnke** [comment]
I have added this... can you test?

**Comment by Apeshere** [comment]
yup, according to twitter pixel helper, both ubuntu and insights have the
pixel installed. But might take up to 24 hours for data come through.

If nothing shows up in the next two days, I will ping you again.

thanks

**Comment by pmahnke** [comment]
closing for now... reopen if it isn't working
