### ISSUE TITLE
submit button of find field is shifted down

### ISSUE THREAD

**Issue by pdragon** [canonical-websites/www.ubuntu.com#1452]
[https://www.dropbox.com/s/244nql4xsqyq3gh/Screenshot_2017-03-22_22-02-41.png?dl=0](url)

---
*Reported from: https://www.ubuntu.com/support*

**Comment by pmahnke** [comment]
@pdragon thanks for filing, this bug is about the help.ubuntu.com site... so I opened a [new bug there](https://bugs.launchpad.net/ubuntu/+source/ubuntu-docs/+bug/1675452) and am going to close this one.

**Comment by DougSmythies** [comment]
@pdragon : Could you please subscribe to the Launchpad bug report Peter entered and give us more details. I can not re-create your issue, so far.

**Comment by pdragon** [comment]
@DougSmythies
I use:
Lubuntu 16.04
Firefox 52.0.1 (x64)

done - has been subscribed
