### ISSUE TITLE
Bugs on Insights sticky RTP and insights subscribe

### ISSUE THREAD

**Issue by ae5202** [canonical-websites/www.ubuntu.com#1453]
## Summary
There's 2 issues on Insights, one is that the RTP sticky isn't displaying on webinar type posts (see 1st screenshot) and the second is that when trying to sign up to Insights updates there seems to be an issue as well (see 2nd screenshot)
[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result
1st problem: instead of showing the sticky RTP widget on the sidebar, I see the 'ubuntu cloud' with formatting issues.

2nd problem: sign up for email updates also looks like it's having formatting issues and the confirmation message looks strange. 

[describe what happened and what you expected]

## Screenshot
![image](https://cloud.githubusercontent.com/assets/12949954/24211243/53c3c06c-0f23-11e7-9f80-3b3a562925f2.png)

![image](https://cloud.githubusercontent.com/assets/12949954/24211218/43a90822-0f23-11e7-8130-f578de32ee85.png)

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
The fix has been proposed: https://code.launchpad.net/~ya-bo-ng/resource-centre/rtp-bugs/+merge/320881

**Comment by anthonydillon** [comment]
This has now been shipped.
