### ISSUE TITLE
Add facebook pixel on site

### ISSUE THREAD

**Issue by Apeshere** [canonical-websites/www.ubuntu.com#1467]
Need to have the following pixel code installed on both ubuntu.com and insights.ubuntu.com

This is the code to be used through google tag manager. 

<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '261183381006220'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=261183381006220&ev=PageView&noscript=1"
/></noscript>

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
added via GTM... removed "// Insert your pixel ID here. "
