### ISSUE TITLE
Add LinkedIn Insight Tag on websites

### ISSUE THREAD

**Issue by Apeshere** [canonical-websites/www.ubuntu.com#1468]
please add the following tag on ubuntu.com and insights.ubuntu.com. 

This can help us to track advertising conversion on LinkedIn

<script type="text/javascript">
_linkedin_data_partner_id = "43615";
</script><script type="text/javascript">
(function(){var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})();
</script>

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
added via GTM
