### ISSUE TITLE
UNetbootin freezes on macOS Sierra and is unable to create a bootable USB

### ISSUE THREAD

**Issue by helgeblod** [canonical-websites/www.ubuntu.com#1471]
After some digging I found that UNetbootin doesn't work with newer versions of macOS and is incapable of copying the .iso images to the USB-drive. My suggestion would be to update the docs to suggest using Etcher (https://etcher.io/) instead of UNetbootin on newer versions of macOS to "burn" the Ubuntu image. It's cross-platform, free, Open-source and works great.

---
*Reported from: https://www.ubuntu.com/download/desktop/create-a-usb-stick-on-macos*

**Comment by deadlight** [comment]
Thanks for the report.

We'll investigate the best solution for Mac users.

**Comment by pmahnke** [comment]
@helgeblod we have converted this to [a tutorial and updated to use Etcher](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-macos#3).

Let us know if you still have problems.
