### ISSUE TITLE
[small screen] buy.ubuntu.com - navigation needs to be fixed

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/www.ubuntu.com#1474]
## Summary
Mobile navigation is overlapping the content

## Current and expected result
Navigation should be fixed:
1- Make the same style as ubuntu.com ( with hamburger menu aligned with logo + shop pictogram)
2- Make sure the nav doesn't overlap the content

## Screenshot
<img width="398" alt="screen shot 2017-03-30 at 16 43 29" src="https://cloud.githubusercontent.com/assets/21334617/24543618/2a60ff7e-15f8-11e7-918a-e35a0be4fd22.png">

**Comment by frankiegranato** [comment]
Email to be sent to shopify to pass over the bug. Stef D knows who to contact.
