### ISSUE TITLE
[Mobile] Home page ubuntu intro images cutting off at smaller screen sizes

### ISSUE THREAD

**Issue by richmccartney** [canonical-websites/www.ubuntu.com#1481]
## Summary

When resizing the browser or viewing the home page on mobile the intro section 6 images get cut off as each list item is set to 32% width from desktop to mobile.

## Process

View the home page on an iPhone 5 or similar width / Resize the browser to less than 350px width

## Current and expected result

Currently the list containers cut the images, expect that the images shouldn't get cut off. I would suggest the class ```.ubuntu-intro__list-item``` gets set to ```width: 50%;``` on smaller screens. This also will improve the UX for the click areas on smaller screens, there is the possibility that on touch more than one image link can be interacted with.

Originally found by @joanasa89.

## Screenshot

<img width="325" alt="screen shot 2017-04-04 at 10 18 56" src="https://cloud.githubusercontent.com/assets/1201618/24649809/28da0a80-1920-11e7-90d9-fbb49ea5beea.png">

**Comment by pmahnke** [comment]
@richmccartney I think this is fixed... can you confirm?

**Comment by richmccartney** [comment]
Hi @pmahnke I would say it still needs some attention right now. This is a screenshot from what it looks like currently.

![image](https://user-images.githubusercontent.com/1201618/27631383-3e3ca244-5bf0-11e7-86c7-f3b291cb337b.png)
