### ISSUE TITLE
[Small screen] Global nav & back to the top links - fix font size on landscape view

### ISSUE THREAD

**Issue by joanasa89** [canonical-websites/www.ubuntu.com#1482]
## Summary
On landscape view (OS) global navigation and back to the top links look too small comparative with the rest of the content.

## Current and expected result
Font size should be the same across the different links.

## Screenshot
![img_5139](https://cloud.githubusercontent.com/assets/21334617/24650318/ba406d74-1921-11e7-9c8e-62dbae55a558.PNG)

**Comment by deadlight** [comment]
Fixed
