### ISSUE TITLE
Inaccurate information about the Canonical distribution of K8s bundle

### ISSUE THREAD

**Issue by ClaraLavina** [canonical-websites/www.ubuntu.com#1491]
Doing some research about K8s and reading all the available documentation and content we offer about this topic, I found some out-of-date information that should be revised as soon as possible.

https://www.ubuntu.com/containers/kubernetes

- 'Getting started' video has a wrong cover image of the Canonical Distribution of Kubernetes bundle.
- 'Analytics on tap' section. Update the part that says _'... a fully integrated Elastic Stack including Kibana for analysis and visualisations.'_
- 'Production features' section. Update bullet point _'Optional: Elastic Stack for Insights with Beats log collection and monitoring and analysis and visualisation with Elasticsearch and Kibana.'_
- In ['Learn more in the Canonical Distribution of Kubernetes datasheet'](https://pages.ubuntu.com/rs/066-EOV-335/images/Datasheet_Canonical-kubernetes_28.09.16_WEB.pdf?_ga=1.267479310.1009276208.1474452978) PDF. Again here a wrong image of the bundle has been used. Also, there are some references to Elastic Stack and Elasticksearch & Kibana that should be updated.

**Comment by pmahnke** [comment]
@ClaraLavina thanks for this.

could you update the [copy doc](https://docs.google.com/document/d/1VMu4i8rJHW7BXKiOiy36XVFsihVxrNEMzUHn3X2XabI/edit) highlighting the changes?

**Comment by ClaraLavina** [comment]
Copy updated :)

I don't have rights to update the copy for the [pdf link](https://pages.ubuntu.com/rs/066-EOV-335/images/Datasheet_Canonical-kubernetes_28.09.16_WEB.pdf?_ga=1.267479310.1009276208.1474452978). Changes here are:
- Update the image of the bundle
- Replace "and a fully integrated Elastic stack including Kibana for analysis and visualisations" with "and a fully integrated Elastic Stack for centralising all logs and metrics and get awesome dashboards for your cluster."

**Comment by pmahnke** [comment]
This was fixed by PR #1603
