### ISSUE TITLE
CRE bar (content recommendation engine) isn't visible on Insights

### ISSUE THREAD

**Issue by ae5202** [canonical-websites/www.ubuntu.com#1506]
## Summary

As part of Marketo we have CRE (now renamed Predictive Content) which basically is a bar that pops up across the bottom of the screen on Insights and proposes new content to visitors. 
I noticed that this bar isn't visible at the moment and am not sure why that is, can you please investigate?

## Process

Go to Insights and check if an orange bar appears across the end of the page after the cookie bar disappears. 

## Current and expected result

Bar needs to become visible again

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@ae5202 it is working now... closing

![image](https://user-images.githubusercontent.com/441217/27842217-e56c05e6-60ff-11e7-86f2-a9314eeff305.png)
