### ISSUE TITLE
Takeover include partial need review

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.ubuntu.com#1510]
There is a huge number of takeover partials in `templates/takeovers` - I assume many are outdated. 

Prior to Vanilla v1 migrations, these should be reviewed to determine which partials are still relevant.

**Comment by anthonydillon** [comment]
I believe we can come up with a better way of storing old takeovers.
Especially if they will not work with Vanilla v1.

**Comment by barrymcgee** [comment]
Absolutely - the repo should not contain old code, being able to retrieve old code for reference can be easily achieved with Git anyway.

**Comment by pmahnke** [comment]
can we just create a repo of all the old takeovers, take under and their associated css/js and leave the current and generic ones?

perhaps one day we could create some way to look through them, but not critical for now.
