### ISSUE TITLE
Donate page references convergence.

### ISSUE THREAD

**Issue by popey** [canonical-websites/www.ubuntu.com#1511]
## Summary

https://www.ubuntu.com/download/desktop/contribute

This page has a slider for convergence. Given recent announcements, this should probably not be there anymore.

## Process

Visit https://www.ubuntu.com/download/desktop/contribute

## Current and expected result

Got a slider for convergence.
Expected not to.

## Screenshot

[if relevant, include a screenshot]
![image](https://cloud.githubusercontent.com/assets/1841272/24880534/b18d0758-1e32-11e7-89d9-fb7522b2f882.png)

**Comment by davidjmedeiros** [comment]
All the website needs to be updated.
