### ISSUE TITLE
Tasks from Vanilla pattern inventory

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1562]
These are the patterns I've identified that don't exist in Vanilla or the brochure theme. I've divided them into: 
1. Needed in Vanilla
2. Vanilla customisations 
3. New custom patterns for ubuntu.com
4. Needs more work (either dev or des)

## 1. Needed in Vanilla:
- `<legend>` in fieldset

## 2. Vanilla customisations:
- List ticks should be orange
- Links to be orange on white and on light grey
- Links to be white on dark backgrounds (aubergine, dark grey)

## 3. Custom patterns to be created:
- Resource card - [cloud/public-cloud](https://www.ubuntu.com/cloud/public-cloud), [cloud/partners](https://www.ubuntu.com/cloud/partners), [cloud/storage](https://www.ubuntu.com/cloud/storage)
- Image aligned horizontally to the middle of the strip, that becomes more visible as the viewport increases - various places
- Very large input field - [search](https://www.ubuntu.com/search)
- Icon | Heading - [containers/overview](https://www.ubuntu.com/containers)
- Way to capitalise text - [cloud/openstack/autopilot](https://www.ubuntu.com/cloud/openstack/autopilot) and other places
- Way to make text 666 colour - I'm afraid I didn't write examples down, only made notes in Dropbox screenshots

## 4. Needs more work/thinking:
- List stepped detailed without white boxes on the right - [cloud/managed-cloud](https://www.ubuntu.com/cloud/managed-cloud)
- Small pull quote pattern - [desktop/enterprise](https://www.ubuntu.com/desktop/enterprise), [desktop/partners](https://www.ubuntu.com/desktop/partners), [desktop/education](https://www.ubuntu.com/desktop/education), [desktop/government](https://www.ubuntu.com/desktop/government): "Ubuntu in action"
- How do we do bigger spacing between elements? - [cloud/plans-and-pricing](https://www.ubuntu.com/cloud/plans-and-pricing), [support/plans-and-pricing](https://www.ubuntu.com/support/plans-and-pricing)
- Card with heading:
  - [cloud/contact-us](https://www.ubuntu.com/cloud/contact-us), [containers/contact-us](https://www.ubuntu.com/containers/contact-us) - sidebar 
  - [iot/overview](https://www.ubuntu.com/internet-of-things) - "From prototype to production on all major platforms"
  - [iot/digital-signage](https://www.ubuntu.com/internet-of-things/digital-signage) - "Partners and players"
  - Open issue: https://github.com/ubuntudesign/vanilla-design/issues/11
- Phone number strip - [support/overview](https://www.ubuntu.com/support)
- Text block positioning - [desktop/features](https://www.ubuntu.com/desktop/features) "Photos" and "Gaming"
- Ticks inside tables - [server/overview](https://www.ubuntu.com/server), [server/management](https://www.ubuntu.com/server/management), [support/plans-and-pricing](https://www.ubuntu.com/support/plans-and-pricing)

**Comment by pmahnke** [comment]
@yaili and @kwm14 is this captured anywhere else?... can we close this?

**Comment by yaili** [comment]
@pmahnke can close.
