### ISSUE TITLE
Remove tablets and phones from browser window title

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#1572]
## Summary

In the browser title, the Ubuntu homepage says 'The leading operating system for PCs, tablets, phones, IoT devices, servers and the cloud | Ubuntu'. Given Ubuntu Touch is officially abandoned (security updates until June, but given it's not actively developed the 'leading operating system for ... tablets, phones' claim seems off), this should read 'The leading operating system for PCs, IoT devices, servers and the cloud | Ubuntu'.

## Process

Open [the Ubuntu website homepage](www.ubuntu.com), read the browser title.

## Current and expected result

It says 'The leading operating system for PCs, tablets, phones, IoT devices, servers and the cloud | Ubuntu', it should say 'The leading operating system for PCs, IoT devices, servers and the cloud | Ubuntu'

## Screenshot

![screenshot from 2017-04-25 13-18-18](https://cloud.githubusercontent.com/assets/3178485/25384844/b04cb496-29b9-11e7-87b8-bd49e133a1fa.png)
![screenshot from 2017-04-25 13-18-56](https://cloud.githubusercontent.com/assets/3178485/25384861/c1542c10-29b9-11e7-8a3b-4d5107136065.png)

**Comment by anthonydillon** [comment]
Sorry @Ads2000. This issue should have been closed earlier as it was complete by https://github.com/canonical-websites/www.ubuntu.com/pull/1565.

**Comment by Ads20000** [comment]
No worries!
