### ISSUE TITLE
Update communication channels for 'Snaps on Ubuntu | Desktop | Ubuntu'

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#1573]
At the bottom of the 'Snaps on Ubuntu | Desktop | Ubuntu' page it says 'we have a fun crowd of people who hang out on the #snappy channel on Freenode or on the snapcraft mailing list', it should read 'we have a fun crowd of people who hang out on our [Rocket Chat](https://rocket.ubuntu.com/channel/snapcraft) or on [our forums](https://forum.snapcraft.io/)' or similar. These are the mediums of communication which we now use. See my approved PR for the Snapcraft README.md [here](https://github.com/snapcore/snapcraft/pull/1268).

---
*Reported from: https://www.ubuntu.com/desktop/snappy*

**Comment by pmahnke** [comment]
Thanks @Ads20000, I have put in a PR
