### ISSUE TITLE
Implement new homepage in VBT

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1649]

**Comment by frankiegranato** [comment]
COPYDOC: https://docs.google.com/document/d/1ySJxQbqVdeH4Tra0zwBm2Tn0s56kFGnEF7d8xDRTxwU/edit

**Comment by yaili** [comment]
New design and assets in Dropbox > _ubuntu.com > Homepage > Deliverables

**Note:** Containers illustration still to be finalised. Cloud image remains the same.
