### ISSUE TITLE
/legal section to VBT

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-websites/www.ubuntu.com#1665]
- [ ] https://www.ubuntu.com/legal/
- [ ] https://www.ubuntu.com/legal/bootstack/
- [ ] https://www.ubuntu.com/legal/bootstack/privacy/
- [ ] https://www.ubuntu.com/legal/bootstack/service-description/
- [ ] https://www.ubuntu.com/legal/contributors/
- [ ] https://www.ubuntu.com/legal/contributors/licence-agreement-faq/
- [ ] https://www.ubuntu.com/legal/contributors/submit/
- [ ] https://www.ubuntu.com/legal/contributors/thank-you/
- [ ] https://www.ubuntu.com/legal/short-terms/
- [ ] https://www.ubuntu.com/legal/short-terms/2015-06-24/
- [ ] https://www.ubuntu.com/legal/short-terms/2015-09-09/
- [ ] https://www.ubuntu.com/legal/short-terms/2016-05-20/
- [ ] https://www.ubuntu.com/legal/short-terms/ja/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/confidentiality-agreement/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/contact-us/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/intellectual-property-policy/2013-05-14/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/livepatch-terms-of-service/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/online-account-terms/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/privacy-policy/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/privacy-policy/2013-03-25/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/privacy-policy/third-parties/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/terms-of-service/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/terms/
- [ ] https://www.ubuntu.com/legal/terms-and-policies/thank-you/
- [ ] https://www.ubuntu.com/legal/ua-dell-tc/
- [ ] https://www.ubuntu.com/legal/ua-miracle-tc-ja/
- [ ] https://www.ubuntu.com/legal/ua-miracle-tc/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/assurance/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/service-description-ja/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/service-description/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/ua-terms-ja/
- [ ] https://www.ubuntu.com/legal/ubuntu-advantage/ua-terms/

**Comment by barrymcgee** [comment]
Demo: http://www.ubuntu.com-v1-legal-setup.demo.haus/legal

**Comment by barrymcgee** [comment]
Super-seded by https://github.com/canonical-websites/www.ubuntu.com/pull/1799
