### ISSUE TITLE
Nav menu items have underline on hover

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.ubuntu.com#1672]
This makes no sense:

https://cl.ly/3p0o0Z2w0i2c

**Comment by barrymcgee** [comment]
@yaili The vanilla navigation pattern has underlines on hover, why are we deviating?

**Comment by yaili** [comment]
Shall we move this to Vanilla @anthonydillon ?

**Comment by anthonydillon** [comment]
Yes, I always thought that was a mistake in Vanilla.

**Comment by yaili** [comment]
This issue was moved to vanilla-framework/vanilla-framework#1063
