### ISSUE TITLE
Remove EOL 12.04 from supported list

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [canonical-websites/www.ubuntu.com#1676]
12.04 just went EOL, so please remove it from the official list: http://releases.ubuntu.com/

**Comment by pmahnke** [comment]
@seventhsonofaseventhson  (now I have White Stripes in my head)

I can't move this bug, so can you refile here: https://bugs.launchpad.net/ubuntu-cdimage

this is for www.ubuntu.com

peter

**Comment by SeventhSonOfASeventhSon** [comment]
@pmahnke Sure

**Comment by SeventhSonOfASeventhSon** [comment]
@pmahnke Done: https://bugs.launchpad.net/ubuntu-cdimage/+bug/1690565
