### ISSUE TITLE
Open Directory listing Showing

### ISSUE THREAD

**Issue by dalvia62** [canonical-websites/www.ubuntu.com#1677]
Hello sir 

we found Open Directory Listing On http://cdimage.ubuntu.com/

I hope u will solve this bug fast

And Send Us Nice Feedback 
![screenshot 158](https://cloud.githubusercontent.com/assets/12573917/25562672/47735bba-2daa-11e7-9f6c-a089abe88e11.png)

Thank you
From
Rohit Dalvi
Hacker101

---
*Reported from: https://www.ubuntu.com/*

**Comment by deadlight** [comment]
Thanks for the report but this is intentional behaviour for used to browse the available files.
