### ISSUE TITLE
Cookie bar to VBT

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1678]
Updated the styling of the cookie bar to work with VBT

**Comment by yaili** [comment]
In small screen the notification is touching the edges, I don't think this is the Vanilla pattern, is it?

**Comment by deadlight** [comment]
@yaili Yes. https://docs.vanillaframework.io/en/patterns/notification
The padding is on the rows but notifications currently just fill the container that they're in. Which, in this case, is the whole page.

**Comment by yaili** [comment]
So could the notification be on the row?

**Comment by yaili** [comment]
@deadlight this is not in the demo yet, is it?

**Comment by barrymcgee** [comment]
@yaili I've just rebuilt the demo so it should be there now

**Comment by yaili** [comment]
The text shouldn't be centred in small screens, if this is a problem in Vanilla it should be added there as a bug instead: https://github.com/ubuntudesign/vanilla-design/tree/master/Notifications

**Comment by deadlight** [comment]
@yaili - I'll check if it's something local.

**Comment by deadlight** [comment]
@yaili It needed a local fix but I will check upstream to see where the centred text is coming from. I'm not sure that it's ever wanted.

**Comment by deadlight** [comment]
@yaili: ready for review on the demo: http://www.ubuntu.com-v1-about-demo.demo.haus/about
