### ISSUE TITLE
Ticks in lists seem to be positioned too high up

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1680]
In /about the ticks in lists seem to be 2-3 pixels too high up, they should align better with the first line of the text

**Comment by barrymcgee** [comment]
Is this also in Vanilla? https://docs.vanillaframework.io/en/patterns/lists

**Comment by anthonydillon** [comment]
Can you file issues on Vanilla so I can put them up.

**Comment by yaili** [comment]
@barrymcgee @anthonydillon Yes, it seems to be an issue in Vanilla. Want me to move it?

**Comment by barrymcgee** [comment]
@yaili Yes please, it'll then be corrected in due course..

**Comment by yaili** [comment]
This issue was moved to vanilla-framework/vanilla-framework#1057
