### ISSUE TITLE
Remove the inset shadow from search input field in M screens

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1689]

**Comment by yaili** [comment]
There is an odd orange bottom border, almost invisible now.

<img width="771" alt="screen shot 2017-05-04 at 17 08 56" src="https://cloud.githubusercontent.com/assets/223966/25713446/970c075e-30ec-11e7-9e52-363498e5d656.png">

**Comment by barrymcgee** [comment]
Can't replicate - what's the exact resolution you're seeing that at?

**Comment by yaili** [comment]
I see it in Chrome using the responsive inspect mode between 1028 and 768px, both inclusive.
