### ISSUE TITLE
Breadcrumb current page should be orange

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1691]
Reviewing /about section

**Comment by yaili** [comment]
It looks good, except when you are on a second level page which has children, like /about/about-ubuntu

See behaviour in https://www.ubuntu.com/about/about-ubuntu

**Comment by yaili** [comment]
@barrymcgee are you sure this has been updated in the demo?

**Comment by barrymcgee** [comment]
@yaili Sorry, missed a thing..
