### ISSUE TITLE
Tweaks to secondary navigation in small screens

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1693]
- The horizontal dividers should be full width (there is a small gap right now)
- Link style should be soft
- The current page font weight should be 400
- Spacing needs to be tidied up between items so that it's the same across all links - compare with live

**Comment by yaili** [comment]
- The gap in the horizontal dividers are still there, see screenshot (checked on my phone too)
- There is still too much space above the top items, the margin-bottom of .nav-secondary .p-breadcrumbs__link should probably be .5rem instead of 1

<img width="70" alt="screen shot 2017-05-10 at 09 22 29" src="https://cloud.githubusercontent.com/assets/223966/25889713/bb581cfe-3562-11e7-91fa-97e9f2485869.png">
<img width="53" alt="screen shot 2017-05-10 at 09 22 38" src="https://cloud.githubusercontent.com/assets/223966/25889717/bd33aca0-3562-11e7-95d4-a152265099de.png">

**Comment by barrymcgee** [comment]
@deadlight The gap to the right of the screen here is footer related as when I delete the footer node, it disappears. I've spent some time today trying to get to the bottom of it but no luck. The `<html>` element already has ` overflow-x: hidden !important;` applied to it. Any other ideas?

**Comment by anthonydillon** [comment]
I tend to continue to delete nodes until I uncover the culprit.
