### ISSUE TITLE
Alignment of nav items at medium (M) size screens

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1696]
None of the items aligns left: global nav, main nav, search box when opened, breadcrumbs - medium breakpoint

**Comment by yaili** [comment]
@barrymcgee search when open still doesn't align left. There's a 

#nav-global ul li:first-of-type a {
    margin-left: 10px;
}

on medium screen breakpoint that should be 0px, so that the global nav aligns too.

**Comment by anthonydillon** [comment]
@yaili I will pick up the global-nav styling issues upstream here: https://github.com/canonical-websites/vanillaframework.io/pull/13

**Comment by yaili** [comment]
So should I ignore the global when I review?

**Comment by anthonydillon** [comment]
Yes please.
