### ISSUE TITLE
Navigation links borders

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1699]
- ~~Can we please add the darker border between nav items (right now only has the lighter one)~~
- Last item of navigation needs right divider

**Comment by barrymcgee** [comment]
@yaili For clarity, can you specify the exact color variable to be used?

**Comment by yaili** [comment]
It should be a percentage of x-dark, I think 5% (0.05)

**Comment by barrymcgee** [comment]
So..using `lighten($color-x-dark, 0.95%);` - we get:

https://cl.ly/3t0d1M350x2p

That's not right, is it?

**Comment by yaili** [comment]
Need to see it next to the light border, not on its own. Can you add the light border back?

**Comment by barrymcgee** [comment]
@yaili Does it really need this custom borders? Wouldn't the Vanilla pattern suffice?

**Comment by yaili** [comment]
I could check in the next design review.

**Comment by yaili** [comment]
I think it would be good to see the border as they are currently (double-border) so that we can decide whether the design benefit is worth the extra lines in the code or not, does it make sense?

**Comment by yaili** [comment]
What's the status on this?

**Comment by deadlight** [comment]
@yaili Can this be closed?

**Comment by anthonydillon** [comment]
I believe this is still valid but we should investigate if we need to move
the issue to Vanilla.

**Comment by yaili** [comment]
@deadlight the second part is still valid, I'll edit the OP
