### ISSUE TITLE
Links in footer too small

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1701]
Contact us, about us, careers and press links in footer are too small in S screen and don't align with other links - compare demo to live

**Comment by deadlight** [comment]
@yaili The <small> tag, in vanilla is [documented as being 13px](https://docs.vanillaframework.io/en/base/typography#small-text) across all screens but there's a [bug](https://github.com/vanilla-framework/vanilla-framework/issues/1046).

**Comment by deadlight** [comment]
It looks like no work has been done on the fix yet. I'll fix it locally and propose upstream.

**Comment by deadlight** [comment]
It turns out the <small> being 13px across viewports is a bug, not a feature. So we're left with the issue of base font size changing between viewports but footer font sizes always being 13px. Is this something we would want to keep going forward or should we take this opportunity to make the font size scale.

**Comment by yaili** [comment]
Are you sure there have been changes? It looks the same to me. Would it be easier if there are no changes between large and small screen? Not sure why the layout changes here…

**Comment by deadlight** [comment]
@yaili Can you clarify what you mean. This issue is for font-size only, right? The font size of all links in the footer are 13px at all viewports just like on live. have I missed anywhere?

**Comment by yaili** [comment]
- I mean why are the links Contact, about, etc not the same as in large screen, why do they have to stack and the button disappears?
- The links are not all 13px in the footer, the sub-links, for example cloud/overview, are 13.872px
- The links Contact, About, etc still don't align with the links above, they're indented too much

Does this make sense?

**Comment by deadlight** [comment]
@yaili:

I fixed the subnav item size issues. that was complicated as it's part of the header styling too.

The links aren't the same in small screen, no, they stack and the button disappears, like on live. I'd be happy for this to not be the case (which would also remove the issue of the positioning and spacing of that stacked list being weird)

**Comment by deadlight** [comment]
The fix to the subnav sizing I mentioned is still awaiting a merge.

**Comment by yaili** [comment]
@deadlight what's the demo link?

**Comment by barrymcgee** [comment]
@yaili This should be on http://www.ubuntu.com-v1-about-demo.demo.haus/about

**Comment by yaili** [comment]
I don't see the contact us in a button. Is that right?

**Comment by deadlight** [comment]
@yaili: At small screen, yes. With the issues in trying to improve this section using inline lists I've decided to keep to the original scope and try and duplicate what we have on live.
