### ISSUE TITLE
Tweaks to back to top link in footer

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1702]
- Space above back to top link in S screen is too much - compare with live - space above and below the text should be the same in all footer small screen links
- Text in back to top link is too small, in S screen, should be the same as other links

**Comment by deadlight** [comment]
All links in footer are now 13px and the spacing is 20px top and bottom.

**Comment by yaili** [comment]
@deadlight what's the demo?

**Comment by deadlight** [comment]
@yaili: some padding changes have caused a regression on the padding. I'll fix it.

**Comment by deadlight** [comment]
yaili: ready for re-review here: https://github.com/canonical-websites/www.ubuntu.com/pull/1753

**Comment by deadlight** [comment]
@yaili Ready to review in the demo: http://www.ubuntu.com-v1-about-demo.demo.haus/about

**Comment by yaili** [comment]
The padding in the other footer links is 12px top and bottom, but in back to top is 16px top and bottom, if you make this change it's good to go.

**Comment by deadlight** [comment]
@yaili ok, done. Thanks.
