### ISSUE TITLE
Remove border above context. footer divider in /legal/bootstack

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1760]

**Comment by barrymcgee** [comment]
Footer now removed - see demo: http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/bootstack

**Comment by barrymcgee** [comment]
@yaili Design review needed

**Comment by barrymcgee** [comment]
@yaili Design review needed

**Comment by barrymcgee** [comment]
@yaili OK.. _now_ it should be removed 😅

http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/bootstack
