### ISSUE TITLE
/legal/bootstack/service-description has horizontal bar in S screen

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1775]
I think this is caused by tables

**Comment by barrymcgee** [comment]
Do you mean `<thead>` bottom borders? https://cl.ly/3C1J3a3L1R14

**Comment by yaili** [comment]
No, the tables are causing the page to have a horizontal bar in small screens.

**Comment by barrymcgee** [comment]
Oh.. you mean horizontal scroll?

**Comment by yaili** [comment]
Yes.

**Comment by barrymcgee** [comment]
Fixed, see demo: www.ubuntu.com-1792-service-desc-update.demo.haus/legal/bootstack/service-description
