### ISSUE TITLE
/legal/ubuntu-advantage/service-description update

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-websites/www.ubuntu.com#1792]
Please update the content on the page as per this copy doc: https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit

Page can't go live before stakeholders approve it on demo

**Comment by barrymcgee** [comment]
Demo: http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/ubuntu-advantage/service-description

**Comment by barrymcgee** [comment]
Demo: http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/ubuntu-advantage/service-description

**Comment by yaili** [comment]
Who needs to review this?

**Comment by barrymcgee** [comment]
@yaili Magda has already QA'd the demo link and I've now sent it to the Legal stakeholder, Chris Johnston, for sign off.

**Comment by yaili** [comment]
OK, thanks.

**Comment by barrymcgee** [comment]
Content has all been signed off by Chris Johnston and Magda.
