### ISSUE TITLE
Horizontal scroll on mobile

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1798]
On mobile (chrome on android, chrome device emulator) the right hand side escapes the screen an there is a slight horizontal scroll.

Currently live on `/about`

**Comment by yaili** [comment]
I think this is related to this one https://github.com/canonical-websites/www.ubuntu.com/issues/1739 which is marked as closed. @barrymcgee ?

**Comment by yaili** [comment]
Maybe related to this one too https://github.com/canonical-websites/www.ubuntu.com/issues/954

**Comment by barrymcgee** [comment]
@yaili Yes, @deadlight and I discussed this yesterday on Slack, we think it's a separate regression which is why this new issue was raised.

**Comment by yaili** [comment]
OK. I don't think this was ever fixed though.

**Comment by anthonydillon** [comment]
If it helps it appears to be the breadcrumbs.

**Comment by barrymcgee** [comment]
🍼👶🏻😜

**Comment by barrymcgee** [comment]
Yeah, it was the breadcrumbs the last time too, dunno how this regressed.. 🤔
