### ISSUE TITLE
Ubuntu pioneer portal is not working

### ISSUE THREAD

**Issue by rahulroopaljain** [canonical-websites/www.ubuntu.com#1800]
## Summary

Ubuntu pioneer portal (https://developer.ubuntu.com/pioneers) is not working any more, its throwing "500 proxy error", I have tried from different network and different location, but its not working since long time. I checked it 2 3 months back, and now today also from multiple places.

## Process

Just hit the URL: https://developer.ubuntu.com/pioneers

## Current and expected result

Current result is:- "500 Proxy error"
Expected:- "Portal should launch as it used to."

**Comment by WillMoggridge** [comment]
Thanks for this, I have created an issue on the Developer issue tracker if you could help in that issue:
https://github.com/canonical-websites/developer.ubuntu.com/issues/286
