### ISSUE TITLE
Nav padding is weird on Chrome on Ubuntu

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.ubuntu.com#1819]
See: https://github.com/canonical-websites/www.ubuntu.com/pull/1784#issuecomment-301525789

**Comment by nottrobin** [comment]
I think this is a duplicate of #1765. We shouldn't consider #1765 resolved unless it is also fixed for Chrome+Ubuntu. We should try to improve #1784 so that it fixes alignment on all principal browsers & OSs.
