### ISSUE TITLE
'License' should alway be referenced using British English - 'Licence'

### ISSUE THREAD

**Issue by ae5202** [canonical-websites/www.ubuntu.com#1827]
The title on this page: https://www.ubuntu.com/about/about-ubuntu/licensing is incorrectly spelt 'Licencing' instead of 'Licensing' and should be corrected.

**Comment by barrymcgee** [comment]
@ae5202 - we have a policy of using British English on all Canonical sites, including www.ubuntu.com so in this instance, 'Licencing' is correct.

However, your issue has drawn my attention to the fact the URL should also reflect this. 

Thank you for raising this issue.

**Comment by ae5202** [comment]
The copy on the rest of the site says licensing (which is why this typo was
pointed out to me).

**Comment by barrymcgee** [comment]
@ae5202 I'll do a full sweep of the site as part of this work issue. Should always be 'licensing'.

**Comment by deadlight** [comment]
Given that this is a verb use then "licensing" should be used. 'Licence' is just for the noun.
