### ISSUE TITLE
Orange Ubuntu bar dropdowns unreachable on some pages

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#1834]
Can't click on the orange Ubuntu bar dropdowns on the 'Download Ubuntu Desktop' webpage. Other things about that top bar seem different (see the GIF below), the very top bar is one less pixel tall, the orange Ubuntu bar is taller, the bar below that is smaller, and the orange bar links are underlined as you hover over them.

Also applies to [the 'Get OpenStack' webpage](https://www.ubuntu.com/download/cloud).

Firefox 53.0.2 on Ubuntu 17.04.

![peek 2017-05-25 01-52](https://cloud.githubusercontent.com/assets/3178485/26431494/1b8b971e-40ed-11e7-90dd-d4e321915d86.gif)

---
*Reported from: https://www.ubuntu.com/download/desktop*

**Comment by yaili** [comment]
This seems to be happening in all new Vanilla Downloads pages.

**Comment by deadlight** [comment]
I believe @grahambancroft is fixing this as part of his navigation refactor in the upgrade of the Vanilla version in Vanilla Brochure Theme.

**Comment by Ads20000** [comment]
Theming of the top bars is still inconsistent between the two pages I linked and the rest of the side, is there another Issue filed for this?
At least the drop-downs are clickable now, that's good!

**Comment by barrymcgee** [comment]
Hi @adconrad - we are currently in the process of moving www.ubuntu.com to an updated version of our CSS framework, Vanilla Framework. To minimise risk and ensure regular content updates to the site can still be performed, we're doing section by section, and in some cases, page by page. 

This will is why you're seeing the inconsistencies you outline above.
