### ISSUE TITLE
Small screen scrolling tables have some very narrow columns.

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-websites/www.ubuntu.com#1838]
## Summary

Whilst reviewing issue #1771 I noticed the small screen horizontally scrolling tables have some very narrow columns. Perhaps these can be wider so the content is easier to read, especially as we are already scrolling the table.

## Process

- Go to the demo - http://www.ubuntu.com-1792-service-desc-update.demo.haus/legal/terms-and-policies/privacy-policy
- Reduce the screensize
- View the 'purpose' column in the 'Cookies we use' table.

## Screenshot

![image](https://cloud.githubusercontent.com/assets/9105999/26444224/59a4fff4-4133-11e7-90eb-290239a5b407.png)

**Comment by pmahnke** [comment]
@kwm14 can you take a look at this?

**Comment by kwm14** [comment]
@pmahnke the demo link in this issue isn't available 'Unknown nginx-based subdomain'?

**Comment by pmahnke** [comment]
@spencerbygraves and @kwm14 I have fixed this by converting it to a table, but the issue might exist generically for other tables... might be a Vanilla thing to fix?

**Comment by spencerbygraves** [comment]
@pmahnke @kwm14 yes, it would be good to check in Vanilla too. Thanks
