### ISSUE TITLE
Vertical padding in contextual footer should be same as strip default

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1864]
The strip default spec has defined values for large, medium and small screens (which I'm not sure has been yet implemented or not, but doesn't match what's on the new ubuntu.com…) and the contextual footer padding should be exactly the same (I see no need for a new pattern to create the contextual footer padding.

Spec: https://github.com/ubuntudesign/vanilla-brochure-theme-design/blob/master/Strip/strip.md

Can we please have a look at this?

**Comment by deadlight** [comment]
Contextual footers are now a default strip.
