### ISSUE TITLE
Remove vertically-spaced from contextual footers

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1865]
Is it part of Vanilla? If so, it should be documented and the issue moved there (I can do that).

Or is it just for ubuntu.com?

Either way, it's adding extra top and bottom padding to the wrapper which adds to the padding of the strips - can we review this?

**Comment by barrymcgee** [comment]
Vanilla has this - https://docs.vanillaframework.io/en/utilities/vertically-center

**Comment by yaili** [comment]
If you look at a new ubuntu.com contextual footer, [example](http://www.ubuntu.com-1596-internet-of-things-robotics.demo.haus/internet-of-things/robotics), you can see the class I'm referring to, which doesn't have the same name as the one in Vanilla. 

It adds extra top and bottom padding to the contextual footer that isn't necessary/desired.

Can this please be looked into?

<img width="365" alt="screen shot 2017-05-30 at 21 53 23" src="https://cloud.githubusercontent.com/assets/223966/26604543/9951d840-4582-11e7-8670-e0920d907e42.png">

**Comment by barrymcgee** [comment]
This was added by @deadlight - Karl, can you please explain the rationale to @yaili?

https://github.com/canonical-websites/www.ubuntu.com/commit/9381de3b2bc51ba40b7be349563b996e84f4d77b

**Comment by deadlight** [comment]
@yaili we discussed this at the time I wrote it. It's a solution to the problem that many elements have no top or bottom padding.

It's currently only local to ubuntu.com. I've not proposed it up-stream to the theme or vanilla framework because I'm told that there is a work planned to solve all the vertical spacing issues in vanilla.

**Comment by deadlight** [comment]
It was first used on /support/esm but it's being used elsewhere.

I have proposed a more [general-purpose padding solution](https://github.com/vanilla-framework/vanilla-framework/issues/1091) to vanilla.

**Comment by deadlight** [comment]
@yaili the use I mentioned above doesn't impact on strip padding. I don't think that it should be used in that situation. A strip variant would be preferable, in that instance.

**Comment by yaili** [comment]
@deadlight so should we remove that from all contextual footers? That extra padding isn't needed/wanted there.

**Comment by deadlight** [comment]
@yaili That seems like a mistake. I'll remove them.
