### ISSUE TITLE
The "Download Ubuntu Core" CTA on the Core page is returning a 404

### ISSUE THREAD

**Issue by caldav** [canonical-websites/www.ubuntu.com#1873]
On https://www.ubuntu.com/core, the first CTA should now be linked to https://developer.ubuntu.com/core/get-started

**Comment by nottrobin** [comment]
What used to be at that location? Is it in any way covered under https://docs.ubuntu.com/phone/en/scopes/index ?

@pmahnke what's your feeling about this one?
