### ISSUE TITLE
incorrect link to "landscape"

### ISSUE THREAD

**Issue by crouchingtigger69** [canonical-websites/www.ubuntu.com#1880]
the link in the following text contains a broken link to landscape (includes "www" when it should not)
"Landscape server management
Landscape is the most cost-effective tool to support and monitor large and growing networks of desktops, servers and clouds."

---
*Reported from: https://www.ubuntu.com/support*

**Comment by barrymcgee** [comment]
@crouchingtigger69 Thank you for raising this issue. I've now submitted a fix to the above Pull Request.
