### ISSUE TITLE
Secondary navigation issue

### ISSUE THREAD

**Issue by ghost** [canonical-websites/www.ubuntu.com#1887]
## Summary

When you have many links in secondary navigation (e.g. https://www.ubuntu.com/legal/terms-and-policies), it breaks after the second item.

![screen shot 2017-06-01 at 15 24 37](https://cloud.githubusercontent.com/assets/16683435/26684299/754eda3a-46de-11e7-9ee9-b00bf6b465b1.png)

**Comment by yaili** [comment]
This had already been reported but somehow closed before being fixed: https://github.com/canonical-websites/www.ubuntu.com/issues/1747

**Comment by pmahnke** [comment]
this has been fixed

![image](https://user-images.githubusercontent.com/441217/29276852-d13ee8c2-8107-11e7-88e8-15a5bd8b83c6.png)

thanks for filing.

**Comment by yaili** [comment]
@pmahnke this is not following the way the [Vanilla breadcrumb pattern](https://docs.vanillaframework.io/en/patterns/breadcrumbs) scales down though

**Comment by pmahnke** [comment]
@yaili how do you mean?

**Comment by yaili** [comment]
The items shouldn't align left like in the example link from the OP. The second line should start left aligned with the first item in the breadcrumb. You can see how the example in the Vanilla docs wraps.

**Comment by anthonydillon** [comment]
After investigation, this is not to be done anymore. This will be complete by the navigation redesign.
