### ISSUE TITLE
broken charm/bundle links

### ISSUE THREAD

**Issue by kwmonroe** [canonical-websites/www.ubuntu.com#1888]
I see a few broken and/or outdated links on:

https://www.ubuntu.com/cloud/juju

In the charm section:
- Hadoop should be replaced with Kafka (https://jujucharms.com/kafka/)
- Spark should link to https://jujucharms.com/spark/
- The DB2 charm has a poor UX (it's not deployable without attaching pre-purchased software).  I'd recommend removing this.

In the bundle section:
- apache-core-batch-processing should be replaced with hadoop-processing (https://jujucharms.com/hadoop-processing)
- apache-hadoop-spark should be replaced with spark-processing (https://jujucharms.com/spark-processing)

---
*Reported from: https://www.ubuntu.com/cloud/juju*

**Comment by chuckbutler** [comment]
in addendum, the kubernetes link is also incorrect.

It should be replaced with one of our bundles, such as https://jujucharms.com/canonical-kubenetes

**Comment by pmahnke** [comment]
Hi, this is in a PR to be fixed.

I did this for charms

![image](https://cloud.githubusercontent.com/assets/441217/26762887/b6907746-4941-11e7-982b-dd7fbe96b3c5.png)

and this for bundles

juju deploy cs:bundle/canonical-kubernetes-38
juju deploy cs:bundle/spark-processing-53
juju deploy cs:bundle/openstack-base-49
juju deploy cs:bundle/wiki-scalable-0
juju deploy cs:bundle/django-2
juju deploy cs:bundle/hadoop-processing-59

let me know if you think anything else should be updated
