### ISSUE TITLE
Build kubernetes takeover

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1916]

**Comment by joanasa89** [comment]
Assets: https://assets.ubuntu.com/v1/a14dd2a9-kubernetes-takeover-desktop-background.png ; https://assets.ubuntu.com/v1/89f817b0-kubernetes-takeover-mobile-background.png

Folder: https://www.dropbox.com/sh/supuf2spo8i0xil/AAAJjHoSI93YhHYKqua-UssEa?dl=0

**Comment by joanasa89** [comment]
use the following svg: https://assets.ubuntu.com/v1/a16fb4d4-kubernetes-pattern.svg

**Comment by joanasa89** [comment]
Logo for mobile: https://assets.ubuntu.com/v1/331f3baf-kubernetes-logo.svg
