### ISSUE TITLE
Design for signpost

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#1922]
For vertical pages

**Comment by anthonydillon** [comment]
Shouldn't design tasks be issues on the Ubuntu.com design repo:
https://github.com/ubuntudesign/www.ubuntu.com-design

**Comment by deadlight** [comment]
@anthonydillon yes, probably. Just getting the hang of using Zenhub for these. Will move/clean up.

**Comment by yaili** [comment]
You can add the design repo to the ZenHub board

**Comment by deadlight** [comment]
Yeah. Sure. It was just that we were working off of epics on one board and put them in the wrong place. An oversight.

**Comment by deadlight** [comment]
This issue was moved to ubuntudesign/www.ubuntu.com-design#6
