### ISSUE TITLE
Breadcrumbs broken in S screen (live)

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#1931]
## Summary

Spacing and position of breadcrumb items at S screen is broken

## Process

Go to a page with 3rd level nav, e.g. https://www.ubuntu.com/about/about-ubuntu/our-philosophy or https://www.ubuntu.com/about/about-ubuntu

Reduce viewport size to small screen

## Current and expected result

- The alignment of the items should be the same as in second level, but the 3rd level items are all too close to each other
- All the items should align left
- In second level pages, the second level page title should align left too, it's a few pixels too much to the left

## Screenshot

**Third level**
<img width="562" alt="screen shot 2017-06-06 at 14 23 19" src="https://cloud.githubusercontent.com/assets/223966/26831382/09ea1842-4ac4-11e7-95b0-b185a4345a62.png">

**Second level**
<img width="446" alt="screen shot 2017-06-06 at 14 26 30" src="https://cloud.githubusercontent.com/assets/223966/26831455/431f5032-4ac4-11e7-9c99-9a242b433976.png">

**Comment by deadlight** [comment]
Related #1765
