### ISSUE TITLE
Search looks broken in master branch

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#1945]
I'm sure this will be fixed when someone implements #1577, but for the time being, search styling is broken in master, which is dangerous as presumably that means it might inadvertently go live:

![search-broken](https://user-images.githubusercontent.com/519935/26919764-b03ecd08-4c2e-11e7-955e-cd61876b10b5.png)

**Comment by pmahnke** [comment]
somehow my 1/2 finished work got pushed up!... my fault... however, I have a PR #1952 to fix it
