### ISSUE TITLE
Footer styling is incorrect at 768px

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-websites/www.ubuntu.com#1967]
## Summary

At 768px, the footer becomes stacked rather than horizontal.

## Process

View this [demo link](http://www.ubuntu.com-1656-desktop-developers.demo.haus/desktop/developers), shrink the screen to 768px wide and scroll to the footer

## Screenshot

![image](https://user-images.githubusercontent.com/9105999/27027898-f5062fce-4f5a-11e7-8d25-e25683cfb7c9.png)

**Comment by yaili** [comment]
Good one. I was trying to find an issue I thought I had filed about there being several issues at exactly 768px on Vanilla, but can't find it…
