### ISSUE TITLE
Cookie banner causing JS error in Safari v9

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.ubuntu.com#1983]
## Summary

- Fire up Safari on El Capitan (or Browserstack) and open site on Safari v9
- Reduce screen resolution to small screen
- Refresh screen
- Cookie banner function is breaking global nav
- See (3rd error in console): 

<img width="754" alt="screen shot 2017-06-14 at 16 57 22" src="https://user-images.githubusercontent.com/505570/27142444-f34635ca-5122-11e7-87c2-f5cabefe53f8.png">

**Comment by anthonydillon** [comment]
This issue has been moved to the cookie policy protect.
