### ISSUE TITLE
Content Recommendation Engine (Marketo) strip isn't working

### ISSUE THREAD

**Issue by ae5202** [canonical-websites/www.ubuntu.com#1990]
## Summary
Content Recommendation Engine (Marketo) strip isn't working. This is an orange strip that appears at the bottom of the page on Insights and pages (Marketo Landing Pages) and provides content recomendations. 

I've checked the Admin section in Marketo that deals with CRE and I see everything seems fine so not sure what the issue is. 

Admin page: https://sjrtp3.marketo.com/app/admin/accountSettings.do?isPredictiveApp=true

## Process

Unfortunately I can't provide a screenshot of what I should be seeing that I'm not (which is the issue) as it's just a pop-up that doesn't appear.

## Current and expected result

Expected result is for the orange pop-up strip to appear on Insights and pages (marketo landing pages)
![screen shot 2017-06-15 at 11 37 42](https://user-images.githubusercontent.com/12949954/27177767-74bfc264-51bf-11e7-9914-f95e82616dbc.png)
![screen shot 2017-06-15 at 11 37 34](https://user-images.githubusercontent.com/12949954/27177769-78f99760-51bf-11e7-900b-c404c5332699.png)
![screen shot 2017-06-15 at 11 37 17](https://user-images.githubusercontent.com/12949954/27177771-7a6e8dbc-51bf-11e7-85b8-2180211fcf66.png)

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
Sorry, I am not sure I understand the issue. Could you provide more information?

**Comment by ae5202** [comment]
Marketo has a sub-product called Content Recommendation Engine. It
basically adds a strip which looks like a footer to each page with content
titles and links to go read them. It used to be visible on Insights pages
and marketo landing pages but has disappeared. Not sure what other info
would help?

**Comment by pmahnke** [comment]
@ae5202 it seems to be working now.... lucia turned it on.
