### ISSUE TITLE
Build MAAS product page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2001]
## Summary

Build the new MAAS page:

[copy](https://docs.google.com/document/d/1A6Cp2zpbk7I5Rl_Novs4awbR5L97Bf9_DwFyU1D76pA/edit#)
[design (now out of date)](https://www.dropbox.com/work/00_web_team/_ubuntu.com/server/MAAS/Exports?preview=MAAS-page-new-template.jpg)

Edit:
[Newer design](https://www.dropbox.com/work/00_web_team/_ubuntu.com/server/MAAS/Exports?preview=MAAS-page-new-template.jpg)

**Comment by anthonydillon** [comment]
Is there any details for this work? Copy docs, designs?

**Comment by deadlight** [comment]
Design feedback

Hero:
[ ] - background 
  - new image
  - right edge not visible on medium screen
  - small screen just dark grey
 - H1 should be MAAS logo

Video
 - make heading standard H2 size and limit to 8 columns (don't let "of" wrap)

Muted headers to #666 

Video -> Webinar on last box

Icon headings - remove top padding if possible

Support: remove .is-deep

**Comment by deadlight** [comment]
The icon-headings problem is something I'm going to see if we can address with the pattern upstream
