### ISSUE TITLE
/cloud/openstack/autopilot uses old vanilla

### ISSUE THREAD

**Issue by grahambancroft** [canonical-websites/www.ubuntu.com#2004]
## Summary

/cloud/openstack/autopilot uses old vanilla

## Process

Go to https://www.ubuntu.com/cloud/openstack/autopilot

## Current and expected result

The page should use VBT

**Comment by anthonydillon** [comment]
## Some other old styling

### Pages
- /cloud/openstack/autopilot
- /support/contact-us
- /download/server/provisioning

### Includes
- /shared/_systems_management_tool.html
- /shared/_open_source_phone.html

### Takeovers
- /takeovers/_juju-generic-takeover.html
- /takeovers/_1704_takeover.html
- /takeovers/_core.html
- /takeovers/_kubernetes_takeover.html
- /takeovers/_maas_takeover.html
- /takeovers/_cloud_default.html
- /takeovers/_advantage.html

**Comment by deadlight** [comment]
@anthonydillon Thanks for looking at this. I think we can remove the majority of these templates. I'll fix this issue first and then have a look at the list separately.

**Comment by pmahnke** [comment]
#2005 fixes /support/contact-us, they were just extra, unused divs

/shared/_open_source_phone.html could be deleted... it isn't used
nor is /shared/_systems_management_tool.html 

the takeovers are leftover, not sure we need them

**Comment by pmahnke** [comment]
PR #2006 fixes /download/server/provisioning
