### ISSUE TITLE
Logo bug on the partner site

### ISSUE THREAD

**Issue by udinachmany** [canonical-websites/www.ubuntu.com#2008]
## Summary

When I tick "Featured" and "Always featured" for partner Packet, I get a white space on https://partners.ubuntu.com/programmes/public-cloud

## Process

See above

## Current and expected result

See above

**Comment by pmahnke** [comment]
I have no idea why this is happening, but I changed the format to png and it works.

`https://assets.ubuntu.com/v1/3f403c1f-logo.svg?fmt=png`

![image](https://user-images.githubusercontent.com/441217/27627772-e8c1b6ca-5be4-11e7-8399-8a52434aa216.png)
