### ISSUE TITLE
Hand over RTP knowledge to marketing team

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#2028]

**Comment by joanasa89** [comment]
Case study: https://assets.ubuntu.com/v1/cc61684f-case-study-icon.svg
e-book: https://assets.ubuntu.com/v1/57364a8b-e-book-icon.svg
white-paper: https://assets.ubuntu.com/v1/cd7a3a3c-white-paper-icon.svg

Designs: https://www.dropbox.com/sh/ybzqy5nh5eqh4f1/AAAOQ2ON9HzxZxlc-X5RigDZa?dl=0
