### ISSUE TITLE
StuckStack takeunder: Build it!

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#2029]

**Comment by joanasa89** [comment]
Asset: https://assets.ubuntu.com/v1/c8efedd7-OpenStack_Logo_white.svg
Dropbox folder: https://www.dropbox.com/sh/lo56exwxnswvl6l/AAAXqF4frNH-k6-9fmSLXuGRa?dl=0

**Comment by deadlight** [comment]
https://docs.google.com/document/d/1rTHWfeuZbusH_nMBY2QJmoUSdKYTDQucLu1qYXZd_nU/edit?ts=595662bc#
