### ISSUE TITLE
K8s takeunder: Build it!

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#2030]

**Comment by frankiegranato** [comment]
Copy: https://docs.google.com/a/canonical.com/document/d/1xxhBZERkuc6OXSTB-WDO39TU6DlXEN66RT0g-z1zQGA/edit?usp=sharing

**Comment by joanasa89** [comment]
Assets: https://assets.ubuntu.com/v1/331f3baf-kubernetes-logo.svg
Dropbox folder: https://www.dropbox.com/sh/lo56exwxnswvl6l/AAAXqF4frNH-k6-9fmSLXuGRa?dl=0
