### ISSUE TITLE
Partner order in Finder not alphabetic

### ISSUE THREAD

**Issue by udinachmany** [canonical-websites/www.ubuntu.com#2034]
## Summary

On https://partners.ubuntu.com/find-a-partner?programme=certified-public-cloud for some reason, updating cloud.ca pushed them to the end, in an alphabetised list

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
This issue was moved to canonical-websites/partners.ubuntu.com#133
