### ISSUE TITLE
Amendment to /ubuntu-advantage/service-description-ja

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2038]
Re https://www.ubuntu.com/legal/ubuntu-advantage/service-description-ja

We need to amend the date of the 'previous version' 
We need to add a disclaimer to the top of the page

Both these amends are specified in the copydoc: https://docs.google.com/document/d/1Tpf4FuP6SzvfyFw-nlR44uAIkofNdwzDaJFY36ZAk68/edit#heading=h.h56jjaoky4l0

**Comment by deadlight** [comment]
Updates now live
