### ISSUE TITLE
Incorrect link to Hastexo on-line OpenStack course

### ISSUE THREAD

**Issue by idobos71** [canonical-websites/www.ubuntu.com#2044]
The link to OpenStack 101 by Hastexo does not work correctly.
The original link: https://academy.hastexo.com/courses/course-v1:hastexo+hx201+201610-juju/about
The correct link (my guess only): https://academy.hastexo.com/courses/course-v1:hastexo+hx201+201706-juju/about

---
*Reported from: https://www.ubuntu.com/cloud/training*

**Comment by pmahnke** [comment]
@idobos71 thanks for this!

@deadlight @frankiegranato I think the link will change all the time.  I asked Arturo if we should just link to their main site.  I will update when I hear back... for now, I think that's safer.

**Comment by frankiegranato** [comment]
I've also left a comment in the copydoc addressed to Arturo asking the question.
