### ISSUE TITLE
Problem with http://ipv6.torrent.ubuntu.com/

### ISSUE THREAD

**Issue by PacketGit** [canonical-websites/www.ubuntu.com#2048]
Hello,

The IPv6 tracker listed at this page http://ipv6.torrent.ubuntu.com/ seems to have a problem.
The tracker ipv6.torrent.ubuntu.com listening on port 6969 is giving an error message when trying to use it with the torrent files on the page that point at it. 

     d14:failure reason63:Requested download is not authorized for use with this tracker.e

I tried using this about 8 weeks ago and it seemed to be working then.

Can you verify your IPv6 tracker is working? I have to do this from an IPv6-only connected machine so cannot use the IPv4 tracker.

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
I have requested information on the website as I have seen this site before. With reply when I have this information.

**Comment by anthonydillon** [comment]
This is hosted by ubuntuv6tracker.bit.nl, who are reachable via mirror@bit.nl. Therefore not something we can rectify I am afraid.

**Comment by PacketGit** [comment]
I will follow up with them. Thanks.
