### ISSUE TITLE
Nav drop-downs disappearing 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2052]
Unable to select menu items from the main nav drop down menus. The drop down disappears before user is able to move curser to make a selection. 

---
*Reported from: https://pages.ubuntu.com/stuckstack_webinar_upgrades_register.html?utm_source=ubuntu.com

**Comment by anthonydillon** [comment]
Do you mean on small screens? I can't replicate it with chrome on Android. Could you please let me know which browser and device you are using?

**Comment by frankiegranato** [comment]
I am seeing this on normal screen - my macbook air (mac OS 10.10) on google chrome Version 59.0.3071.115 . I checked again just now and its still happening.

**Comment by anthonydillon** [comment]
Thanks for the details. I think I know what is causing it. Will have a fix
shortly.

**Comment by deadlight** [comment]
@anthonydillon What's the status of this. Should it go into our normal bug pipeline or have you got somewhere with it?

**Comment by anthonydillon** [comment]
@deadlight This is ready to be worked on. I believe this is a z-index issue on this page: https://www.ubuntu.com/cloud.

**Comment by deadlight** [comment]
I can no longer replicate this and so will close it.

@frankiegranato please reopen this issue if you can still replicate it.

**Comment by anthonydillon** [comment]
Have you tried the cloud overview page. I believe it had something to do
with the image having a higher z-index.
