### ISSUE TITLE
A small bug on the site.

### ISSUE THREAD

**Issue by NikolayDenisov** [canonical-websites/www.ubuntu.com#2061]
Hello Ubuntu team.

![2017-07-13 15-11-43](https://user-images.githubusercontent.com/23256858/28161782-4cae34a6-67de-11e7-9f85-95ee83effaf5.png)

---
*Reported from: https://www.ubuntu.com/download/desktop/contribute?version=17.04

**Comment by deadlight** [comment]
Hello Nikolay,

Thanks for the bug report.

I cannot replicate the issue you are experiencing. The site has had many updates recently, can you confirm that the bug is still present.

If the bug is still visible to you, could you please let me know which browser and operating system you are using? 

Thanks,
Karl

**Comment by NikolayDenisov** [comment]
Hello Karl.
Error is present.

1) Browser

```
Firefox 54.0 (64-bit)
```
2) OS

```
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.04"
VERSION_ID="17.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=zesty
UBUNTU_CODENAME=zesty
```
3) Link

```
https://www.ubuntu.com/download/desktop/contribute?version=17.04&architecture=amd64
```

4) Attach

![bug](https://user-images.githubusercontent.com/23256858/29115029-8a537d66-7d0f-11e7-9f07-ee0e9597a49a.png)

**Comment by deadlight** [comment]
Ah, I see. It's only when all of the sliders are set to "0" and the button disappears. Thanks for clarifying.

**Comment by NikolayDenisov** [comment]
=)
