### ISSUE TITLE
Add logo to certification.ubuntu.com

### ISSUE THREAD

**Issue by wililupy** [canonical-websites/www.ubuntu.com#2067]
## Summary

Hello, one of our partners, Penguin Computing, would like to have their logo added to the other logos that are shown on the "Become Ubuntu Certified" section of the site.

## Process

They are a paying partner that we have certified their hardware with Ubuntu as well as a reseller and hardware/switch vendor that all run Ubuntu.

## Current and expected result

Have the enclosed logo added to the site.

I have enclosed two versions of their logo, one is a standard size web logo and the other is a larger vectored graphic that we can adjust to fit the site. They are both in png format.
![logo_penguin-computing_blktxt_500x227](https://user-images.githubusercontent.com/17133934/28189457-d6f136ee-67da-11e7-9f96-9dce56fc2a25.png)
![logo_penguin-computing_blktxt_vector_1266x600](https://user-images.githubusercontent.com/17133934/28189459-d9e201e4-67da-11e7-80fe-01adf77dd654.png)

**Comment by deadlight** [comment]
Thanks for the issue report.
I'll get this work into our backlog and see when we can fit it in.

**Comment by wililupy** [comment]
Do you have an updated when this will be completed? The partner is requesting.

**Comment by deadlight** [comment]
I have picked this issue up now and hope to complete it soon.

**Comment by deadlight** [comment]
@wililupy this subdomain is managed outside of the main ubuntu.com website and outside of the web team. I'm still trying to chase up to see if we can get this added.

**Comment by codersquid** [comment]
Hi @deadlight I'm part of the team that works on that subdomain. :wave:

**Comment by deadlight** [comment]
Apologies for the delay, @wililupy, I overlooked this piece of work when actioning issues.

Thanks, @codersquid, can I hand this request to you/your team? If so, should I raise a bug elsewhere?

It's also worth noting that we can provide a json feed from https://partners.ubuntu.com/find-a-partner, all we would need is a list of criteria (we also have a concept of a "featured" partner, if that would help special cases such as this).

Please feel free to ask if there's anything else I can do to resolve this.

**Comment by deadlight** [comment]
Ah, I saw the launchpad change, thanks.

**Comment by codersquid** [comment]
@deadlight oh, interesting. I was not aware of the partner feed. But, I'd like to change things around entirely. Ideally, though, I'd like for the certification team to provide an API to your team so that we could have the certification subdomain run out of this app rather than our old django app. It would make a lot more sense that way.

**Comment by codersquid** [comment]
This is deployed now. https://certification.ubuntu.com/

**Comment by wililupy** [comment]
Thank you so much for completing this.
