### ISSUE TITLE
Build UA price pages

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#2077]
Breif: https://docs.google.com/a/canonical.com/document/d/1QA4aiDxBjDsqpa0s5iHocmChxTrnQ1ibrSDjCXIw2Ls/edit?usp=sharing

**Comment by joanasa89** [comment]
Price cards
https://www.dropbox.com/s/730kk330f7xyvg5/Cloud%3Aovrview%3Apernode.jpg?dl=0)
