### ISSUE TITLE
"Try it now" CTA on www.u.c/containers/kubernetes could be smoother

### ISSUE THREAD

**Issue by mikemccracken** [canonical-websites/www.ubuntu.com#2081]
The "Try it Now" button on this page:
https://www.ubuntu.com/containers/kubernetes

leads to https://conjure-up.io

which isn't kubernetes-specific, so it seems possible to get lost there.

If you persist, that page does give you text instructions for kubernetes in a box in the "conjure-up spells" section.

However, that box also has a link, "Kubernetes with conjure-up", which is this link:
https://www.ubuntu.com/containers/kubernetes#getting-started-video

So, you get sent back to the page you may have just come from -- and that anchor seems to be missing, so you end up at the top instead of at the big embedded video a couple screens down.

Also, that video is out of date, which I'll file as a separate bug.

---
*Reported from: https://www.ubuntu.com/containers/kubernetes

**Comment by deadlight** [comment]
Thanks for the report. We are in the process of refreshing the content and updating the layout of this page.
I've added it to the list of items to be addressed in this work.

**Comment by deadlight** [comment]
We're going to roll out a more tailored tutorial to solve this issue.
