### ISSUE TITLE
Getting started video on www.u.c/containers/kubernetes is out of date

### ISSUE THREAD

**Issue by mikemccracken** [canonical-websites/www.ubuntu.com#2082]
## Summary

The embedded "getting started" video on containers/kubernetes starts off by adding PPAs for conjure-up and juju, and installing them via their packages.

I think the only supported way to install conjure-up now is via snaps, as per https://conjure-up.io 

---
*Reported from: https://www.ubuntu.com/containers/kubernetes

**Comment by deadlight** [comment]
Thanks for the report. 
Similarly to your other report, #2081, this content is in the process of being updated and reorganised. I will put this forward to be addressed in this work, too.

**Comment by frankiegranato** [comment]
A new version of the /kubernetes page has been released on ubuntu.com, but we haven't yet been able to update the video. However, we do have someone working on a new video and we hope to have it published on the page shortly (hopefully within two/three weeks).
