### ISSUE TITLE
OpenStack 101 link 404's

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#2084]
Link to OpenStack 101 by Hastexo results in a 404.

---
*Reported from: https://www.ubuntu.com/cloud/training*

**Comment by deadlight** [comment]
Thanks for the bug report.
It looks like the page has been moved at their end. We'll get the new link and update it as a priority.

**Comment by deadlight** [comment]
Replace with link to homepage

**Comment by nottrobin** [comment]
I think this may no longer be an issue.

**Comment by deadlight** [comment]
@nottrobin correct! Closing.
