### ISSUE TITLE
Navigation prototype (phase 2)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2087]
## Summary

As part of an ongoing effort to evolve the ubuntu brand, we have proposed a new way to style the ubuntu.com navigation. In order for our stakeholders (and ourselves) to make an informed decision about the viability and usability of the new designs, we would like to see it in prototype form (ie. a fully interactive version of ubuntu.com with a working re-style nav in place). 

## Process
Joana will handover a visual which describes the designs for the new nav. She will also include specifics such as hex codes for colours. She will add these visuals in to this issue. 

A developer will then begin building the prototype using the magical power of Vanilla.

**Comment by deadlight** [comment]
@anthonydillon @frankiegranato can you check that this is still needed and triage it as appropriate, please?

**Comment by anthonydillon** [comment]
@deadlight @frankiegranato I believe this is complete

**Comment by deadlight** [comment]
Cool. I'll close and we can re-open if it's incorrect.
