### ISSUE TITLE
Typo on UASD

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#2089]
2.4.42.4.4 Access to Canonical Livepatch Service is included with all support offerings, unless otherwise noted.

---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage/service-description*

**Comment by deadlight** [comment]
Thanks Chris.

I'll see if I can get this quick fix out ASAP.

- Karl

**Comment by deadlight** [comment]
This fix is now live.
