### ISSUE TITLE
Ubuntu Advantage Price updates (07.17)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2093]
These are the updates as I've understood them. I've nick named this piece of work UA 07.17 updates.

cloud/openstack: 
No changes to this page. See copydoc: https://docs.google.com/document/d/12z6QEGpqMVbNPJOd5aUfn0VnXQ0Sa5YriEBLA7VGNwI/edit

cloud/plans-and-pricing:
Various changes. See copydoc:
https://docs.google.com/document/d/1yZ7wClcmxGCqMyyyBJLO66Z3YlpT-4soWLFmJ6uXeMM/edit#

/support/plans-and-pricing:
Various changes. See copydoc: 
https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit

/support: 
One change to intro paragraph. See copydoc:
https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit

**Comment by pmahnke** [comment]
@frankiegranato can you confirm this can be closed? we think they are all done.

**Comment by frankiegranato** [comment]
the only outstanding edit left to do is to the /support page. I will file it as a bug  and close this issue.
