### ISSUE TITLE
Foundation Cloud Updates - Build (FC Updates)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2094]
Build new product page /cloud/foundation-cloud: 
https://drive.google.com/open?id=1f83OSIHVQGMjF7b0pZUKFvoubMGqi_b-OYbSpyhveX4

Section added to /cloud/plans-and-pricing:
https://docs.google.com/document/d/1yZ7wClcmxGCqMyyyBJLO66Z3YlpT-4soWLFmJ6uXeMM/edit?usp=sharing

Small updates to /cloud/openstack: 
https://docs.google.com/document/d/12z6QEGpqMVbNPJOd5aUfn0VnXQ0Sa5YriEBLA7VGNwI/edit#

**Comment by deadlight** [comment]
https://www.dropbox.com/sh/g38zhigxzcaea8x/AABUsGC8NVKV8SVJSwWlYCQJa?dl=0
