### ISSUE TITLE
Replace YouTube video with Vimeo for lead-gen

### ISSUE THREAD

**Issue by lamesdonner** [canonical-websites/www.ubuntu.com#2096]
Recently, we've been working to replace our YouTube videos with ones off of Vimeo. Unlike YouTube, using Vimeo allows us to capture leads using a form that appears at the end of each video. This will help us gather interest during the marketing stages, and also provide a more actionable approach to our webpages with one simple switch.

Here is the embed code:

<iframe src="https://player.vimeo.com/video/225445183" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

In addition, we can integrate with Google Analytics by embedding this below the GA script.

<script type="text/javascript" defer="defer" src="https://extend.vimeocdn.com/ga/57997584.js"></script>

More information on this subject can be found at https://help.vimeo.com/hc/en-us/articles/224980588-Integrating-with-Google-Analytics?flash_digest=0c148ec8b7cf37beab4a7622e5682b8e63f323fd

---
*Reported from: https://www.ubuntu.com/server/livepatch*

**Comment by anthonydillon** [comment]
Does this video replace the one in the "Install in under a minute" section
on https://www.ubuntu.com/server/livepatch?

**Comment by lamesdonner** [comment]
Yes. It's the exact same video, but with a player that's better optimized and can generate leads while we're at it.
