### ISSUE TITLE
Add GA Vimeo Integration

### ISSUE THREAD

**Issue by lamesdonner** [canonical-websites/www.ubuntu.com#2097]
In order to get GA details from our vimeo embed on the page, we can now use a tracker that goes underneath the regular GA HTML script. The code can be found at

<script type="text/javascript" defer="defer" src="https://extend.vimeocdn.com/ga/57997584.js"></script>

More information at https://help.vimeo.com/hc/en-us/articles/224980588-Integrating-with-Google-Analytics

---
*Reported from: https://www.ubuntu.com/download/cloud/conjure-up*

**Comment by pmahnke** [comment]
@lamesdonner I have added this to www.ubuntu.com with various events... let me know if it works for you.
