### ISSUE TITLE
Build updates cloud overview

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#2098]

**Comment by joanasa89** [comment]
![cloud-overview-page](https://user-images.githubusercontent.com/21334617/28879341-cbeba8aa-7799-11e7-880a-7528d1e89af4.jpg)
Find on dropbox: https://www.dropbox.com/s/mofr93c74wbq17b/Cloud-overview-page.jpg?dl=0

**Comment by deadlight** [comment]
I'm postponing work on this issue until the content has settled down.
