### ISSUE TITLE
Ubuntu 16.04 64 bit server edition torrent link results in a 404 page

### ISSUE THREAD

**Issue by GabrielSturtevant** [canonical-websites/www.ubuntu.com#2118]
![screenshot-20170803085425-1877x1053](https://user-images.githubusercontent.com/17666816/28931043-a80cc19a-7829-11e7-9048-435b518efe53.png)

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
@GabrielSturtevant thanks for filing this.

Can you try again?  I think either the site was down, or we were updating to 16.04.3

Otherwise, reopen this and I will look into it more.

Peter

**Comment by GabrielSturtevant** [comment]
It seems to be working fine now.
