### ISSUE TITLE
Redirect from https://www.ubuntu.com/usn/ to https://usn.ubuntu.com/usn is broken

### ISSUE THREAD

**Issue by tgm4883** [canonical-websites/www.ubuntu.com#2128]
## Summary
The redirect for USN (https://www.ubuntu.com/usn/ to https://usn.ubuntu.com/usn) is broken. It instead redirects to https://usn.ubuntu.com/usn%7Bpage%7D which gives a 404

## Process

1. Go to https://www.ubuntu.com/usn/ (This is the page that is linked from search engines such as google) and get redirected to the wrong page.

## Current and expected result

Current. 
You get redirected to https://usn.ubuntu.com/usn%7Bpage%7D

Expected
You get redirected to https://usn.ubuntu.com/usn

**Comment by deadlight** [comment]
Thank you for the bug report.

This has been fixed.
