### ISSUE TITLE
Pricing table should not be using chevrons

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#2137]
## Summary

Using chevrons when it should be using of greater than, less than symbols

## Process

Got to https://www.ubuntu.com/cloud/plans-and-pricing
Scroll to Service provider pricing table
See the first row is using chevrons

Also make sure to check if this is happening anywhere else on the site

**Comment by nottrobin** [comment]
@pmahnke you reopened this? Is it still relevant?

**Comment by pmahnke** [comment]
@nottrobin I mistakenly closed it , then reopened, but it has been fixed... so now... closing on purpose
