### ISSUE TITLE
Provide example RTP HTML and list of element IDs to marketing

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#2141]

**Comment by pmahnke** [comment]
I wrote a doc to help with how to update the HTML:

https://docs.google.com/document/d/1IYePhyQsgIhkCga1djygM4TJZQceetnQtiFjXfVsJM8/edit#

Also an html builder:

https://docs.google.com/spreadsheets/d/1KH2fYY_i1erA5ogURMuhC30WydGlatbhJsO0GFx7p_s/edit#gid=0

We might have to adjust to the builder to be a bit more greedy, depending on if RTP overwrites the div it is using, or just inside the div.

Please let me know if you have questions.
