### ISSUE TITLE
https://developer.ubuntu.com/api/apps/qml/current

### ISSUE THREAD

**Issue by office-work-account** [canonical-websites/www.ubuntu.com#2167]
https://developer.ubuntu.com/api/apps/qml/current
Message:
404: Page not found
Sorry, we couldn’t find that page.
---
*Reported from: https://www.ubuntu.com/desktop*

**Comment by caldav** [comment]
Hello, the page you are looking for has been moved here https://docs.ubuntu.com/phone/en/apps/api-qml-current/index
