### ISSUE TITLE
https://developer.ubuntu.com/api/apps/qml/development

### ISSUE THREAD

**Issue by office-work-account** [canonical-websites/www.ubuntu.com#2168]
https://developer.ubuntu.com/api/apps/qml/development
Message:
404: Page not found
Sorry, we couldn’t find that page.
---
*Reported from: https://www.ubuntu.com/desktop*

**Comment by caldav** [comment]
Hello, the page you are looking has been moved here https://docs.ubuntu.com/phone/en/apps/api-qml-development/index
