### ISSUE TITLE
Using incorrect MAAS logo

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/www.ubuntu.com#2174]
On https://www.ubuntu.com/server/maas we're using the wrong MAAS logo in the hero section at the top of the page. Please update to new logo attached below.

### New logo
https://assets.ubuntu.com/v1/4fac1d52-MAAS-Logo.svg

---
*Reported from: https://www.ubuntu.com/server/maas*

**Comment by pmahnke** [comment]
@kvm14 - is this the logo? 

https://assets.ubuntu.com/v1/0de4fcd5-logo-maas-icon.svg

**Comment by kwm14** [comment]
@pmahnke nope this is the logo you need for that page.

https://assets.ubuntu.com/v1/4fac1d52-MAAS-Logo.svg

Thanks
