### ISSUE TITLE
Retire or archive unity.ubuntu.com

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2180]
Since Unity is no longer under active development, [unity.ubuntu.com](https://unity.ubuntu.com/) should be either retired, or converted to a read-only exhibit without comment forms and chat frames. The site hasn’t been touched in about five years.

(Apologies if this is the wrong place to report the bug; this site doesn’t seem to have a repo.)

**Comment by anthonydillon** [comment]
RT has been filed.

**Comment by anthonydillon** [comment]
The unity website has been retired.
