### ISSUE TITLE
Review copy on /download/server/thank-you

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2184]
Copy doc: https://docs.google.com/document/d/1S5zY7HN_Q8eQWch0mCEfLICfj8pW1bct9_wGArCNIqc/edit

**Comment by pmahnke** [comment]
s/It features Autopilot, the fastest way to build an OpenStack cloud/It features Autopilot, the fastest way to build an OpenStack cloud/

this is ready
