### ISSUE TITLE
UX for /cloud (autopilot)

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2190]
Copy doc: https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit

**Comment by frankiegranato** [comment]
Hi @anthonydillon I've prepared the content for /cloud but I do think we will need a designer to help with this page. All the sections have been moved around and I've added a section. Shall we talk it through?
