### ISSUE TITLE
Replace 'Autopilot' content in all contextual footers

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2197]
please ensure that we replace the 'autopilot' mentions in all default contextual footers. I have amended the copydoc accordingly. 
Contextual footer copydoc: https://docs.google.com/document/d/1kq0SPv-PAIfL9nHGxgNDpHhr5OplE2iNaZZiqG4RT48/edit#

**Comment by anthonydillon** [comment]
This is a duplicate of https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2188
