### ISSUE TITLE
“How to upgrade your OpenStack cloud” video is AWOL

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2219]
1. In a Firefox Private window, go to https://pages.ubuntu.com/stuckstack_webinar_upgrades_register.html?utm_source=ubuntu.com
2. Try to watch the video.

What happens:
- There is no video on the page.
- There is no link to the video on the page.
- There is a heading “Watch webinar”, but that section contains only the plain text “On-demand”.

![www ubuntu com-2219](https://user-images.githubusercontent.com/19801137/30536959-d06e3f9c-9c5f-11e7-8bbd-a4648a3bd696.png)

What should happen: There should be an obvious way to watch the video.

This seems particularly important since this page is linked to from a big red box on [the Ubuntu front page](https://www.ubuntu.com/).

(As an aside, I’m pretty sure that “on-demand webinar” is an oxymoron. If it’s not interactive, it’s just a video.)

**Comment by pmahnke** [comment]
@matthewpaulthomas that should be a form under 'On-demand' but it is rendered with javascript.

Do you have js turned off? What browser are you using?

**Comment by matthewpaulthomas** [comment]
@pmahnke Sorry, I didn’t mention the browser because I had gotten the same results with two browsers: Firefox 55.0.2 on Ubuntu, and Safari 10 on iOS.

On further investigation, with Safari, the form is blocked by the Firefox Focus content blocker — even with all of its individual blocking settings turned off. That is, if someone is using Firefox Focus, they will never see this form unless they choose “Reload Without Content Blockers”.

Less obscurely, with Firefox 55, it is Firefox’s built-in Tracking Protection that is suppressing the form. From the console:
> The resource at “https://app-sjg.marketo.com/js/forms2/js/forms2.min.js” was blocked because tracking protection is enabled.[Learn More] stuckstack_webinar_upgrades_register.html
> The resource at “https://munchkin.marketo.net//munchkin-beta.js” was blocked because tracking protection is enabled.[Learn More] stuckstack_webinar_upgrades_register.html
> The resource at “https://sjrtp3-cdn.marketo.com/rtp-api/v1/rtp.js?aid=ubuntu” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://www.googleadservices.com/pagead/conversion_async.js” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://snap.licdn.com/li.lms-analytics/insight.min.js” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://connect.facebook.net/en_US/fbevents.js” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://munchkin.marketo.net/munchkin.js” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html
> The resource at “https://c1.adform.net/serving/cookie/match?party=1112” was blocked because tracking protection is enabled.[Learn More]  stuckstack_webinar_upgrades_register.html

Tracking Protection is on by default in Firefox Private windows. So if someone visits this page in a Private window, they probably won’t see the form.

**Comment by Caleb-Ellis** [comment]
@anthonydillon What would be the easiest way to get access to the pages.ubuntu.com codebase?
@frankiegranato Just wondering how we'd want to tackle this from a UX perspective - I was thinking a little textbox that says 'Please enable JavaScript/tracking' or something like that

**Comment by anthonydillon** [comment]
I sent you an email to the landing pages admin. I agree your message would give the user enough information to work out what to do.

Maybe something like: "This content is not available to your browser. Please ensure you have JavaScript enabled and any tracking blockers disabled."

**Comment by matthewpaulthomas** [comment]
If the message is specific to this page, we can avoid the euphemism “content”: something like “Sorry, to sign up you’ll need to…”

Separately, “not available to your browser” could be misinterpreted as meaning you cannot use your current browser to access it, and I don’t know of any browser where that’s the case. Clearer would be something like “Sorry, something’s blocking the sign-up form. Try opening this page in a normal window, with any blockers turned off.”
