### ISSUE TITLE
UX the copy doc for /kubernetes/managed page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2226]

**Comment by frankiegranato** [comment]
copydoc: https://docs.google.com/a/canonical.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit?usp=drive_web

**Comment by frankiegranato** [comment]
copydoc: https://docs.google.com/a/canonical.com/document/d/1g38PPPhEP0Z66eM_gezfUyUwAr5e9vGfTHJDWV8gZlE/edit?usp=drive_web
