### ISSUE TITLE
Stock instructions on single node Openstack on LTS not working

### ISSUE THREAD

**Issue by mfv2112** [canonical-websites/www.ubuntu.com#2229]
From a stock 16_04 LTS install after update the instructions at https://www.ubuntu.com/download/cloud/try-openstack just do not work. My last error had conjure-up for novalxd install asking for lxd to be installed via snap which again didn't work. Even using --edge failed although messages from conjure-up suggest progress is being made.

Historically, I have never had the instructions working here either. It's a bad entry to Ubuntu and with lxc/zfs i'm really stoked about the technology but each time I end up having to go back to CentOS/RDO for my Openstack needs (to run Ubuntu!)

---
*Reported from: https://www.ubuntu.com/download/cloud/try-openstack*

**Comment by pmahnke** [comment]
@mfv2112 thanks for filing the issue and sorry you are having problems.

I have asked for some help from the conjure-up author and will let you know what he says.

**Comment by pmahnke** [comment]
@mfv2112 I am added the requirement to have lxd working to the page for now.

in the background we are looking into other things we can do to make this work smoother.

again, thank you for filing the issue and sorry you have had problems.

we have started using tutorials for a lot of our help and hopefully that will get more people feeding back about issues they are having on various setups.

**Comment by mfv2112** [comment]
Thanks this is great to know, as these are great ways to get started and the promise conjure-up/juju brings. In many ways these can also serve as test scripts.
