### ISSUE TITLE
The spacing on a heading is broken on MAAS page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2251]
The spacing on the "Learn about MAAS" (aka the resources) row is broken. See the title of the row. The probable cause is the recent upgrade to Vanilla. fyi @anthonydillon & @deadlight 

---
*Reported from: https://www.ubuntu.com/server/maas*

**Comment by deadlight** [comment]
@anthonydillon were you working on a fix for this?

**Comment by anthonydillon** [comment]
This should be fixed with `v1.6.0`. I will update shortly.

**Comment by anthonydillon** [comment]
This is fixed via https://github.com/canonical-websites/www.ubuntu.com/pull/2299
