### ISSUE TITLE
Fix command 'snap install...'

### ISSUE THREAD

**Issue by souzagaabriel** [canonical-websites/www.ubuntu.com#2261]
In "Installation instructions" - > Install and start conjure-up -> ```snap install conjure-up --classic```

The correct would be:

```sudo snap install conjure-up --classic```

---
*Reported from: https://www.ubuntu.com/download/cloud/try-openstack*

**Comment by deadlight** [comment]
We need to confirm that this is the advice that we want to give.

**Comment by frankiegranato** [comment]
@evilnick can you give us a steer on this please (should we use sudo)? @grahambancroft fyi.

**Comment by evilnick** [comment]
yup, you need to use sudo, as per the instructions - https://docs.ubuntu.com/conjure-up/2.2.0/en/index#installing-conjure-up
