### ISSUE TITLE
Build updates to short form service description

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#2276]
Copydoc: https://docs.google.com/document/d/1psOjmP69PFHs1rhDfP043kXksYieGlny9-0r6yWUPnI/edit

Brief: https://docs.google.com/document/d/1t1CE5yjE7NOKMPnHG6laQjA5IOjNF5O-20zahOSnKDA/edit

**Comment by frankiegranato** [comment]
Short Form Service Agreement: 
English: https://drive.google.com/open?id=0B2_PyaH0PaVmNWdYT1ZycEFrMmc1c3Q4X1otZDl3NzMyTmpN
Japanese translation: https://drive.google.com/open?id=0B2_PyaH0PaVmT290eFhPY2VDOWNLbXhva3NVbkZoWTlOT3NR
Unfortunately these docs are Word docs. Let me know I need to get them reformatted.
