### ISSUE TITLE
Mention of Autopilot to be replaced

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2302]
Remove "Build a cloud with Autopilot" from contextual footer of /cloud/partners. Use default contexual messaging as specified in this doc: https://docs.google.com/document/d/1kq0SPv-PAIfL9nHGxgNDpHhr5OplE2iNaZZiqG4RT48/edit

Remove autopilot mention on this page: https://www.ubuntu.com/download/cloud/try-openstack

---
*Reported from: https://www.ubuntu.com/cloud/partners*

**Comment by grahambancroft** [comment]
Including this: Remove autopilot mention on this page: https://www.ubuntu.com/download/cloud/try-openstack in this card, as per https://docs.google.com/a/canonical.com/document/d/1GQLzMVe8f78EPm9OorJjuyFawxlu3nV-VLRjMcB2AAk/edit?disco=AAAABBGDDBQ
