### ISSUE TITLE
Broken navigation links on USN

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2305]
Hello,

The page at: https://usn.ubuntu.com/usn/usn-3435-1/ (from the security
team updates) contains broken navigation menu links to the rest of the
website, such as: https://usn.ubuntu.com/server

It seems that all the links attempt to connect to the "usn.ubuntu"
subdomain rather than ubuntu.com. Deleting "usn" appears to correct the
links.

Thank you!

**Comment by WillMoggridge** [comment]
With the change to the new USN site, this issue should be resolved
