### ISSUE TITLE
Update datasheet PDFs

### ISSUE THREAD

**Issue by deadlight** [canonical-websites/www.ubuntu.com#2310]
Hi guys,

We need to urgently update the below links as the Foundation datasheet includes storage encryption as an option but is not something we offer, and K8s explorer includes VMware and Openstack as target platforms, but these options are only available as part of Discoverer.

https://insights.ubuntu.com/wp-content/uploads/9ee0/Datasheet_Foundation-cloud-build_02.17.pdf?_ga=2.19508856.1951505184.1508175010-248055331.1495812585

All the foundation cloud datasheet collateral we have at the moment has this incorrect info as well.

https://assets.ubuntu.com/v1/b35eca50-Enterprise-Kubernetes-datasheet.pdf?_ga=2.172154595.115392878.1508099656-249522427.1505216678

Please sync to update the data sheets and website as this has caused some issues in front of customers recently.

**Comment by anthonydillon** [comment]
Thanks for taking this on Karl. Has this been raised to the correct people to generate a new PDF?

**Comment by deadlight** [comment]
Alexia briefed Marcus to get the new PDFs.

We'll update as soon as we have the new docs.

**Comment by deadlight** [comment]
Marcus says that the updated sheets should be complete and signed off by the end of the week (2017-11-03).

**Comment by frankiegranato** [comment]
Lets one of us, remember to update the original requester, Jonathan Brough <jonathan.brough@canonical.com> when this is completed. 

@grahambancroft , I don't know which pages these two pdfs are linked from, but I'm assured that you will be able to find out somehow.

**Comment by frankiegranato** [comment]
@grahambancroft can you check this is done?

**Comment by grahambancroft** [comment]
Work completed with this duplicate issue https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/2498
