### ISSUE TITLE
The spelling of GNOME is inconsistent

### ISSUE THREAD

**Issue by tsimonq2** [canonical-websites/www.ubuntu.com#2322]
## Summary

If someone navigates to https://www.ubuntu.com/desktop/1710 and reads the text, GNOME is spelled like "Gnome" but further down it is spelled like "GNOME." [As per the official GNOME website](https://www.gnome.org/), the spelling is "GNOME." Please correct this.

(I don't feel the other headers are necessary because this is a pretty simple problem and using those would be redundant...)

**Comment by anthonydillon** [comment]
Thank you very much @tsimonq2 we will update the typo shortly.

**Comment by nottrobin** [comment]
I grepped the codebase and only found this inconsistency on the 17.10 page, thankfully. I'm fixing it now.
