### ISSUE TITLE
Contact Us in the footer is the only button

### ISSUE THREAD

**Issue by tsimonq2** [canonical-websites/www.ubuntu.com#2323]
## Summary

The Contact Us button in the ubuntu.com footer is the only button.

## Process

 1. Go to [Ubuntu.com](https://www.ubuntu.com/) and scroll to the footer.

## Current and expected result

It is a bit inconsistent that this is the only link that looks like a button, it should probably be consistent with "About Us," "Careers," and "Press centre," whatever happens to be done.

## Screenshot

![](https://i.imgur.com/FS5zGXV.png)

**Comment by anthonydillon** [comment]
@tsimonq2 thank you very much for taking the time to point out this design pattern. 

The decision to make this link a button was taken with care. We wanted to highlight the Contract us as the main call to action in this area. We appreciate that consistency is compromised for this. But was deemed acceptable for the benefit to the user experience.
