### ISSUE TITLE
“Desktop” Ubuntu 17.10 intro has grammar errors

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2324]
*Reported from: https://www.ubuntu.com/desktop/1710*

“In April 2018, the next Long-term release of Ubuntu, will come with the Gnome shell as default. Ubuntu 17.10 will be the first release to include the new shell and is a great way to preview the future of Ubuntu.”

What’s wrong with this:
- “the next Long-term release of Ubuntu” is bracketed with commas as if it is a secondary phrase, but it isn’t.
- The term is “long-term support version” or “long-term support release”, not “Long-term release”.
- Ubuntu 17.10 has been released, so “will be” should be “is”.
- Gnome Shell is a proper noun.

**Comment by anthonydillon** [comment]
Thanks @matthewpaulthomas will get this done shortly.
