### ISSUE TITLE
Wrongly implies that swap file is a feature or change in 17.10

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2327]
On [the 17.10 page](https://www.ubuntu.com/desktop/1710), the “Features and changes” section has a tile that begins “The swap is now a file, not a partition…”

Irrespective of my tweak in #2325, this suggests that the change from a swap partition to a swap file is new in Ubuntu 17.10. It is not; the change was made in 17.04.

The configuration of swap is not interesting enough to to be a “Feature” of 17.10, and it’s not a “change” in 17.10 either. So probably this tile should be replaced altogether.

**Comment by pmahnke** [comment]
@matthewpaulthomas since the purpose of this page is to get people using this page as a test between LTSes, we put it in as a significant change.  I agree it isn't entirely true as it was added in 17.04, but we wanted to mention it.  Any thoughts on how to do that in the space allowed?

**Comment by matthewpaulthomas** [comment]
@pmahnke That makes me realize there’s a problem with the previous item too: as far as I can tell, it is not the case that “Upgrading to Ubuntu 17.10 should be seamless from Ubuntu 16.04 LTS”.

[The Ubuntu 17.10 release notes](https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes), linked from this same page, don’t even mention the possibility of upgrading from 16.04 LTS; they provide upgrade instructions only from 17.04. And [OMG Ubuntu reports](http://www.omgubuntu.co.uk/2017/10/upgrade-to-ubuntu-17-10) that if you set 16.04 LTS to upgrade to “any new version”, it will offer to upgrade to 17.04. Only after that is done will you be offered the opportunity to upgrade to 17.10. If that’s not a “seam” I don’t know what is.

If that is correct, anyone who will be “using this [release] as a test between LTSes” was already using 17.04, and so they already had a swap file.

**Comment by anthonydillon** [comment]
As this issue will go away in April. Maybe we should leave it for now instead of spending time finding something to replace it.

**Comment by pmahnke** [comment]
closing as this page will be removed tomorrow.
