### ISSUE TITLE
Asset on the ESM page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2334]
Add new asset on the ESM page. See copydoc: https://docs.google.com/document/d/1BK-XXECYJJllG8jIe3WN3X8EMo_3wBBa03nlzYDP8xE/edit#heading=h.3epo9nsrrdcy

**Comment by nottrobin** [comment]
@frankiegranato ^^ really? boo!

**Comment by frankiegranato** [comment]
I need to add this to the copydoc before this task can progress.
Asset: https://pages.ubuntu.com/rs/066-EOV-335/images/ITstrategen_casestudy.pdf
Landing page for new asset: https://pages.ubuntu.com/Cloud_CS_ITstrategen.html
