### ISSUE TITLE
[MAAS] The steps of installation for MAAS and the screen shots are out of date

### ISSUE THREAD

**Issue by MariaVrachni** [canonical-websites/www.ubuntu.com#2335]
Here is the copydoc link for maas.io. You can find the updated steps and screenshots here 
https://docs.google.com/a/canonical.com/document/d/1uVdX719h32QuWT0Dwe_hZTFuCvi4b3XQOcOoQtINH88/edit?usp=sharing

Lets figure out a way to keep in sync when updates are made on maas.io so that they are also reviewed for ubuntu.com.

**Comment by evilnick** [comment]
It may make sense to either track the install page from the docs or perhaps if we make changes there we should also check the web page. @degville, any suggestions?

**Comment by anthonydillon** [comment]
Issue moved to [canonical-websites/maas.io #210](https://github.com/canonical-websites/maas.io/issues/210) via [**ZenHub**](https://www.zenhub.com/)

**Comment by anthonydillon** [comment]
This is in fact an ubuntu.com issue.
