### ISSUE TITLE
[MAAS] broken link - 'Learn more about interfaces'

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/www.ubuntu.com#2336]
On the [MAAS tour](https://maas.io/tour) page the link for 'Learn more about interfaces' is broken. Maybe you want to send it here:?

https://docs.ubuntu.com/maas/2.2/en/nodes-commission#post-commission-configuration

**Comment by anthonydillon** [comment]
Issue moved to [canonical-websites/maas.io #203](https://github.com/canonical-websites/maas.io/issues/203) via [**ZenHub**](https://www.zenhub.com/)
