### ISSUE TITLE
IF USER STAYS IN ATTACHED PAGE, DOWNLOADS WONT STOP

### ISSUE THREAD

**Issue by pokes2017** [canonical-websites/www.ubuntu.com#2339]
Access
https://www.ubuntu.com/download/desktop/thank-you?country=BR&version=16.04.3&architecture=amd64

wait

see how the page keeps starting new downloads.

browser = opera 
OS = windows 7

---
*Reported from: https://www.ubuntu.com/download/desktop/thank-you?country=BR

**Comment by anthonydillon** [comment]
@pokes2017 Thanks for taking the time to report this issue. I am not able to replicate it. I have tested the download on Windows 7, Opera 48. The download started once and when cancelled it didn't start again. Could you retest and if you still have the issue could you provide the browser version.

**Comment by anthonydillon** [comment]
Closing as there has been no response for sometime.
