### ISSUE TITLE
Maas Pricing Table Update

### ISSUE THREAD

**Issue by michaelb17** [canonical-websites/www.ubuntu.com#2343]
Located at the bottom of the Maas page is an outdated pricing table.

This should be an include from support/plans-and-pricing.

Table styling needs updating.

-------------------------------------------------

<img width="650" alt="screen shot 2017-10-23 at 14 15 40" src="https://user-images.githubusercontent.com/32878117/31890973-e08c9df2-b7fc-11e7-8921-f2b9c8d0c097.png">

---
*Reported from: https://www.ubuntu.com/server/maas*

**Comment by pmahnke** [comment]
@michaelb17 the table is the same, the background should be 'p-strip--light' to give it the grey... also on /server/plans-and-pricing
