### ISSUE TITLE
Images not obeying boundaries of cards!

### ISSUE THREAD

**Issue by michaelb17** [canonical-websites/www.ubuntu.com#2346]
The product screenshots within the cards are not obeying padding or boundaries of the cards they sit within.

<img width="844" alt="screen shot 2017-10-24 at 09 56 28" src="https://user-images.githubusercontent.com/32878117/31933679-b0489970-b8a1-11e7-894e-a41640589011.png">

---
*Reported from: https://www.ubuntu.com/cloud/juju*

**Comment by anthonydillon** [comment]
@michaelb17 Looks ok for me in Chrome. Which browser are you using?

**Comment by pmahnke** [comment]
no one else can replicate, closing
