### ISSUE TITLE
Alignment Problem

### ISSUE THREAD

**Issue by bymiy** [canonical-websites/www.ubuntu.com#2354]
Hello there,

`<td class = "u-align - center">`

I think this code is missing a place to be.

The pace did not look good.

Would you check?

Thank you.

Here: `<td class="p-table__cell--highlight"><small>Small: $95,000<br />Medium: $225,000<br />Large: $420,000</small></td>`

Mehmet IŞIK
mehmet@sartek.com.tr
www.sartek.com.tr

---
*Reported from: https://www.ubuntu.com/support/plans-and-pricing*

**Comment by anthonydillon** [comment]
Thank you very much @bymiy. You are right. We will get this fixed shortly.

**Comment by bymiy** [comment]
You're welcome. everything for ubuntu :)
