### ISSUE TITLE
Ubuntu gnome 17.10 - Laptop's touchpad is getting freezed once we unlock/logedin to window

### ISSUE THREAD

**Issue by praveenashok** [canonical-websites/www.ubuntu.com#2355]
Ubuntu 17.10
Dell vostro 3000 laptop
Once we lock the window, come back and unlock the window and touch pad mouse cursor is getting freezed untill we restart the laptop.

Note: If i opened in wrong place, pls give me the link where i can report this.

---
*Reported from: https://www.ubuntu.com/desktop/1710*

**Comment by pmahnke** [comment]
@praveenashok this repo is for issues on the website www.ubuntu.com

issues with ubuntu itself should be reported on launchpad.net/ubuntu

here is a guide: https://help.ubuntu.com/community/ReportingBugs
