### ISSUE TITLE
404 on Intel NUC link

### ISSUE THREAD

**Issue by pureagave** [canonical-websites/www.ubuntu.com#2356]
Click on the Intel logo for the NUC and the page gives a 404

---
*Reported from: https://www.ubuntu.com/internet-of-things/digital-signage*

**Comment by pmahnke** [comment]
@pireagave, thanks!

@campbeil or @davidcalle - linking to https://www.intel.co.uk/content/www/uk/en/products/boards-kits/nuc.html
