### ISSUE TITLE
pages.ubuntu.com nav doesn't work 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2373]
Drop down menus are inaccessible from article pages.  

---
*Reported from: https://pages.ubuntu.com/Cloud_CS_ITstrategen.html*

**Comment by frankiegranato** [comment]
@anthonydillon is this a fixable bug for this iteration?

**Comment by grahambancroft** [comment]
@frankiegranato I've fixed this in Marketo, please head along to https://pages.ubuntu.com/Cloud_CS_ITstrategen.html to confirm

**Comment by grahambancroft** [comment]
Also, @Caleb-Ellis had a look and confirmed the nav works ok

**Comment by grahambancroft** [comment]
@frankiegranato has seen and confirms the fix, yayer :)
