### ISSUE TITLE
Best buy logo is not displaying correctly 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2374]
Please replace the current version with a version of the Best Buy logo on a transparent background. 

---
*Reported from: https://www.ubuntu.com/support*

**Comment by pmahnke** [comment]
I think the background should be p-strip--light ... rather than change the logo, we don't control all the logos

**Comment by pmahnke** [comment]
@frankiegranato turns out the suru background was on the whole page and the p-strip has just a transparent background... so I had to remove it from the entire page.
