### ISSUE TITLE
Contribute Slider Bug

### ISSUE THREAD

**Issue by andypagdin** [canonical-websites/www.ubuntu.com#2375]
The same price matched item does not match the contributed amount when the contributed amount is less than the current item and more than the previous items price.

Simple change within the chooseEquivalentItem function
` (item['price'] > totalAmount && items[itemIndex - 1]['price'] < totalAmount)`
to
` (item['price'] > totalAmount && items[itemIndex + 1]['price'] > totalAmount)`
---
*Reported from: https://www.ubuntu.com/download/desktop/contribute*

**Comment by pmahnke** [comment]
@nottrobin can you confirm?

**Comment by grahambancroft** [comment]
Hi andypagdin, I'm unable to replicate this and the suggested code causes complete failure of the feature.
