### ISSUE TITLE
UES takeover build

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2381]

**Comment by michaelb17** [comment]
UES Takeover Nov 17 - Initial Draft

![UES Takeover - Nov 17 - Concept 3 - Large Screen .jpg](https://images.zenhubusercontent.com/59e712dca468affe6df71a10/79a98d04-cb8c-4eef-9f41-d87ad535df76)

**Comment by michaelb17** [comment]
Things still being considered:

- Suru Background?
- Illustration

**Comment by michaelb17** [comment]
Preposed draft for submission.

Waiting on Thibauts's approval but will go with this version for now.

All assets uploaded to manager.assets.ubuntu.com

![UES Takeover - Nov 17 - Concept 3 - Large Screen .png](https://images.zenhubusercontent.com/59e712dca468affe6df71a10/639492ff-9604-47dc-b0e5-23e73838cba7)

![UES Takeover - Nov 17 - Concept 3 - Mobile Screen .png](https://images.zenhubusercontent.com/59e712dca468affe6df71a10/ecb8f93f-2ff5-437d-825b-8a9bffb30024)
