### ISSUE TITLE
Changing links on multiple pages

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2388]
Brief: https://docs.google.com/document/d/1GQLzMVe8f78EPm9OorJjuyFawxlu3nV-VLRjMcB2AAk/edit#

**Comment by frankiegranato** [comment]
they should be part of:
Kubernetes: 
Kubernetes for enterprise 1,2,3 go (about Explorer packages): https://insights.ubuntu.com/2017/09/07/kubernetes-for-the-enterprise-1-2-3-go/
Updated product sheet from design
Openstack:
Stuckstack webinar
Stuckstack whitepaper (create form)
Citynetwork case study (maybe add a signup form + change the page title so it appears correctly on SEO)
Openstack made easy 
Replace with newly updated piece from design
ESM + Support + buy.ubuntu.com + Livepatch
Add ITstrategen 
Make space for upcoming pieces:
Acquia (Livepatch)
Security webinar by Dustin
Commercetools whitepaper
Ensure we have dashboard to monitor page performance after changes and have learned experiences from other pages when it comes to placement and look and feel

**Comment by grahambancroft** [comment]
Only actionable item from the list in the brief is as follows:

## Openstack made easy 

Replace with newly updated piece (https://assets.ubuntu.com/v1/4315c393-OpenStack-made-easy_eBook_11.17.pdf) on the following pages:
  
- https://www.ubuntu.com/download/cloud/build-openstack
- https://www.ubuntu.com/download/cloud/try-openstack)
