### ISSUE TITLE
Display LTS dates

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2401]
Please add the support window dates to the relevant download pages on your website.  At https://www.ubuntu.com/download/desktop it is noted that 16.04 is an LTS release and has a 5-year support window, but does not say when that window starts or ends!  Furthermore, there is a link to the release notes.  Surely that info will be there... nope.  Maybe the change summary... nope.  Is there anywhere on your website that immediately shows the support dates?  Not that I could easily find.  

I had to google it to get to find a wiki page with the info.  It is still incomplete, however.  There are no end support dates for some releases at https://wiki.ubuntu.com/Releases.  All relevant info for the release should be on the download page.

Please, understand your audience.  We want simple, clear, obvious relevant info.  These pages are as much info for technical users as is marketing, or rather, it should be.

**Comment by pmahnke** [comment]
I think this would be easy to add with some text and perhaps a link to /info/release-end-of-life

**Comment by pmahnke** [comment]
* desktop - [updated copy doc](https://docs.google.com/document/d/1ScuTtdrm3-iAvizTDxksVTAerV6QkCUN8Sg60uUlJsk/edit)

**Comment by frankiegranato** [comment]
Update variable and wiki.

**Comment by grahambancroft** [comment]
I've added the LTS full EOL as part of the variable, I've also updated /download /desktop as per the copy doc. 

I've pinged Adam Conrad (emailed Adam also) and Chris Johnson to see if they can furnish me with point release EOL dates to update the wiki and add to the point release LTS on ubuntu.com.

**Comment by grahambancroft** [comment]
Re point releases, Adam replied saying "They all have the same EOL dates as the original release, because we're doing rolling HWE stacks now."

**Comment by grahambancroft** [comment]
The wiki has been updated, I'm guessing by Adam https://wiki.ubuntu.com/Releases

**Comment by frankiegranato** [comment]
@grahambancroft & @anthonydillon Peter has requested that we remove this variable. There should be no dates in headings or in links. He think the note in the body copy will suffice. Can we re open this issue or should I make a new one? Lets have a chat.
