### ISSUE TITLE
Add ITstrategen case study to buy.u.com homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2419]
Swap the tutorial (third resource in the row) on the existing homepage
![Screen Shot 2017-11-14 at 14.03.01.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/a365248e-251c-4246-beda-4f18c3a93db0)

With:
Learn how ITstrategen keeps their applications secure with Ubuntu [link to: https://pages.ubuntu.com/Cloud_CS_ITstrategen.html]
The security of customer data is of the utmost importance to ITstrategen, which is why Ubuntu is their server operating system of choice. 

![image.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/39b3a6e4-9f6b-4708-bc0a-6f04ecd78919)

**Comment by grahambancroft** [comment]
@frankiegranato Done and live
