### ISSUE TITLE
Replace resources row on /kubernetes

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2421]
Replace content in the resources row on this page: https://www.ubuntu.com/kubernetes/
With the following; 

order: 1
type: WEBINAR
text: How to get started with your Kubernetes strategy 
link: https://insights.ubuntu.com/2017/06/09/webinar-how-to-get-started-with-your-kubernetes-strategy/?_ga=2.160429757.1298694829.1510572191-765379582.1510062947 

order: 2 
type: WEBINAR
text: Kubernetes for the Enterprise: 1, 2, 3, Go! 
link: https://insights.ubuntu.com/2017/09/07/kubernetes-for-the-enterprise-1-2-3-go/

order: 3
type: WHITEPAPER
text: The no-nonsense way to accelerate your business with containers 
link: https://insights.ubuntu.com/2017/02/27/the-no-nonsense-way-to-accelerate-your-business-with-containers/?_ga=2.164082367.1298694829.1510572191-765379582.1510062947

**Comment by grahambancroft** [comment]
@frankiegranato @anthonydillon noticed that the copy doc (https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit) hadn't been updated to reflect theses changes so I've updated it.
