### ISSUE TITLE
duplicated text

### ISSUE THREAD

**Issue by setharnold** [canonical-websites/www.ubuntu.com#2423]
Hello, the text "Canonical has two Kubernetes offerings: Kubernetes Explorer and Kubernetes Discoverer, but every Kubernetes we build is future-proof with automated upgrades to newer versions on demand" appears duplicated on the page https://www.ubuntu.com/kubernetes

Thanks
---
*Reported from: https://www.ubuntu.com/kubernetes*

**Comment by pmahnke** [comment]
@setharnold thanks for pointing this out, a PR is in place, should get fixed soon
