### ISSUE TITLE
some desktop/government references out of date

### ISSUE THREAD

**Issue by evilnick** [canonical-websites/www.ubuntu.com#2443]
Munich recently decided to ditch Linux, so probably not worth a callout.

CESG doesn't actually exist anymore, the report is nearly four years old, so not 'recent' as mentioned in text 
---
*Reported from: https://www.ubuntu.com/desktop/government*

**Comment by grahambancroft** [comment]
@evilnick thanks for this, would you recommend that these be removed or reworded?

**Comment by evilnick** [comment]
I think the Munich one can be pretty easily swapped for something else. 
Possibly the CESG bit can be swapped for something about FIPS.

Shall I edit the copydoc?

**Comment by grahambancroft** [comment]
That would be wonderful if you could, thank you, sir.

**Comment by pmahnke** [comment]
@evilnick combined that page with some others to a new one https://www.ubuntu.com/desktop/organisations... so closing this issue
