### ISSUE TITLE
community.ubuntu.com is not a support venue

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#2450]
community.ubuntu.com is not a support venue (as suggested by this webpage by the 'Get free community support link'), please consider linking to https://community.ubuntu.com/t/finding-help/712 or https://community.ubuntu.com/t/community-support/709

---
*Reported from: https://www.ubuntu.com/support/community-support?_ga=2.18407545.1309351023.1511123512-629454919.1504091901*

**Comment by pmahnke** [comment]
@Ads20000 I have updated ubuntu.com, still feels a bit too little, but I hope this helps
