### ISSUE TITLE
Implement small text changes on /kubernetes page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2453]
Nicholas Dimotakis requested changes in copydoc: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#

**Comment by frankiegranato** [comment]
Nicholas Dimotakis requested these changes via email to me on 21 Nov. All changes marked for Dev in copydoc: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit#

**Comment by grahambancroft** [comment]
These changes have been completed as part of this issue https://github.com/canonical-websites/www.ubuntu.com/issues/2438 https://github.com/canonical-websites/www.ubuntu.com/pull/2448
