### ISSUE TITLE
Change phone numbers on https://landscape.canonical.com

### ISSUE THREAD

**Issue by grahambancroft** [canonical-websites/www.ubuntu.com#2457]
## Summary

Change phone numbers on https://landscape.canonical.com as per brief https://docs.google.com/document/d/14CQg3WMMe2oHh4QirQI0Lm-mruY-OCMhZpjqsL8Njdo/edit

**Comment by anthonydillon** [comment]
David Coronel recently landed this branch to replace the phone numbers with a link to Ubuntus contact us page.

https://bazaar.launchpad.net/%7Elandscape/landscape/trunk/revision/11259

**Comment by grahambancroft** [comment]
MP: https://code.launchpad.net/~gbancroft-canonical/landscape/add-phone-numbers/+merge/334440
