### ISSUE TITLE
Cloud - Overview Table of Contents Spacial Errors

### ISSUE THREAD

**Issue by michaelb17** [canonical-websites/www.ubuntu.com#2458]
Styling of the table of contents looks off. There should be a greater spacing between elements and a stronger contrast between the heading and body copy.

Screenshot:
<img width="948" alt="screen shot 2017-11-23 at 17 07 26" src="https://user-images.githubusercontent.com/32878117/33183737-fddcf668-d070-11e7-8b5e-bb95c3b72f09.png">

---
*Reported from: https://www.ubuntu.com/cloud*

**Comment by pmahnke** [comment]
this is using Vanilla correctly, closing...
