### ISSUE TITLE
Replace /kubernetes datasheet

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2466]
Please replace the current datasheet on the /kubernetes page with this new version: https://drive.google.com/open?id=0B2_PyaH0PaVmaVVoWDYwT3hsZUU2eHBPMFdtcG81LUVNaW80
See comment @dev in the /kubernetes copydoc: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit

**Comment by grahambancroft** [comment]
Asset - https://assets.ubuntu.com/v1/894857eb-DS_Enterprise-Kubernetes_screen-AW_11.17.pdf
