### ISSUE TITLE
Amendments re the use of the Kubernetes Trademark

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2469]
Please see amends in the following pages (links to copydocs included): 

/kubernetes: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit

/kubernetes/managed: https://docs.google.com/document/d/1viNQgt99D2_b873Yd98iNT5vEzIbPQFgNI5XBFnszHk/edit#heading=h.887mlur04i40

/cloud - overview: https://docs.google.com/document/d/1mQjVXDcoP8ChOzRdmuI55BdXhbURD53qBNc2bgJhfhg/edit#

**Comment by frankiegranato** [comment]
Logo: [Uploading... certified-kubernetes-brand-logo.svg ]

**Comment by frankiegranato** [comment]
Here is the svg to replace the header asset on the kubernetes/managed page.![K8s-cloud-key.svg](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/55728c7d-fed5-4bfb-a703-10d13f4dd675)

**Comment by grahambancroft** [comment]
@frankiegranato was there meant to be another logo? (Logo: [Uploading... certified-kubernetes-brand-logo.svg ])
