### ISSUE TITLE
Too much spam to the email addresses on this page!

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2507]
Chris Johnston says he receives too much spam to the two email addresses at the foot of this page (namely support-manager@canonical.com and operations-director@canonical.com). What can be done to remedy this (without deactivating the inbox)? An contact form instead? Any other ideas? 

---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage/service-description*

**Comment by anthonydillon** [comment]
Maybe just remove the links and replace the `@` with `(at)`. This can stop bots picking up the email address.
