### ISSUE TITLE
UnsubscribePage is not reacheable

### ISSUE THREAD

**Issue by jeromelavigne** [canonical-websites/www.ubuntu.com#2509]
Hello,
By clicking on Unsubscribe link in Ubuntu emails, you are redirected to https://pages.ubuntu.com/UnsubscribePage.... and the page is indicated as unreacheable: ERR_CONNECTION_RESET

---
*Reported from: https://pages.ubuntu.com/UnsubscribePage*

**Comment by anthonydillon** [comment]
@jeromelavigne thank you very much for taking the time to report this issue. I cannot replicate this issue. The page loads for me. Could you please check again and if it is still not working. Let me know which browser you are using.

**Comment by anthonydillon** [comment]
Please use the "Unsubscribe from all" form field.
