### ISSUE TITLE
Typos in security page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2530]
> Protected VMs
> LXD containers, libvirt VMs and OpenStack VMs are protected by AppArmor by default. A rich set of profiles is provided so users can opt-in to protection for other applications.

“Profiles” being plural you should use are instead of is there right?

> FIPS
> Ubuntu is certified to US government standards by FIPS (Federal Information Processing Standard) to ensure compliance and tougher security that mandates.

Shouldn’t that say "than mandates”?

**Comment by pmahnke** [comment]
@anthonydillon great catches

the second one shouldn't even have 'that mandates'
