### ISSUE TITLE
“Ubuntu for telcos” page doesn’t show up in search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2538]
1\. On any page on www.ubuntu.com, use the header search to search for “telcos” or “telecommunications”.

What should happen: “[Ubuntu for telcos](https://www.ubuntu.com/telecommunications)” is the first result.

What actually happens: The page does not show up in the results at all.

---
*Reported from: https://www.ubuntu.com/telecommunications*

**Comment by anthonydillon** [comment]
Looks like we need Google to index the new pages.

**Comment by matthewpaulthomas** [comment]
Maybe add that to the process checklist for adding (or moving) a page.

**Comment by pmahnke** [comment]
filed an [RT](https://portal.admin.canonical.com/108245)

**Comment by matthewpaulthomas** [comment]
This is fixed now. Will be interesting to see if the problem recurs with a future new page.
