### ISSUE TITLE
[design] Pages should have justified texts

### ISSUE THREAD

**Issue by gsilvapt** [canonical-websites/www.ubuntu.com#2539]
## Summary

Hello all.

As far as design is concerned, my knowledge and understanding is pretty limited. However, seeing non-justified texts feels inadequate in these days. This is more of a proposal/discussion issue than an actual bug.
In some paragraphs you can clearly notice texts are not justified and I think it would look cleaner and more professional if we style texts differently. I'll hereon take the Code of Conduct page as this seems the best example.

Nevertheless, I was told this was a general styling option and thus I should ask/propose here because it should/could reflect on the website general layout.

## Process

Visiting https://www.ubuntu.com/about/about-ubuntu/conduct we can see the texts are out of place or not aligned. 

## Current and expected result

Texts are aligned to the left and should be justified.

**Comment by frankiegranato** [comment]
Thanks for giving this your consideration gsilvapt. However we have a set of agreed upon design guidelines for use of typography which do not usually include justified text. See https://vanillaframework.io/ for more information on our  design guidelines. Thanks again.
