### ISSUE TITLE
404 on developer TOS Publishing Policy

### ISSUE THREAD

**Issue by maxiberta** [canonical-websites/www.ubuntu.com#2544]
## Summary

The Publishing Policy link in section 1.e of the [developer terms and conditions](https://www.ubuntu.com/legal/terms-and-policies/developer-terms-and-conditions) is broken.

## Current and expected result

Section 1.e links to `developer.ubuntu.com/en/publish`, but this URL returns a 404 error page. It should link to the actual Publishing Policy (I don't really know the exact url). And, it should be an actual link instead of plain text, btw.

**Comment by pmahnke** [comment]
@maxiberta thanks for pointing this out.  I have contacted our legal team to see what they want to do.
