### ISSUE TITLE
Word changes under Build Your Own Production Cloud

### ISSUE THREAD

**Issue by lamesdonner** [canonical-websites/www.ubuntu.com#2554]
Hello,

Some of the information under Build Your Own Production Cloud needs updated as per a conversation with Stefan Fabel.

    - Replace "Production" by "Private"

    - Change "Requirements" to "Minimum Requirements"

    - Note in fine print "For production clouds 12 nodes are required,
      including 3 nodes for High Availability MAAS-based infrastructure"

---
*Reported from: https://www.ubuntu.com/download/cloud/build-openstack*

**Comment by pmahnke** [comment]
@lamesdonner hi... I added 'private' to the h1 rather than replace as the page before this says 'Build your own production cloud'
