### ISSUE TITLE
Small text changes to /telco page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2563]
Small text changes suggested by me to improve the flow of the page - amend as specified in copydoc: https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit#heading=h.ujlkf6v8a22y

---
*Reported from: https://www.ubuntu.com/telecommunications*

**Comment by frankiegranato** [comment]
I believe this is done as part of many larger improvements done by @pmahnke 
I'm going to close the issue

**Comment by anthonydillon** [comment]
This is still in progress.
