### ISSUE TITLE
Design for improving resources page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2565]
Reduce above the fold header
Improve typographic representation of each post
Consider use of colour in posts
Add an intro blurb (what is this site?)
Remove search bar (for now)
Consider removing the 'breadcrumb' navigation

**Comment by frankiegranato** [comment]
Re the blurb, please can we try this:


Heading: Ubuntu resources
Subhead: Selected resources from insights.ubuntu.com


@spencerbygraves  can you try using this blurb in your design please? (It might not look right though so I do have other options to try!)

**Comment by spencerbygraves** [comment]
@frankiegranato @anthonydillon I have a question about the display of the content type on the cards. When you click through to an article, the content type is displayed along with tags. Should each card show the tags too, or just the content type?

![image](https://user-images.githubusercontent.com/9105999/34770839-4b644cfc-f5fa-11e7-82a2-e2ee78dda64d.png)

**Comment by spencerbygraves** [comment]
@frankiegranato @anthonydillon Here is the design including the changes we discussed yesterday. 

![image](https://user-images.githubusercontent.com/9105999/34779021-ef6461b8-f616-11e7-803c-1debdf401ed0.png)

**Comment by anthonydillon** [comment]
Lovely thank you @spencerbygraves. You are not showing tags just category so it should just be one thing.

**Comment by frankiegranato** [comment]
Yes - show just the categories :-)

**Comment by spencerbygraves** [comment]
@frankiegranato @Caleb-Ellis I have updated the design a little to make the topic titles more legible by removing the coloured background.

![image](https://user-images.githubusercontent.com/9105999/34950541-5dc6aaa6-fa0b-11e7-81cf-c2177967a580.png)

**Comment by Caleb-Ellis** [comment]
New issue #2580
