### ISSUE TITLE
“To find out more about snaps” incomplete phrase

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2569]
On [the “Ubuntu Desktop for developers” page](https://www.ubuntu.com/desktop/developers), the “Snaps are the new apps” section ends with a standalone link:

> [To find out more about snaps](http://snapcraft.io/?_ga=2.122970889.322940702.1515397985-1860446039.1493901412)

To find out more about snaps, what? A simple fix is to change “To find” → “Find”.

---
*Reported from: https://www.ubuntu.com/desktop/developers*

**Comment by pmahnke** [comment]
I think that IS has updated the GSA and the results data has changed.  @WillMoggridge do you know how the GSA code works?
