### ISSUE TITLE
Search always says “We’ve found 0 results” even when there are results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2570]
1\. In the top-level search field on any www.ubuntu.com page, search for anything that should return results, such as “[developer](https://www.ubuntu.com/search?q=developer)”.

What you see:
- ‘We've found 0 results for "developer"’
- ‘Results to of 0’
- search results.

What you should see:
- ‘10 results for “developer”’
- ‘Showing all 10 results’
- search results.

---
*Reported from: https://www.ubuntu.com/search?q=developer*

**Comment by pmahnke** [comment]
Thanks @matthewpaulthomas, IS updated the GSA firmware and now the results info isn't returning correctly.  I think that @WillMoggridge has made a fix, but we still can't publish the site.

**Comment by caldav** [comment]
Any progress on this issue?
