### ISSUE TITLE
Design for takeover

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2577]

**Comment by frankiegranato** [comment]
Next month, Thibaut is running a campaign called Ubuntu Product Month to encourage users to learn about our products. 

We have the copy for the takeover ready in the brief: https://docs.google.com/document/d/1GQAsZVnrFqXI7SlxAuNXIoQXgeSWd4MSbrSYO2djbPU/edit 

... and I've had an idea for a visual which I've sketched (see two attachments below). No need to go with my idea, but I thought I'd throw it in the mix :-) 

![IMG_8989.JPG](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/7fdb0dce-955a-4eec-ab98-a67d3a41ec30)
![Screen Shot 2018-01-18 at 10.27.47.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/e8d871e5-3b9b-468f-92b5-291e57652128)

I know you are busy and I don't want to add too much pressure (especially when you're doing us a favour), but @Caleb-Ellis is available to start building this asap and Thibaut is itching to see it live, so the sooner you can get round to this, the better. Thank you so much. 

Fyi @kasiag

**Comment by spencerbygraves** [comment]
@frankiegranato Here is the design

**Large screen**

![image](https://user-images.githubusercontent.com/9105999/35149083-b911e2dc-fd0c-11e7-8369-25f88135f9b8.png)

**Small screen**

![image](https://user-images.githubusercontent.com/9105999/35149097-c55dc3a8-fd0c-11e7-8025-f52dbe7e0817.png)

**Comment by frankiegranato** [comment]
Looks great to me @spencerbygraves. @Caleb-Ellis do your stuff!

**Comment by spencerbygraves** [comment]
**Landing page header**

![image](https://user-images.githubusercontent.com/9105999/35150647-14a4f5de-fd13-11e7-8a32-b9c61e606c95.png)

**Comment by frankiegranato** [comment]
The landing page header looks great too. What an improvement! I think I'll make a separate issue to describe the landing page work and assign @anthonydillon (I'll save your visual there too)
