### ISSUE TITLE
formulate plan for navigation

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2579]

**Comment by frankiegranato** [comment]
---------- Forwarded message ----------
From: Dustin Kirkland <kirkland@canonical.com>
Date: Tue, Jan 16, 2018 at 5:33 AM
Subject: thin Canonical ribbon
To: Peter Mahnke <peter.mahnke@canonical.com>, Kasia Galandziej <kasia.galandziej@canonical.com>, Carla Berkers <carla.berkers@canonical.com>
Cc: Mark Shuttleworth <mark@ubuntu.com>


In a review with Mark this morning, we were looking at this page for a
product (Packer) from a similar open source company (Hashicorp):

https://www.packer.io/intro/getting-started/build-image.html

Mark liked the thin black/white ribbon across the top of this page,
with the Hashicorp logo.  Note that the url is packer.io.

Mark asked that I take this to you for your consideration for our
ubuntu.com, maas.io, jujucharms.com, cloud-init.org, etc. web
properties.

Can you think this through, perhaps mock this up?

Thanks!

Dustin Kirkland
