### ISSUE TITLE
In the alternate downloads page there's no link to minimal iso

### ISSUE THREAD

**Issue by mymike00** [canonical-websites/www.ubuntu.com#2583]
In the Alternative download page I expect to see a section regarding minimal iso, that can be found [here](https://help.ubuntu.com/community/Installation/MinimalCD).

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by pmahnke** [comment]
@mymike00 they are actually the 'Network installer' images... I will try and work the wording 'minimal iso' into the text.

**Comment by mymike00** [comment]
Oh, I thought they were different things... Thanks

**Comment by pmahnke** [comment]
@mymike00 they are the same... it installed a really basic ubuntu and asks you about loads of options and languages, etc...

**Comment by cbrownstein** [comment]
Resolved in #2608
