### ISSUE TITLE
Solo reboot

### ISSUE THREAD

**Issue by robertomollo** [canonical-websites/www.ubuntu.com#2588]
Saludos.
Espero puedan comprender mi reporte.
Estoy muy contento con el producto ubuntu 16.04, pero hoy tengo un problema que no se esta solucionando actualizando el sistema.
- Cuando quiero apagar el sistema este simplemente se reinicia, sin importar si lo hago con la linea de comando. No apaga el sistema, lo único que hace es reiniciar.
- El equipo funciona sin problema el único detalle es el querer realizar el apagado, no apaga solo reinicia. Tengo instalado Windows 10 en otra partición y no me da este mismo problema.

MI EQUIPO
descripciÃ³n: | Equipo de escritorio
-- | --
producto: | 10A6A0KV00 (LENOVO_MT_10A6)
fabricante: | LENOVO
versiÃ³n: | ThinkCentre M93p

Espero puedan solucionar el problema, porque otro problema no lo he encontrado.
Gracias de antemano.
P.D.: En archivo adjunto les envió los datos técnicos de mi equipo. Se encuentra en formato html, solo es de cambiar la extensión ".txt" por ".html"

[sistema_lenovo.txt](https://github.com/canonical-websites/www.ubuntu.com/files/1637191/sistema_lenovo.txt)

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
Hello @robertomollo .

Sorry to hear you are having a problem with 16.04. Unfortunately I cannot provide support via this channel as I am a member of the web team.

If you could report an bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question on askubuntu.com you should receive a quick response.
