### ISSUE TITLE
In the Openstack installation instructions, add a next button between step 5 and 6

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2589]
@MariaVrachni commented on [Wed Jan 17 2018](https://github.com/canonical-websites/design.ubuntu.com/issues/106)

## Summary

Kiko asked to add a Next button between Step 5 and 6 in the Openstack installation page. 
(https://www.ubuntu.com/download/cloud/build-openstack)

## Process

For further requirements contact Kiko (kiko@canonical.com)

## Screenshot

<img width="1328" alt="screen shot 2018-01-17 at 13 09 38" src="https://user-images.githubusercontent.com/18288099/35044507-8984893c-fb88-11e7-9dbf-c005f4c6855f.png">

---

@MariaVrachni commented on [Wed Jan 17 2018](https://github.com/canonical-websites/design.ubuntu.com/issues/106#issuecomment-358301027)

FYI @anthonydillon

**Comment by pmahnke** [comment]
closing as we have asked kiko for details without reply.
