### ISSUE TITLE
500 page isn't rendering correctly?

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#2591]
## Summary

- seems like the 500 error page isn't rendering correctly

## Process

- on your laptop, try breaking logic in a thank you page (eg, remove the condition in an elif)
- load that page

## Current and expected result

- nice 500 page

## Screenshot

![image](https://user-images.githubusercontent.com/441217/35086601-bf7dc794-fc35-11e7-99b2-329a50fa6a4b.png)

**Comment by anthonydillon** [comment]
There was a space between the hash and the number: `Fixes # 2591`
