### ISSUE TITLE
Improvements to "Ubuntu Product Month" landing page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2593]
Landing page to be improved.
Here is the current page: https://pages.ubuntu.com/ubuntu_product_month.html
Here is the copydoc: https://docs.google.com/document/d/1HPf1I7bJQ4He_RuV1vLZw7lEt-KiuQke_zLXKaD6stk/edit

**Comment by frankiegranato** [comment]
Here is Spencer's latest design: ![35150647-14a4f5de-fd13-11e7-8a32-b9c61e606c95.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/211be5da-0842-4668-8071-160ac657ebc5)

@Caleb-Ellis can you please add a link to the takeover page - I hope Ant might be able to borrow code or assets from it.

**Comment by anthonydillon** [comment]
This is done: https://pages.ubuntu.com/ubuntu_product_month.html
