### ISSUE TITLE
Mobile menu has orange background

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2617]
![screenshot_20180129-231550_01](https://user-images.githubusercontent.com/1413534/35539688-8e22a61a-054a-11e8-8366-09192276f81d.jpg)

---
*Reported from: http://www.ubuntu.com/kubernetes

**Comment by cbrownstein** [comment]
Hello. I might try to tackle this if I have time.

Should I assume that the menu background color should be white? If not, what color?

**Comment by anthonydillon** [comment]
@cbrownstein thank you. White would be great. We would like to keep header banner above the menu orange but the background of the menu should be white.
