### ISSUE TITLE
Small screen logos are cropped

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#2618]
On the /containers/LXD page the logos are cropped in chrome on android.

![screenshot_20180129-233100_01](https://user-images.githubusercontent.com/1413534/35540194-b3e07c22-054c-11e8-8ea3-6ecb16c10ee9.jpg)

**Comment by cbrownstein** [comment]
The /kubernetes page is affected as well (Chrome on Android).

![kubernetes_page](https://user-images.githubusercontent.com/25962175/35547108-0e5135fa-052c-11e8-9eff-3e1b6448eb16.png)

**Comment by cbrownstein** [comment]
Just experimenting (this comment may not be helpful), but the problem appears to be fixed if I use Chrome DevTools to disable the `width` property of `.p-inline-images__logo` (styles.css:5779).

Note: I have not tested to see if this fix causes problems elsewhere.
