### ISSUE TITLE
Ubuntu GNOME has been merged with Ubuntu Desktop

### ISSUE THREAD

**Issue by tsimonq2** [canonical-websites/www.ubuntu.com#2631]
## Summary

On [the flavors page](https://www.ubuntu.com/download/ubuntu-flavours), Ubuntu GNOME is still present. The Ubuntu GNOME flavor was merged with Ubuntu Desktop, and the website might need to reflect that.

CCing @jbicha in case he'd like to comment.

**Comment by cbrownstein** [comment]
I opened a pull request but I think it's premature. The latest non-LTS release (Ubuntu 17.10.1) comes with GNOME Shell. But, the latest LTS release (Ubuntu 16.04.3 LTS) doesn't. If a user wants Ubuntu 16.04.3 LTS with GNOME Shell, they'll have to download the Ubuntu GNOME flavor. Thus, it shouldn't be removed from the flavor matrix (yet).

**Comment by pmahnke** [comment]
I agree with @cbrownstein this should be done with the 18.04 release only. (cc @anthonydillon )

**Comment by pmahnke** [comment]
this will be released tomorrow - #2908 fixes it

**Comment by darkxst** [comment]
Ubuntu GNOME 16.04 is still technically supported, while I don't expect many people would be installing that, maybe its worth holding out until 18.04.1 before dropping this. At that point the vast majority of our users will have migrated to Ubuntu proper.
