### ISSUE TITLE
Text update on https://www.ubuntu.com/desktop/1710

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2635]
Amend intro text to read: 

"In April 2018, the next long-term support (LTS) release of Ubuntu will come with GNOME Shell as an option. Ubuntu 17.10 is the first release to include the new shell, so it’s a great way to preview the future of Ubuntu."

---
*Reported from: https://www.ubuntu.com/desktop/1710*

**Comment by cbrownstein** [comment]
> In April 2018, the next long-term support (LTS) release of Ubuntu will come with GNOME Shell as default.

https://www.ubuntu.com/desktop/1710

Is it not accurate that 18.04 LTS will feature GNOME Shell as default? Curious. I thought it was. Thanks.

**Comment by anthonydillon** [comment]
I believe the GNOME Shell will be the default in Bionic. @kasiag can you confirm with the source of the request please?

**Comment by pmahnke** [comment]
yes GNOME will be the default... closing this issue
