### ISSUE TITLE
Flavor matrix does not display properly if a flavor is removed

### ISSUE THREAD

**Issue by cbrownstein** [canonical-websites/www.ubuntu.com#2639]
## Summary

If a flavor is removed from the matrix, the matrix no longer displays properly. See screenshot.

## Process

Remove Ubuntu GNOME (or presumably any other flavor) from the matrix.

## Current and expected result

Bottom border of row 2 column 3 disappears. It should not.

## Screenshot

![gnome_deleted](https://user-images.githubusercontent.com/25962175/35965204-fe097de8-0c6e-11e8-9251-41d100eaf072.png)

**Comment by anthonydillon** [comment]
Good spot. This is in fact an issue with the CSS framework: Vanilla framework. Would you mind filing this issue on that project and closing this one.
https://github.com/vanilla-framework/vanilla-framework/issues/new

**Comment by cbrownstein** [comment]
Done: https://github.com/vanilla-framework/vanilla-framework/issues/1587

Closing this issue.
