### ISSUE TITLE
Global navigation

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2643]

**Comment by kwm14** [comment]
## Visual exploration
- reuse of Vanilla components
- exploring component combinations

### 001 
![global-nav-002](https://user-images.githubusercontent.com/17748020/36143084-005b8348-10a2-11e8-8ace-6f76d5d94c61.png)

### 0012
![global-nav-003](https://user-images.githubusercontent.com/17748020/36143085-007b6de8-10a2-11e8-8ffa-9d1a257b27bb.png)

### 003
![global-nav-004](https://user-images.githubusercontent.com/17748020/36143086-00a047da-10a2-11e8-82c3-65fe2bdff0d5.png)

### 004
![global-nav-005](https://user-images.githubusercontent.com/17748020/36143087-00c60d12-10a2-11e8-9656-e401de82c5ef.png)

### 005
![global-nav-006](https://user-images.githubusercontent.com/17748020/36143088-00e5dd5e-10a2-11e8-9407-d792e6bbad62.png)

**Comment by kwm14** [comment]
## Review
- explore matrix  layout as 2-col
- reduce logo height to 24px
- 10px padding vs 20px padding
- full logo vs icon/link

**Comment by kwm14** [comment]
## Continued exploration
- applied review changes to new explorations

### 006
![global-nav-007](https://user-images.githubusercontent.com/17748020/36143367-d2bc6c12-10a2-11e8-8a7b-d14a4a33cb91.png)
### 007
![global-nav-009](https://user-images.githubusercontent.com/17748020/36143385-dbd41930-10a2-11e8-956e-d18f8691ee1a.png)
### 008
![global-nav-010](https://user-images.githubusercontent.com/17748020/36143387-dbf67cf0-10a2-11e8-9b03-e1988bfe73c9.png)
### 009
![global-nav-011](https://user-images.githubusercontent.com/17748020/36143388-dc1d47e0-10a2-11e8-8dca-de9289e992dc.png)
### 010
![global-nav-012](https://user-images.githubusercontent.com/17748020/36143389-dc43e918-10a2-11e8-87a0-2d9f238ff541.png)

**Comment by kwm14** [comment]
## Review
- +1 new matrix padding on design 006
- 008 can't see full product list above the fold
- 010 preferred design layout (craiglist inspired)
- update design going forward with top navigation

**Comment by kwm14** [comment]
## Global navigation in situ
- updated preferred design 
- explored nav dropdown options

### 011 Fixed menu
![global-nav-013](https://user-images.githubusercontent.com/17748020/36148290-6874b902-10b3-11e8-8e56-9eae4a4a58ce.png)

### 012 Contained menu
![global-nav-014](https://user-images.githubusercontent.com/17748020/36148291-68993480-10b3-11e8-8028-6199ad5f7085.png)

### 013 Overlay menu
![global-nav-015](https://user-images.githubusercontent.com/17748020/36148295-68d2d870-10b3-11e8-8628-a6f7c20783d2.png)

**Comment by pmahnke** [comment]
@kwm14 could we explore a dark version too?

**Comment by anthonydillon** [comment]
Some sites navigation is full width (fluid) which looks strange when the
global nav is restrained by the page width.

Maybe you could explore making it full width across all sites. Even the
sites that have restricted navigation widths.

Then you revealed content could also be full width which should reduce the
height of the panel and give it a visual difference from the page content
below.

**Comment by kwm14** [comment]
## Design review

_Attendees: @spencerbygraves @pmahnke @frankiegranato_ 

- 010 design preferred
- discuss dropdown animation once design is signed off
- create a dark version of 010
- add to both designs to presentation

**Comment by kwm14** [comment]
## Design update
- Taking all feedback into consideration

### 014
![global-nav-014](https://user-images.githubusercontent.com/17748020/36376764-3f39dcda-156c-11e8-8ebb-ef4c59d315fc.png)

### 015
![global-nav-015](https://user-images.githubusercontent.com/17748020/36376765-3f6425e4-156c-11e8-837c-56828c7cf0b2.png)

**Comment by anthonydillon** [comment]
Again, this issue with constricting the width of the global navigation drop-down content is that some sites have different widths which will make this look unaligned. 

The global navigation is a stand alone component. Which means it cannot inherit or be bespoke to a website.

**Comment by kwm14** [comment]
## Review with Mark
- update Landscape and Snaps logo
- preferred for look
- update colour of linked headings to black
- work on ways to 'connect' top bar nav with dropdown
   - use dark grey instead of black
   - white version?
- reduce 'Canonical' logo size even further

**Comment by kwm14** [comment]
## Updated visual exploration
- taking all feedback into consideration
- full-width to match nav (reduces dropdown height)
- 3 color way options
- if we were to go with the darker option which Mark favours I will need to adjust colour on primary nav
- @spencerbygraves ready for re-review

### 016 - color-x-light
![global-nav-017](https://user-images.githubusercontent.com/17748020/36476406-ba5cf246-16f5-11e8-91e0-57b26d93a227.png)

### 017 - color-mid-dark
![global-nav-017a](https://user-images.githubusercontent.com/17748020/36476408-ba8461d2-16f5-11e8-98af-24bda547f489.png)

### 018 - color-brand
![global-nav-017b](https://user-images.githubusercontent.com/17748020/36476409-baa92684-16f5-11e8-80ae-857c7b655c2b.png)

**Comment by spencerbygraves** [comment]
@kwm14 Here's some feedback from @marcush and I...

- We prefer the dark grey, but think that #111 might be better. Marcus would also like to see a version with the the top strip in the dark aubergine (#2C001E) with #111 below.
- The margins left and right feel a bit narrow, and the 3 columns a touch too wide, although I can see you're trying to keep it aligned with the logo. What would happen on very large screens, keep getting wider or fix at 1440px for example? It would be good to try a version with wider margins left and right at 1440px, if we fix at 1440px we'll lose that logo alignment anyway on wider screens.
- Use the light Snaps logo on dark backgrounds

Thanks

**Comment by kwm14** [comment]
## Design review updates
- updates based on feedback
- global nav colour now dark aubergine
- two versions of margins at `2rem` and `3rem`
- updated Snaps logo

### 019
- margin left and right - `2rem`

![global-nav-019](https://user-images.githubusercontent.com/17748020/36480377-05e28fd8-1704-11e8-8c7a-27162e975ea2.png)

### 020
- margin left and right - `3rem`

![global-nav-020](https://user-images.githubusercontent.com/17748020/36480378-06050fd6-1704-11e8-9e5f-aa6ee0f22e6f.png)

**Comment by spencerbygraves** [comment]
@kwm14 👍 020 (pending the row test with @Caleb-Ellis)

**Comment by frankiegranato** [comment]
@kwm14 & @spencerbygraves I wonder if we need a more obvious 'close' mechanism? The arrow is very subtle and once you've scrolled down the menu, it goes out of sight. Not sure what the right solution is though.
Also, for me, the aubergine strip is too disconnected from the dark grey drop down. I think I preferred it  when both components of the menu were the same colour.

**Comment by kwm14** [comment]
@frankiegranato you have a fair point but the global navigation itself is quite subtle. When we begin testing the beta on users we can see if the interactions actually work or not, and hopefully results will show if the global navigation is a success 👍 

When reviewing with Marcus and Spencer we all felt the dark aubergine worked and the presence of the Canonical brand, I still need to apply it to external product sites to make sure it works 😄

**Comment by spencerbygraves** [comment]
@frankiegranato @kwm14 we can use the beta to quickly test colour combinations, and let's see what happens in testing with opening and closing the nav. If a user scrolls we could also close it by clicking away.

**Comment by kwm14** [comment]
Closing issue as it's design related. @Caleb-Ellis is currently exploring interactions based on our discussion yesterday [here](https://github.com/canonical-websites/www.ubuntu.com/issues/2740)

**Comment by anthonydillon** [comment]
As a heads up. All the design tasks for www.ubuntu.com should be on the design repo: https://github.com/ubuntudesign/www.ubuntu.com-design
