### ISSUE TITLE
Primary navigation menu

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2644]

**Comment by kwm14** [comment]
## Primary navigation options
- nav inside Vanilla grid
- new Vanilla full width nav
- new Vanilla header search box

### 001
![primary-nav-001](https://user-images.githubusercontent.com/17748020/36163311-e8a33dba-10e0-11e8-8c67-ecb8de01d802.png)

### 002
![primary-nav-002](https://user-images.githubusercontent.com/17748020/36163312-e8cbbbfa-10e0-11e8-8b3f-08747551665a.png)

### 003
![primary-nav-003](https://user-images.githubusercontent.com/17748020/36163314-e8f68524-10e0-11e8-9f67-8d45eda7e593.png)

**Comment by kwm14** [comment]
## Next steps
- 002 preferred nav design
- explore adding dropdown content for:

   - Enterprise
   - Developer
   - Community

**Comment by kwm14** [comment]
## Visual exploration w/content
- First pass exploring layout for **Enterprise** section
- Once decided on a layout solution I will follow same style for **Developer** and **Community**
- Followed Marks layout in copydoc

### 001 - Divider list
![primary-nav-enterprise-004](https://user-images.githubusercontent.com/17748020/36210191-b3ec31ca-1195-11e8-8e7a-0460ddae62db.png)

### 002 - Break line
![primary-nav-enterprise-001](https://user-images.githubusercontent.com/17748020/36210200-ba656cba-1195-11e8-825b-dd85c950fcdd.png)

### 003 - Muted heading (Spencer style)
![primary-nav-enterprise-003](https://user-images.githubusercontent.com/17748020/36210214-c16b971e-1195-11e8-81b6-6d9fd16cb846.png)

### 004 - Compact craiglist style
![primary-nav-enterprise-002](https://user-images.githubusercontent.com/17748020/36210244-da0f8028-1195-11e8-9eb1-7aa28cd50466.png)

**Comment by kwm14** [comment]
## Primary nav - Product extension
- Applying products navigation style
- Proposal to update MAAS header to white (currently doesn't work with nav black > black > black)

### Canoncial
![brand-extension-canonical](https://user-images.githubusercontent.com/17748020/36301573-472ed61e-12fd-11e8-9ed4-f57ad4604929.png)

### Conjure-up
![brand-extension-conjure-up](https://user-images.githubusercontent.com/17748020/36301574-4754220c-12fd-11e8-84e8-ff558698724a.png)

### Juju
![brand-extension-juju](https://user-images.githubusercontent.com/17748020/36301575-47783f2a-12fd-11e8-9b7e-464593c941cb.png)

### LXD
![brand-extension-lxd](https://user-images.githubusercontent.com/17748020/36301576-47a44188-12fd-11e8-9b09-2bfa38aee122.png)

### MAAS
![brand-extension-maas-white](https://user-images.githubusercontent.com/17748020/36301578-48168ca2-12fd-11e8-8aa4-17974d820171.png)

### Snapcraft
![brand-extension-snapcraft](https://user-images.githubusercontent.com/17748020/36301579-483d5666-12fd-11e8-8169-d7fd74325c71.png)

**Comment by kwm14** [comment]
## Design review

_Attendees: @spencerbygraves @pmahnke @frankiegranato_ 

- 001 and 004 preferred design
- remove heading from 004
- add grey background to divide resources on 001 design
- add both the presentation

**Comment by kwm14** [comment]
## Design update
- Based on feedback from review

### 005
![primary-nav-enterprise-005](https://user-images.githubusercontent.com/17748020/36376533-4e24e5e2-156b-11e8-9550-dd80c1a1795e.png)

### 006
![primary-nav-enterprise-006](https://user-images.githubusercontent.com/17748020/36376534-4e4b3008-156b-11e8-8e8b-8722cf548b81.png)

**Comment by kwm14** [comment]
## Review with Mark
- 006 preferred layout "felt to be tidier"
- bigger font size on nav items
- no blue links on linked headings
- sticky nav +1
- apply this design layout to both 'Developer` and `Community` pages

**Comment by kwm14** [comment]
## Updated visual exploration
- currently u.com uses 14px font size inside the primary nav
- we showed Mark updated version using 16px but said it's still too small

### 007 - 18px (not in Vanilla)
![nav-item-size-18px](https://user-images.githubusercontent.com/17748020/36485690-9c105138-1714-11e8-928a-727ecd33cab1.png)

### 008 - 20px (h5 in Vanilla)
![nav-item-size-20px](https://user-images.githubusercontent.com/17748020/36485693-9c4f66de-1714-11e8-8bd2-7d22261007e0.png)

**Comment by kwm14** [comment]
Design review updates
- taking all feedback into consideration
- Enterprise, Developer and Community sections
- 006 layout applied to all pages

### 009 - Enterprise
![primary-nav-enterprise-008](https://user-images.githubusercontent.com/17748020/36491393-8e8774b6-1722-11e8-81b6-d40fdaaf086d.png)

### 009 - Developer
![primary-nav-developer-008](https://user-images.githubusercontent.com/17748020/36491407-98d7dcf8-1722-11e8-9eb8-38d0acfeefe9.png)

### 009 - Community
![primary-nav-community-008](https://user-images.githubusercontent.com/17748020/36491418-a0606a3a-1722-11e8-8095-97b87b1f887e.png)

**Comment by spencerbygraves** [comment]
@kwm14 agree to try 18px links for testing and 👍 for white.

**Comment by kwm14** [comment]
Added latest designs in build issue for @Caleb-Ellis. Closing issue.
