### ISSUE TITLE
Design secondary navigation on ubuntu.com

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2648]

**Comment by kwm14** [comment]
## Mark's initial design
- secondary nav to have custom lockup 

![screen shot 2018-02-16 at 14 49 37](https://user-images.githubusercontent.com/17748020/36313193-be5b7226-1328-11e8-9f64-82ce227ba39f.png)

**Comment by kwm14** [comment]
## Discussion with Tom
- spoke with Tom about our current brand extension guidelines
- currently only designed for horizontal layout

![screen shot 2018-02-16 at 14 52 13](https://user-images.githubusercontent.com/17748020/36313294-00d3ba14-1329-11e8-8ebe-a831cbf74366.png)

- further discussion asking for a vertical layout
- Tom previously created brand extension lockups for expos

![delivered-by_black-orange_hex](https://user-images.githubusercontent.com/17748020/36313352-2ab08722-1329-11e8-92da-193b82be9620.png)

**Comment by kwm14** [comment]
## Visual exploration
- Referencing Mark's design from copy doc
- Using Toms vertical brand extension as a guide

![brand-extension-community-20px](https://user-images.githubusercontent.com/17748020/36313422-67c5d252-1329-11e8-94cb-c48bd662bd49.png)

![brand-extension-containers-20px](https://user-images.githubusercontent.com/17748020/36313423-67eb3010-1329-11e8-8824-a91e58037f73.png)

![brand-extension-download-20px](https://user-images.githubusercontent.com/17748020/36313424-680d6d10-1329-11e8-8632-5b565a17cad0.png)

![brand-extension-iot-20px](https://user-images.githubusercontent.com/17748020/36313425-6830387c-1329-11e8-88cb-c87ea7f4c815.png)

![brand-extension-management-20px](https://user-images.githubusercontent.com/17748020/36313426-6856726c-1329-11e8-874a-f715883a3fbe.png)

![brand-extension-openstack-20px](https://user-images.githubusercontent.com/17748020/36313427-6878e658-1329-11e8-8ebd-dfd47fd33509.png)

![brand-extension-public-cloud-20px](https://user-images.githubusercontent.com/17748020/36313430-68a0ae04-1329-11e8-9738-af9d209e8b0e.png)

![brand-extension-security-20px](https://user-images.githubusercontent.com/17748020/36313431-68c5998a-1329-11e8-9a29-f71533a7700f.png)

**Comment by kwm14** [comment]
## Design review

_Attendees: @spencerbygraves @pmahnke @frankiegranato_ 

- +1 from team on new brand extension
- update secondary navigation to be white
- add all to presentation for Mark to see

**Comment by kwm14** [comment]
## Review with Mark
- brand extension well liked :)
- try smaller Ubuntu logo
- Mark likes vertical layout
- speaking with Marcus we need to explore this lockup further
   - circle of friends/extension
   - ubuntu/extension as text
   - circle of friends w/ubuntu text/extension
- product extensions should follow same styling of u.com
   - future piece which will need exploring
   - will try one version on MAAS and conjure-up

**Comment by kwm14** [comment]
## Visual exploration of brand extension
- taking feedback from Marcus
- 004 and 005 wider versions
- @spencerbygraves ready for re-review

### 001
![brand-extension-community-002](https://user-images.githubusercontent.com/17748020/36594318-97ff5f30-1895-11e8-990d-b0aa40e5c4a6.png)

### 002
![brand-extension-community-004](https://user-images.githubusercontent.com/17748020/36594321-9f4ea840-1895-11e8-97a0-36f6985f8e8d.png)

### 003
![brand-extension-community-005](https://user-images.githubusercontent.com/17748020/36594322-9f76940e-1895-11e8-960d-7a1db35dea59.png)

### 004
![brand-extension-community-001](https://user-images.githubusercontent.com/17748020/36594344-b1b572e8-1895-11e8-8a41-aac39d8e531b.png)

### 005
![brand-extension-community-003](https://user-images.githubusercontent.com/17748020/36594352-b88c3d9a-1895-11e8-83e2-a45fd1988854.png)

**Comment by spencerbygraves** [comment]
@kwm14 let's discuss on Monday with @marcush. I'll leave the review label until then. Thanks.

**Comment by pmahnke** [comment]
from my point of view, the word 'Ubuntu' needs to be there, otherwise, new people might think it is a Canonical website.

**Comment by kwm14** [comment]
## Design review
_Attendees: @spencerbygraves, Marcus and Tom_

- 004 preferred version
- use Ubuntu logo so that circle of friends is apparant
- all lower case on page extensions
- explore long and short version (IoT and Community)
- explore 18px and 20px versions of type size
- check all sub-pages so that cover odd character heights

**Comment by kwm14** [comment]
## Updated design
- design updates based on yesterdays feedback
- 006 24px thin version
- 007 20px light version

### 006 management
![brand-extension-management-006](https://user-images.githubusercontent.com/17748020/36725570-9833cc90-1bae-11e8-9c55-91be38a13a01.png)

### 006 IoT
![brand-extension-iot-006](https://user-images.githubusercontent.com/17748020/36725587-a83c8078-1bae-11e8-8894-776ae26963fc.png)

### 007 management
![brand-extension-community-007](https://user-images.githubusercontent.com/17748020/36725599-b2f9fcde-1bae-11e8-85ef-6b7361f57a33.png)

### 007 IoT
![brand-extension-iot-007](https://user-images.githubusercontent.com/17748020/36725618-c04bf4a0-1bae-11e8-8196-099f49b0de58.png)

**Comment by kwm14** [comment]
## Design review
_Attendees: @spencerbygraves, Marcus and Tom_

- 007 preferred version
- increase size of Ubuntu logo slightly
- align Ubuntu logo to top of primary navigation items
- align page extension to bottom of secondary navigation items

**Comment by kwm14** [comment]
## Updated design
- design updates based on feedback

### 008 Management
![brand-extension-management-008](https://user-images.githubusercontent.com/17748020/36735063-31c0967c-1bcd-11e8-92cb-847e0e338545.png)

### 008 IoT
![brand-extension-iot-008](https://user-images.githubusercontent.com/17748020/36735062-319c2850-1bcd-11e8-9c6d-4fa38ef7f28a.png)

**Comment by kwm14** [comment]
## Design review
_Attendees: Marcus
- reduce padding in-between logo and extension text (1/3)

**Comment by kwm14** [comment]
## Updated design
- reduced padding
- reduced height of secondary navigation to accommodate new extension

### 009 Management
![brand-extension-management-009](https://user-images.githubusercontent.com/17748020/36743112-59749b5a-1be1-11e8-947e-0a615d66a9d0.png)

### 009 IoT
![brand-extension-iot-009](https://user-images.githubusercontent.com/17748020/36743129-6012f6b4-1be1-11e8-9a66-1c7476002a1b.png)

**Comment by kwm14** [comment]
## Design review
_Attendees: Marcus
- nearly there, can you try a version with 'Management' in lower case
- IoT spacing looks odd?

**Comment by kwm14** [comment]
## Updated design
- updated to lower case
- adjusted kerning on IoT

### 010 Management
![brand-extension-management-010](https://user-images.githubusercontent.com/17748020/36788334-723d764e-1c85-11e8-82a0-f75163efff10.png)

### 010 IoT
![brand-extension-iot-010](https://user-images.githubusercontent.com/17748020/36788343-7db03610-1c85-11e8-8f9a-396b545105d2.png)

**Comment by kwm14** [comment]
## Design review
_Attendees: Marcus
- I think we should go with capitals version

**Comment by kwm14** [comment]
## Updated design
- updated to use capitals

### 011 Management
![brand-extension-management-011](https://user-images.githubusercontent.com/17748020/36794469-5be68576-1c98-11e8-894c-82a0db3d0473.png)

### 011 IoT
![brand-extension-iot-011](https://user-images.githubusercontent.com/17748020/36794486-6515da5c-1c98-11e8-9efc-8fdf42b45afb.png)

**Comment by spencerbygraves** [comment]
👍 from @marcush

**Comment by kwm14** [comment]
Closing issue. Will add signed-off designs in build issue for @Caleb-Ellis.
