### ISSUE TITLE
Primary nav build

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2650]

**Comment by kwm14** [comment]
@Caleb-Ellis primary nav design signed off [here](https://github.com/canonical-websites/www.ubuntu.com/issues/2644).

- navigation font-size: `18px` (not in Vanilla but just for testing)
- navigation background-color: `#FFFFFF`
- design added below for visual reference

### Enterprise
![primary-nav-enterprise-008](https://user-images.githubusercontent.com/17748020/36534047-53f4d366-17bd-11e8-8509-407c93671834.png)

### Developer
![primary-nav-developer-008](https://user-images.githubusercontent.com/17748020/36534110-83016e94-17bd-11e8-9bde-516368e2ea52.png)

### Community
![primary-nav-community-008](https://user-images.githubusercontent.com/17748020/36534077-666e08c8-17bd-11e8-8c30-d97aef0498a7.png)

**Comment by kwm14** [comment]
@Caleb-Ellis small update to primary navigation content
- re-review with Spencer
- can we remove max-width on row so we use default 1030px grid
