### ISSUE TITLE
Secondary nav build

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2651]

**Comment by kwm14** [comment]
@Caleb-Ellis signed-off design issue for secondary nav can be found [here](https://github.com/canonical-websites/www.ubuntu.com/issues/2648#issuecomment-368953788). Adding mini spec and visual reference for you below:

## Design spec
- ubuntu logo to align to top of primary navigation items
- ubuntu logo margin left/right: `20px`
- page extension font size: `20px`
- page extension to align to bottom of secondary navigation items
- padding in-between ubuntu logo and page extension: `0.25rem`

## Page extension examples
![brand-extension-iot-011](https://user-images.githubusercontent.com/17748020/36796506-9aa6d586-1c9d-11e8-9bdd-969b955712fa.png)
![brand-extension-management-011](https://user-images.githubusercontent.com/17748020/36796507-9acde9dc-1c9d-11e8-97c5-1002f120943e.png)
