### ISSUE TITLE
Update /community/code-of-conduct

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2654]
move /community/code-of-conduct page

**Comment by pmahnke** [comment]
This is a straightforward move of www.ubuntu.com/project/about-ubuntu/conduct to www.ubuntu.com/community/code-of-conduct.

[copy doc](https://docs.google.com/document/d/1SWBQmBvpVvJnSZVB7aEDWLOo8rBhHgTkYii1Wvgjx20/edit)

### Work

* You need to create a redirect
