### ISSUE TITLE
Update /community/mission

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2655]
Move the philosophy page to /community/mission

**Comment by pmahnke** [comment]
### Work

- update the text of the existing https://www.ubuntu.com/about/about-ubuntu/our-philosophy page into the https://www.ubuntu.com/community/misson page with the text in the [copy doc](https://docs.google.com/document/d/1KREEL0iRsg7G1Sol4J5v7EraNljDTiIYMem5_rQLtKE/edit#)
- create a redirect
