### ISSUE TITLE
Update /community/governance 

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2656]
Move /community/governance

**Comment by pmahnke** [comment]
### Work

- move the page
- update the meta description based on the [copy doc](https://docs.google.com/document/d/11obb5eQNVwAD8auz2SLFqiZeTVpqbj8uph0jShsZvVA/edit#)
- redirect www.ubuntu.com/about/about-ubuntu/governance to www.ubuntu.com/community/governance
