### ISSUE TITLE
Update /community/debian

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2659]
Move and update /community/debian

**Comment by pmahnke** [comment]
### Work

- update text of www.ubuntu.com/community/debian with the [copy doc](https://docs.google.com/document/d/16wyBJyzmRJMkz677QFkfXWapie22SyGrjXHduo8GibA/edit#)
- Redirect www.ubuntu.com/about/about-ubuntu/ubuntu-and-debian to www.ubuntu.com/community/debian
