### ISSUE TITLE
Update /community/canonical 

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2660]
Move and update /community/canonical

**Comment by pmahnke** [comment]
### Work

- update the text and meta description per the [copy doc](https://docs.google.com/document/d/1kup0vH-dschLdqhjp7CuktEa8CNoLPSm5Fo24y4y1lc/edit#)
- redirect www.ubuntu.com/about/canonical-and-ubuntu to www.ubuntu.com/community/canonical
