### ISSUE TITLE
Create the /download/core/orange-pi-zero page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2670]
create the www.ubuntu.com/download/core/orange-pi-zero   page

**Comment by pmahnke** [comment]
### /download/core/orange-pi-zero  

- [copy doc](https://docs.google.com/document/d/1vMQ9DesjpV3fA1iVpKxdHYANbf2Y-Mp5rIXGnV3HypY/edit#)
- [dev.u.c page](https://developer.ubuntu.com/core/get-started/orange-pi-zero)
