### ISSUE TITLE
Create the /download/core/up-squared-iot-grove page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2671]
Create the www.ubuntu.com/download/core/up-squared-iot-grove page

**Comment by pmahnke** [comment]
@caldav is this a real page that we have somewhere?

**Comment by caldav** [comment]
https://developer.ubuntu.com/target-platforms/boards/up-squared

**Comment by pmahnke** [comment]
### Work

- Create the /download/core/up-squared-iot-grove page from the [copy doc](https://docs.google.com/document/d/1-q8NzhmqYvPCAT2AwSv7N9sr_TgJdCc8_gLT7RmaoNE/edit#)
- Based on the [dev.u.c page](https://developer.ubuntu.com/target-platforms/boards/up-squared)
