### ISSUE TITLE
Create the /download/core/intel-nuc page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2674]
create the www.ubuntu.com/download/core/intel-nuc page

**Comment by pmahnke** [comment]
### /download/core/intel-nuc 

- [copy doc](https://docs.google.com/document/d/1e2aWvVEEXvxDWSbxDzs-_tqKbKbW9sapjCjIRiuAdMg/edit#)
- [developer site page](https://developer.ubuntu.com/core/get-started/intel-nuc)
