### ISSUE TITLE
Create the /download/core/intel-joule page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2675]
create the www.ubuntu.com/download/core/intel-joule page

**Comment by pmahnke** [comment]
### /download/core/intel-joule

* [copy doc](https://docs.google.com/document/d/1uniGWQZokDNQIzdUEeq6WGs_x2jxa-vwA03TZ39kCWc/edit#)
* [develper.u.c page](https://developer.ubuntu.com/core/get-started/intel-joule)
