### ISSUE TITLE
Create the /download/core/kvm page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2676]
create the www.ubuntu.com/download/core/kvm  page

**Comment by pmahnke** [comment]
### /download/core/kvm 

- [copy doc](https://docs.google.com/document/d/1FHIArLpuAyLe2gnDwymefvzc4Lg8dSGvN8QAl8wX18Q/edit#)
- [dev.u.c page](https://developer.ubuntu.com/core/get-started/kvm)
