### ISSUE TITLE
Create the /download/core page

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#2677]
create the www.ubuntu.com/download/core page

**Comment by pmahnke** [comment]
### /download/core

- [copy doc](https://docs.google.com/document/d/1Sxdl5cGGe1wbHmKB2eL2zQLfVW3KBea02a2FIGx3VdQ/edit)
- [dev.u.c page](https://developer.ubuntu.com/core/get-started)
