### ISSUE TITLE
OpenStack support table shows wrong Extended support EOL dates

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#2681]
The OpenStack extended support releases are supported for 36 months according to:

https://wiki.ubuntu.com/OpenStack/CloudArchive

If you look at the text table for OpenStack on the EOL page, it shows Kilo ending in April 2017 and Ocata ending in Aug 2019. These should both be 36 months from their initial release date.

Thanks!

---
*Reported from: https://www.ubuntu.com/info/release-end-of-life*

**Comment by pmahnke** [comment]
@cjohnston1158 so, do they look 3 months too long?

what about that 'Extended customer support' bar? is that still valid?

**Comment by cjohnston1158** [comment]
Added comments to the spreadsheet

**Comment by anthonydillon** [comment]
@pmahnke can you estimate this please.

**Comment by pmahnke** [comment]
Overall
![image](https://user-images.githubusercontent.com/441217/36759568-bf67bfb8-1c0f-11e8-98c2-0d8ded43b3c5.png)

OpenStack
![image](https://user-images.githubusercontent.com/441217/36759500-7dd639c6-1c0f-11e8-8037-d04d9a5ad068.png)

Desktop
![image](https://user-images.githubusercontent.com/441217/36759550-a4408666-1c0f-11e8-85b2-73cb1d27b717.png)

**Comment by cjohnston1158** [comment]
Added two comments to the spreadsheet. Do we need to split Desktop and Server or could we use text to say that only server qualifies for ESM?
