### ISSUE TITLE
Ubuntu Desktop Screenshots are not updated

### ISSUE THREAD

**Issue by MrDiamond123** [canonical-websites/www.ubuntu.com#2708]
## Summary

Not all the screenshots of Ubuntu are updated. 

## Process
Look at the screenshots

## Current and expected result
I expected the images of the desktop would be updated for GNOME but are not

## Screenshot
(No need just look at the screenshots on the website)

**Comment by pmahnke** [comment]
@MrDiamond123 thanks for this.  We only update the screenshots with LTS releases, so we will for the April release... 

However, you can see gnome on https://www.ubuntu.com/desktop/1710

Closing for now.
