### ISSUE TITLE
Firefox icon is outdated

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#2714]
1\. Go to [the “Desktop features” page](https://www.ubuntu.com/desktop/features).
2\. Look at the Firefox icon.

What you see:
![the old icon](https://user-images.githubusercontent.com/19801137/36262590-d19d7f24-125f-11e8-97c1-9159ac6befc0.png)

What you should see:
![the new icon](https://user-images.githubusercontent.com/19801137/36262808-5dfb9c9e-1260-11e8-8980-6d27d039c965.png)

---
*Reported from: https://www.ubuntu.com/desktop/features*

**Comment by pmahnke** [comment]
@matthewpaulthomas we only update icons, etc... for LTS releases, I am guessing this is older.  We will update with 18.04.

Closing for now.

**Comment by matthewpaulthomas** [comment]
Firefox uses the new icon on Ubuntu 14.04 LTS and Ubuntu 16.04 LTS.
