### ISSUE TITLE
Make updates to UPM landing page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2728]

**Comment by frankiegranato** [comment]
@ant I've made an Epic and this issue to capture this work. Could you please review the estimate I made (total guess)? And also put card into relevant pipeline. Thanks

**Comment by anthonydillon** [comment]
This work is captured but phased issues:
- https://github.com/ubuntudesign/web-squad/issues/384
- https://github.com/ubuntudesign/web-squad/issues/385
- https://github.com/ubuntudesign/web-squad/issues/407
