### ISSUE TITLE
/legal section: Review Copy docs

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2731]
Also ask Catherine does marketing need to capture data, where does she want the data to go?

**Comment by frankiegranato** [comment]
Docs from katharine:

Contact us [copy doc]: https://docs.google.com/document/d/1_sM2dGQNd5FRda2gITWL1jD1oWsIekAw2jCxPTPD1Ss/edit

Legal Website Change Request - February 2018: https://docs.google.com/document/d/1o9e5Loh85f0H0uJGTfPuuwrgNVF0y1heYSVjfL2uu6U/edit?ts=5a81bc46#heading=h.htue3qlqrfl1

**Comment by frankiegranato** [comment]
Katherine still needs to add content to data-privacy copydoc: https://docs.google.com/document/d/1Xxy20AW7kLs-peWynDhVSS7YbFL4Mj58TXlN1VP8Yx4/edit#
