### ISSUE TITLE
Beta: Make primary nav sticky 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2739]

**Comment by frankiegranato** [comment]
As discussed with the gang: Lets remove "sticky" nav when drown down is expanded but lets make sticky nav appear on scroll-up. Please keep nav sticky in all other instances (ie. when the drown down is not in use). Sorry - about all the complicated logic that I'm sure this will involve (I do think its worth doing though - I think its the only way we can really assess if these menu interactions are usable or not).

**Comment by spencerbygraves** [comment]
@Caleb-Ellis @frankiegranato from the review...

The sticky header causes the open navigation to not scroll on screens shorter than the menu length. Can we try having the navigation appear only when you scroll back up the page please. And if possible to keep some white space to make sense of the selected state.

Thanks

**Comment by frankiegranato** [comment]
@Caleb-Ellis  lets catch up on this on Thursday. I think we said we should leave this until we've tested the beta.

**Comment by Caleb-Ellis** [comment]
After discussing this with @frankiegranato  and @spencerbygraves, we all agree that its best to leave the interaction as it is for now. There is no point doing an involved and time-consuming investigation into how to make a sticky nav work with expanded drop downs, before we've tested the BETA. Also, we've heard rumours that @pmahnke has received some direction from Mark about exploring the use of a darker primary nav (which might have beneficial implications for the drown downs) so we'll come back to this discussion once that exploration was been done. The original PR and demo have been left open as a point of reference for future discussion on the topic.
