### ISSUE TITLE
Homepage bug - Live news feed failed to load

### ISSUE THREAD

**Issue by Lewciie** [canonical-websites/www.ubuntu.com#2780]
## Summary

Live news feed failed to load

## Process

access www.ubuntu.com

## Current and expected result

homepage should display live news feed from insights.ubuntu.com, bug to load

## Screenshot

![image](https://user-images.githubusercontent.com/22214936/37041172-787d688e-2153-11e8-9ca3-657df9ef7cfd.png)

**Comment by nottrobin** [comment]
Thanks so much for letting us know. This has been fixed now!
