### ISSUE TITLE
The live news feed failed to load.

### ISSUE THREAD

**Issue by Jishanshaikh4** [canonical-websites/www.ubuntu.com#2783]
## Summary

The live news feed failed to load.
## Process

>    Open the main page (https://www.ubuntu.com/) and view for Latest news from insights.

## Current and expected result

The live news was failed to load, it needs to be loaded with insights.

## Screenshot

![screenshot from 2018-03-07 00-02-01](https://user-images.githubusercontent.com/30091032/37051066-8892eb48-219b-11e8-9856-444244468136.png)

**Comment by nottrobin** [comment]
Thanks @Jishanshaikh4, this is now fixed

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. A fix has been released and the feed is now working again.

**Comment by Jishanshaikh4** [comment]
Pleasure mine. Thanks for a wonderful website @nottrobin @anthonydillon.
