### ISSUE TITLE
Latest Insight News not loading

### ISSUE THREAD

**Issue by Davidhervil** [canonical-websites/www.ubuntu.com#2786]
## Summary

Latest news from insights not loading on the main website

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/12719889/37053069-8aa60f86-2151-11e8-9ac4-7ce1c9e9d44e.png)

**Comment by nottrobin** [comment]
Thanks for letting us know. We've fixed this now.
