### ISSUE TITLE
Update the homepage takeunder

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2797]
Please replace, the "How to pick a winning IoT business model" takeunder with a  "IoT security Whitepaper" takeunder. 

This takeunder should run for the same duration as the "How to pick a winning IoT business model" takeOVER.

Please get copy from the takeunder brief, which can be found here: https://docs.google.com/document/d/11cYDqmtEop-OU2MDtFJC_1aS6sld3TdK52ZvjrYxEYY/edit#

**Comment by pmahnke** [comment]
oh, I created a different one based on the takeover 

![image](https://user-images.githubusercontent.com/441217/37159378-ff9f7f32-22ed-11e8-8600-a1c68cd24ecd.png)


happy to use the one here if you prefer

**Comment by frankiegranato** [comment]
@anthonydillon I'm assigning this to you because I know you'll be best placed to assign it to whomever is able to to this work. 
Fyi @pmahnke this issue is related to ttps://github.com/canonical-websites/www.ubuntu.com/pull/2796
