### ISSUE TITLE
Logos appear squashed

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2811]
Squashed logos in partner section. See screen shot:
![screen shot 2018-03-13 at 15 44 31](https://user-images.githubusercontent.com/17002826/37352618-9467afe6-26d5-11e8-95ac-bbbee42bcc11.png)

---
*Reported from: https://www.ubuntu.com/containers*

**Comment by pmahnke** [comment]
I have fixed this in the beta, I could backport it... I will look tomorrow
