### ISSUE TITLE
Consolidate FCB pricing info

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#2817]
## Summary

I believe with the re-work of the pricing page, we were supposed to start using the pricing tables across the website to prevent conflict, extra work keeping things updated, etc. It appears as though we are maintaining two separate pricing tables for FCB, one on the [pricing page](https://www.ubuntu.com/support/plans-and-pricing) and one on the [Foundation Cloud Build page](https://www.ubuntu.com/cloud/foundation-cloud).. It would be very nice if we could consolidate this.

**Comment by pmahnke** [comment]
dup of #2818
