### ISSUE TITLE
/legal/data-privacy - build new 'data privacy' page

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2826]

**Comment by pmahnke** [comment]
@frankiegranato waiting on copy

**Comment by steverydz** [comment]
Add a new blank placeholder page for now whilst awaiting copy

**Comment by frankiegranato** [comment]
@steverydz  I just spoke to Katherine Ollerhead. She is unlikely to be able to supply the copy for this new page until next week so I've advised @steverydz to build a placeholder page for now. Here's the (currently empty) copydoc for the new 'Data-Privacy' page: https://docs.google.com/document/d/1Xxy20AW7kLs-peWynDhVSS7YbFL4Mj58TXlN1VP8Yx4/edit#

**Comment by frankiegranato** [comment]
Katherine has been delayed, so expect content by Monday 16th April

**Comment by steverydz** [comment]
@frankiegranato Is there any update on the content for this page?

**Comment by frankiegranato** [comment]
Data privacy copydoc from Katherine: https://docs.google.com/document/d/1AlOE2_-BqZNP4hiiuf8kZney8g1zvqAlDYl2u3X6m6I/edit#
