### ISSUE TITLE
Kubernetes and Docker logos warped on /containers page

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/www.ubuntu.com#2834]
## Bug
*Reported from: https://www.ubuntu.com/containers*

Partnering with Industry leaders section on /containers page has warped logos inside strip - Kubernetes and Docker

1. Navigate to https://www.ubuntu.com/containers
2. Scroll down to 'Partnering with Industry leaders'
3. You will notice Kubernetes and Docker logos are warped

## Screenshot
![screen shot 2018-03-19 at 11 25 56](https://user-images.githubusercontent.com/17748020/37592964-55d1f240-2b68-11e8-9cf8-63ee68bb1558.png)

**Comment by pmahnke** [comment]
this was fixed in #2811, which should go live today.
