### ISSUE TITLE
Ubuntu Server 17.10.1 Mirror Uni Hannover wrong link

### ISSUE THREAD

**Issue by TheodorD** [canonical-websites/www.ubuntu.com#2845]
Trying to download Ubuntu Server 17.10.1 amd64 redirected me to the Uni Hannover mirror, with a link being
 ```ftp://ftp.rrzn.uni-hannover.de/pub/mirror/linux/ubuntu-releases17.10.1/ubuntu-17.10.1-server-amd64.iso```
it is missing a slash.
the correct link would be
 ```ftp://ftp.rrzn.uni-hannover.de/pub/mirror/linux/ubuntu-releases/17.10.1/ubuntu-17.10.1-server-amd64.iso```
---
*Reported from: https://www.ubuntu.com/download/server*

**Comment by pmahnke** [comment]
@TheodorD I forgot to mention, but I have reported this to our IS team.

**Comment by pmahnke** [comment]
@TheodorD thanks again - from IS

> The offending Launchpad mirror config has been fixed.  I believe the Launchpad mirrors are brought in during deploy so this should happen soon (tomorrow if not tonight I imagine);
