### ISSUE TITLE
Update snappy contact methods

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#2860]
> join the snap crafting community — we have a fun crowd of people who hang out on Rocket Chat and on the snapcraft forum.

under 'Creating a snap is easy!' is outdated. See [the merged pull to the snapd repo](https://github.com/snapcore/snapd/pull/4453) and [the merged pull to the snapcraft repo](https://github.com/snapcore/snapcraft/pull/2022).

It should link to [the IRC](https://webchat.freenode.net/?channels=snappy) instead of the Rocket Chat.

---
*Reported from: https://www.ubuntu.com/desktop/snappy*

**Comment by pmahnke** [comment]
@Ads20000 sorry this has taken so long, but this page is actually going away as of tomorrow... I will close the bug
