### ISSUE TITLE
Implement copy updates on /download/server/ - 18.04

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2866]
* update with [copy doc](https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit#)

_note, waiting on update from dpb_

**Comment by frankiegranato** [comment]
@steverydz this copy doc is ready for build: https://docs.google.com/document/d/1FFQQUtzFGH88hA30qnZm-3pwVqcVl9UYyrNT4qQWrSM/edit

**Comment by frankiegranato** [comment]
Hang on - I just spotted one one unresolved comment from Peter in that doc I'm just chasing Stephan Fabel about it.

**Comment by frankiegranato** [comment]
@steverydz  this is ready for you :-)
