### ISSUE TITLE
Implement copy updates on /download/server/power8/ - 18.04

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2868]
Update with [copy doc](https://docs.google.com/document/d/1e-vav_b54KlKsi92w3rDu9J14O0gpp8yAanEAIImlE8/edit#)

_Note waiting on dpb_

**Comment by frankiegranato** [comment]
Still chasing David Britton and Ivan Dobos.

**Comment by frankiegranato** [comment]
@steverydz   this page is ready for you now :-)
