### ISSUE TITLE
Implement copy updates on /download/server/arm - 18.04

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2869]

**Comment by frankiegranato** [comment]
I've un-blocked this issue now. I think Peter's changes are ready in the doc: https://docs.google.com/document/d/1whVU3DvB9j5k6Ed3UvLZCEN6BU-lZcow4ZefqKQqokg/edit

**Comment by steverydz** [comment]
Fixed by #2865
