### ISSUE TITLE
Implement copy on /download/server/provisioning - 18.04

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2871]
Move ebook down and update instructions
See copydoc: https://docs.google.com/document/d/12GXYcP9WrOgoso6Sf3bQql6nALRUzpdlcRW3Gbu-npM/edit#

**Comment by frankiegranato** [comment]
This issue is still blocked as we are waiting for input from Andres. I'll keep chasing.

**Comment by anthonydillon** [comment]
There are no chances for the 18.04 release.
