### ISSUE TITLE
Updates to /maas (features) - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2873]
Features to reflect maas.io
Copydoc: https://drive.google.com/open?id=1IrlcBMrX_TDrRC8U1_QSbEOEJ55pGY7nnCd-nfZfiXM

**Comment by frankiegranato** [comment]
@shivjoshi1996   please do not go-live with the updated page until we have had an explicit "ok" from Andres (basically we don't want to mention any new/updated features until after the new version of Maas has been released). I'm adding a Don't Merge label.
