### ISSUE TITLE
Update /internet-of-things/robotics - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2878]
See copydoc: 

/robotics: https://docs.google.com/document/d/1g8XpVzDkAdFETrfZvOf5Q6WlYwHCBYQ8Y6TgTlyTEYc/edit#

/digital-signage: https://drive.google.com/open?id=1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ

/gateways: https://drive.google.com/open?id=1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU

**Comment by kasiag** [comment]
@steverydz has Frankie reviewed this?

**Comment by frankiegranato** [comment]
@steverydz;  @anasereijo is working on a design for the new "Ubuntu runs on the robotic platforms that matter" section. Please hold until that design is ready.

**Comment by frankiegranato** [comment]
Also, lets not include that weird video (I hadn't noticed it on the doc!). 
Also, there is a resource to update when you next get into that page.
Btw, I'll usually try to leave an @dev comment to highlight anywhere a change has taken place.
So sorry for all the confusion.

**Comment by anasereijo** [comment]
@frankiegranato new design here. Let me know if you are happy with it and then I'll save down for @steverydz 

![iot-robotics](https://user-images.githubusercontent.com/36884067/38865828-ed9839f6-4236-11e8-8670-1314a67ba081.jpg)

**Comment by frankiegranato** [comment]
Looks lovely @anasereijo

**Comment by anasereijo** [comment]
@steverydz copydoc updated. you can start building this. thanks
