### ISSUE TITLE
update /internet-of-things/digital-signage - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2880]
See copydoc: 

/robotics: https://docs.google.com/document/d/1g8XpVzDkAdFETrfZvOf5Q6WlYwHCBYQ8Y6TgTlyTEYc/edit#

/digital-signage: https://drive.google.com/open?id=1fFvBl-ZZvKDFV6OMv7O4kudQKtyxfvSU60rfVdKluAQ

/gateways: https://drive.google.com/open?id=1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU

**Comment by steverydz** [comment]
Fixed by #2878
