### ISSUE TITLE
Update /desktop - overview - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2881]
update screenshots
delete icons or images from the contextual footer

**Comment by frankiegranato** [comment]
@steverydz Fyi my portion of work is done on the /desktop-overview page, but you'll still be waiting on a number of image assets from Ana.

**Comment by anasereijo** [comment]
@steverydz all assets saved down for you.
copydoc with assets links:
https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit
final design:
![overview](https://user-images.githubusercontent.com/36884067/38806101-16dd1772-4170-11e8-8586-1da1d75ce224.jpg)
