### ISSUE TITLE
Update /desktop/developers - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2888]
Replace “Myapps” screenshot with dev.u.c - change to build.snapcraft.io
Update copy https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit
Update screenshot (x2 wallpapers)
Update graph
delete icons or images from the contextual footer

**Comment by anasereijo** [comment]
@steverydz this is done. 
final designs here: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/132#issuecomment-381581952

copydoc: https://docs.google.com/document/d/1VJ3xT2ViC-CvL0UmsAUzpYFmvpuqUP4AbpnlPm8tqOA/edit#
