### ISSUE TITLE
Update /desktop/features - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2893]
Copydoc: https://drive.google.com/open?id=1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU

**Comment by anasereijo** [comment]
@steverydz this is all done and saved for you.

**Final Design:**
https://github.com/ubuntudesign/web-squad/issues/467

Copy Doc:
https://docs.google.com/document/d/1nLHJlZ3igDwAAOUDP03wp4iKLxZts8110EA2ZOF5uaU/edit

**Comment by frankiegranato** [comment]
@steverydz Oopps - it looks like you started work on this card before it was ready. Clearly, we need to be communicating better with each other. We'll work on that :-)
