### ISSUE TITLE
/desktop/snappy - ux

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2895]
Copydoc: https://drive.google.com/open?id=19EIGiQ4FLfWVQczBgAqj5lIcWGnM0GmVGWggFIXcHt0

In a nutshell from Frankie: Remove and re-distribute content of desktop/snappy page

Evan's feedback: Under "A whole world of apps", the list should dynamically generate from the featured snaps (https://snapcraft.io/store). Each item should be a direct link to that app.

Instead of "Visit the Ubuntu apps directory", we should say something like "Discover more apps that run on Ubuntu at the Snapcraft Store." This should link to https://snapcraft.io/store.

Under "All the tools developers need", I do not think we should link to https://developer.ubuntu.com/. It looks like an abandoned website. I do not believe we have documentation for installing developer tools like Python or Visual Studio Code on Ubuntu. However, we do have documentation for producing snaps "whether your team uses Python, Ruby, Node.js or Java" (https://docs.snapcraft.io/build-snaps/languages) and I would suggest we make that the focus of this paragraph.

"Snaps are the new apps" is overly broad. The app I've written is the new app. Snaps are a way to release my app to a storefront viewed by tens of millions. The platform lets me efficiently manage updates so I can spend less time firefighting busted updates and more time writing features.
The space between "Snaps are the new apps" and "By developers, for developers" could hold a quote from one of our happy lighthouse vendors (Sarah CC'ed), as we've done with Barton under "Ubuntu certified PCs."

**Comment by frankiegranato** [comment]
UX work is complete. See /snappy copydoc: https://docs.google.com/document/d/19EIGiQ4FLfWVQczBgAqj5lIcWGnM0GmVGWggFIXcHt0/edit#
