### ISSUE TITLE
Update takeover for 18.04 and homepage- Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#2896]

**Comment by anasereijo** [comment]
@steverydz can you please also replace the laptop image with this one? https://assets.ubuntu.com/v1/c6504e94-Dell_XPS_Laptop_Front-Desktop.png

Should look like this:
![homepage screenshot](https://user-images.githubusercontent.com/36884067/38621657-39d1c366-3d99-11e8-8515-40e1f09a2ac1.jpg)

**Comment by anasereijo** [comment]
@steverydz 

mobile version (assets are the same as desktop):
![takeover-small-screen](https://user-images.githubusercontent.com/36884067/38678070-ecf52082-3e57-11e8-9b06-02ac7d160f8a.jpg)

**Comment by frankiegranato** [comment]
@steverydz Where is the demo? Perhaps I should do a UX Review?

**Comment by steverydz** [comment]
@frankiegranato The demo has gone as this issue is closed but you can see
the work here for now:
http://www.ubuntu.com-pr-2947.run.demo.haus

**Comment by steverydz** [comment]
The screenshot was changed as part of #2944 but for some reason that was closed without being merged. I've since merged it and you can see it on the release demo here: http://www.ubuntu.com-pr-2958.run.demo.haus/
