### ISSUE TITLE
selects inside tabs cause spacing between selected state and border-bottom

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/www.ubuntu.com#2897]
@lyubomir-popov commented on [Fri Apr 06 2018](https://github.com/canonical-websites/insights.ubuntu.com/issues/302)

## Summary
Causes this. I believe this is the correct repo, as the culprit - .p-tabs__item--select - is not part of vanilla.
https://github.com/vanilla-framework/vanilla-framework/issues/1682

## Process

[list the steps to replicate the issue]

## Current and expected result

selected state sitting above border

## Screenshot

https://user-images.githubusercontent.com/17748020/38320313-28620cac-382c-11e8-80c7-5b54c8940eb1.png

**Comment by steverydz** [comment]
Closing as this doesn't appear to be an issue anymore
