### ISSUE TITLE
Bug with AMD A9 Radeon 5 Graphics.

### ISSUE THREAD

**Issue by AlfonsoIMa** [canonical-websites/www.ubuntu.com#2900]
Hey, I installed 17.10 and it flashes windows and animations when I full-screen anything. My laptop is an HP bw005la so it does have AMD Graphics, I think that could be the problem; but indeed I didn't find any driver for my OS so, I raise my problem to you, thanks for making Ubuntu awesome! :+1:  

---
*Reported from: https://www.ubuntu.com/desktop/1710*

**Comment by pmahnke** [comment]
@AlfonsoIMa sorry, but you have filed this on the repo for the www.ubuntu.com website, can you please file it against the OS? - https://help.ubuntu.com/community/ReportingBugs
