### ISSUE TITLE
http://archive.canonical.com/ load balancing mirror at 91.189.91.15 is just a blank apache fresh install

### ISSUE THREAD

**Issue by superkuh** [canonical-websites/www.ubuntu.com#2916]
## Summary

The http://archive.canonical.com/ load balancing mirror at http://91.189.91.15/ is just a blank apache fresh install. When the Ubuntu round robin or whatever load balancer tells Ubuntu OS client package managers to use this mirror they fail and abort.

This has been going on for 2 days now.

## Process

Well, since it's a load balancer/DNS issue it really is sort of random. But since my OS has cached that IP for archive.canonical.com all I have to do is an,

$ apt-get update 
...
Hit http://old-releases.ubuntu.com lucid-security/universe Packages                                 
Hit http://old-releases.ubuntu.com lucid-security/multiverse Packages                               
Hit http://old-releases.ubuntu.com lucid-backports/main Packages                                    
Hit http://old-releases.ubuntu.com lucid-backports/restricted Packages                              
Hit http://old-releases.ubuntu.com lucid-backports/universe Packages                                
Hit http://old-releases.ubuntu.com lucid-backports/multiverse Packages    
...
Err http://archive.canonical.com lucid/partner Packages                                
  404  Not Found [IP: 91.189.91.15 80]
Err http://archive.canonical.com lucid/partner Packages                                
  404  Not Found [IP: 91.189.91.15 80]
...
W: Failed to fetch http://archive.canonical.com/ubuntu/dists/lucid/partner/binary-amd64/Packages.gz  404  Not Found [IP: 91.189.91.15 80]

W: Failed to fetch http://archive.canonical.com/dists/lucid/partner/binary-amd64/Packages.gz  404  Not Found [IP: 91.189.91.15 80]

E: Some index files failed to download, they have been ignored, or old ones used instead.

## Current and expected result

I expect the http://archive.canonical.com/ mirror to not just be a blank fresh apache install and actually have a repo and packages on it. This one currently does not.

## Screenshot

See the above log excerpt.

**Comment by superkuh** [comment]
I can access other servers that http://archive.canonical.com/ resolves to by tunneling my brower's DNS out to a remote server (ssh socks 5 proxy to VPS) and see that they work. But since my OS has cached this bad one it will not be fixed until I restart. I don't restart more than once a month usually.

**Comment by pmahnke** [comment]
@superkuh our IS team thinks it is because you are running the out of support lucid? see...


> The archive mirrors are name-based virtual hosts and will respond with an Apache page if the IP is hit directly, but will respond as expected as part of the archive.canonical.com hostname.  The reporter appears to be trying lucid, which is no longer a supported product:
> 
> $ curl -v -H "Host: archive.canonical.com" http://91.189.91.15/ubuntu/dists/ | grep xenial
> *   Trying 91.189.91.15...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 91.189.91.15 (91.189.91.15) port 80 (#0)
> > GET /ubuntu/dists/ HTTP/1.1
> > Host: archive.canonical.com
> > User-Agent: curl/7.47.0
> > Accept: */*
> > 
> < HTTP/1.1 200 OK
> < Date: Wed, 25 Apr 2018 22:54:38 GMT
> < Server: Apache/2.4.18 (Ubuntu)
> < Vary: Accept-Encoding
> < Content-Length: 5269
> < Content-Type: text/html;charset=UTF-8
> < 
> { [5269 bytes data]
> 100  5269  100  5269    0     0  34767      0 --:--:-- --:--:-- --:--:-- 34894
> * Connection #0 to host 91.189.91.15 left intact
> <tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="xenial-proposed/">xenial-proposed/</a></td><td align="right">2018-04-17 22:48  </td><td align="right">  - </td></tr>
> <tr><td valign="top"><img src="/icons/folder.gif" alt="[DIR]"></td><td><a href="xenial/">xenial/</a></td><td align="right">2018-03-28 09:41  </td><td align="right">  - </td></tr>
> 
> $ curl -v -H "Host: archive.canonical.com" http://91.189.91.15/ubuntu/dists/ | grep lucid
> *   Trying 91.189.91.15...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 91.189.91.15 (91.189.91.15) port 80 (#0)
> > GET /ubuntu/dists/ HTTP/1.1
> > Host: archive.canonical.com
> > User-Agent: curl/7.47.0
> > Accept: */*
> > 
> < HTTP/1.1 200 OK
> < Date: Wed, 25 Apr 2018 22:54:49 GMT
> < Server: Apache/2.4.18 (Ubuntu)
> < Vary: Accept-Encoding
> < Content-Length: 5269
> < Content-Type: text/html;charset=UTF-8
> < 
> { [5269 bytes data]
> 100  5269  100  5269    0     0  34802      0 --:--:-- --:--:-- --:--:-- 34894
> * Connection #0 to host 91.189.91.15 left intact

let me know if you think that is incorrect. closing for now.

**Comment by superkuh** [comment]
I think that is incorrect. I understand now why hitting the IP directly will show the blank apache page. But the fact is that the repo exists and the files exist on some of the mirrors. I took this screenshot a minute or two before commenting here,

http://superkuh.com/huh-what-are-these-lucid-repos-doing-existing-then.png
(I tried attaching the file but it didn't work so here's a copy hosted by me)

I guess if it is your intention to break the repo for lucid despite the fact that it does exist and could work just fine then this isn't a bug. Otherwise it is. And if it is you can ignore it because, as you say, lucid isn't supported anymore. But it'd be real nice if you didn't.
