### ISSUE TITLE
Implement copy updates on /download/desktop/thank-you - 18.04

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#2918]
* minor copy and link updated in the [copy doc](https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#heading=h.kavp9d2tequc)

**Comment by steverydz** [comment]
Closing as fixed by #2865
