### ISSUE TITLE
Spacing too tight

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2926]
See bottom of /download/desktop page. The spacing on headline "Get the version you need" seems too close to the line below it. See screen grab attached. 

![download ubuntu desktop - spacing error](https://user-images.githubusercontent.com/17002826/38556083-4cd8fa26-3cc0-11e8-8b7d-7a32bc0d2d62.png)

---
*Reported from: https://www.ubuntu.com/download/desktop*

**Comment by pmahnke** [comment]
closing as this will go away tomorrow.
