### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by dbrockus** [canonical-websites/www.ubuntu.com#2927]
Hello,

The "Autopilot" link on https://landscape.canonical.com/thank-you?aliId=42809164 (returned after filling out a contact form) is broken.  It links to _https://www.ubuntu.com/cloud/openstack/autopilot_, which generates a 404.

Regards,
David

---
*Reported from: https://www.ubuntu.com/cloud/openstack/autopilot*

**Comment by pmahnke** [comment]
@dbrockus thanks for filing this

@steverydz we will need to update via the launchpad code - I updated the copy doc here https://docs.google.com/document/d/1KKG5oLelB6xY62eDoFmXANEY9Z5Szg95ZTAZjZWw3p4/edit#
