### ISSUE TITLE
Updated design for /download page - build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2929]
Please implement version 2 of Ana's design for this page. This is linked to Ana's design card: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/139

**Comment by frankiegranato** [comment]
@anasereijo please add your design file here and anything else that @steverydz needs to build this page. 
@steverydz when you have seen the design, can you add an estimate to this issue please?

**Comment by anasereijo** [comment]
@steverydz see bellow the new design
![download v2](https://user-images.githubusercontent.com/36884067/38610064-a7294500-3d77-11e8-836a-47898107fc8d.jpg)

**Comment by anasereijo** [comment]
@steverydz it's all vanilla guidelines but see bellow a guide for spacing and alignment. any questions let me know! thank you
![final version spacing](https://user-images.githubusercontent.com/36884067/38610593-3e5f50bc-3d79-11e8-8450-7124c7ecb9fd.jpg)
