### ISSUE TITLE
Add quote to /IoT/gateways page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#2956]
Add Dell quote to page.
Can be released anytime.
Please see instructions in copydoc: https://docs.google.com/document/d/1hQon1vuYPDg_GojABIwbp2gFBkE2WApZTZJGT3yUdLU/edit

**Comment by steverydz** [comment]
Pull request: https://github.com/canonical-websites/www.ubuntu.com/pull/2959

(For some reason I couldn't link this issue? The option to do so wasn't there?)

**Comment by steverydz** [comment]
Demo: http://www.ubuntu.com-pr-2959.run.demo.haus/internet-of-things/gateways
