### ISSUE TITLE
Spelling mistake.

### ISSUE THREAD

**Issue by Devendrabhat** [canonical-websites/www.ubuntu.com#2992]
Gaming

From Sudoku to shoot-em-ups, we’ve got **loads** of games that’ll keep you busy for hours. There are thousands of games available for Ubuntu, including titles from the Unity and Steam platforms. Pick from critically acclaimed titles such as Dota 2, Civilization V, Kerbal Space Program, Football Manager 2015 and Borderlands 2.

That should be lots instead of loads.

---
*Reported from: https://www.ubuntu.com/desktop/features*

**Comment by pmahnke** [comment]
@Devendrabhat thanks for filing this; however, I am told that this is a correct use of the word.

But please file other things you see.
