### ISSUE TITLE
Is "Canonical's Kubernetes" the best term?

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#3016]
Going through /containers section, I see a lot of "Canonical's Kubernetes". I'm guessing this is the official way we refer to CDK? It seems a bit odd - really sounds much more like we own K8s than if we just said "Kubernetes" without qualification.

Can't we say "Canonical's Kubernetes distribution" or "our Kubernetes distribution"?

**Comment by pmahnke** [comment]
@nottrobin I agree... on /containers you could just say Kubernetes in the divided section.

on /kubernetes I think I agree s/Canonical Kubernetes/Canonical's Kubernetes/g

**Comment by shivjoshi1996** [comment]
Fixed via #3055
