### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by tsirko** [canonical-websites/www.ubuntu.com#3033]
## Summary

Error:Our partner logos failed to load. Please report this bug and our team will fix the problem as soon as possible.

## Process

https://www.ubuntu.com/server

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
@tsirko what kind of error are you seeing?  the partner logos appear to me... and they rotate... what are you expecting to see?

**Comment by tsirko** [comment]
It shows up just fine now, yesterday the logos did not load.

**Comment by pmahnke** [comment]
ok, thanks, I will close for now and watch that page.
