### ISSUE TITLE
update homepage takeunder - Dev

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3049]
please update the takeunder section.
keep Openstack and replace Product of the month with Kubernetes.
Copy and link addresses in the brief: https://docs.google.com/document/d/1Kr_Y_1LdB_AjqeVEdlAiEWVuNjj6o12WCQte_Uj1cSk/edit

**Comment by anasereijo** [comment]
@steverydz final design [here](https://github.com/canonical-websites/www.ubuntu.com/issues/3047) and links on copydoc

**Comment by steverydz** [comment]
![Design](https://user-images.githubusercontent.com/36884067/39246185-b625fafa-488d-11e8-8001-8d30905577a3.jpg)
