### ISSUE TITLE
Snags - round 2

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3058]
Snags - round 2 

High Priority:

"Ubuntu Server for IBM Z and LinuxONE" becomes /download/server/s390x: https://docs.google.com/document/d/1d85IfqqxZYYZ0orj5lBhqLWLGpLYWRLdvs75lYsplGs/edit

Add redirect for /telco on the /telecommunications page. Resolve note in copydoc once complete: https://docs.google.com/document/d/15FY_IaT39V81FQcoSoEJpmRRjBX80PJ7uxjgzHnDDws/edit

Medium Priority:

Add a re-direct for /desktop/1710 to /desktop/ Please resolve comment in copydoc when complete: https://docs.google.com/document/d/1ZhMkLlkXcimHTIe1taXy24vbbR9pBkZd49H2sJqeQH0/edit 

Low Priority:

Link change on /cloud/thank-you: https://docs.google.com/document/d/1-dWhd0ydDWlYg16rEybPPmkQ6cdxsBmiFOuUz0ApCBM/edit

One small text edit on /kubernetes page: https://docs.google.com/document/d/1G-h1eWiBSKqG9oWB15Pup8VDe1axBUwQGvtkwJ9g8T0/edit

**Comment by frankiegranato** [comment]
Please ensure redirect is functioning for /telco and a new one: /telcos

**Comment by frankiegranato** [comment]
Please ensure that redirect is functioning for http://www.staging.ubuntu.com/desktop/1710 as well.

**Comment by steverydz** [comment]
@frankiegranato It won't work on staging until this is merged but you can see it on the demo:

http://www.ubuntu.com-pr-3059.run.demo.haus/desktop/1710 will redirect to http://www.ubuntu.com-pr-3059.run.demo.haus/desktop

I've also fixed the telco redirects:
http://www.ubuntu.com-pr-3059.run.demo.haus/telco goes to http://www.ubuntu.com-pr-3059.run.demo.haus/telecommunications
http://www.ubuntu.com-pr-3059.run.demo.haus/telcos goes to http://www.ubuntu.com-pr-3059.run.demo.haus/telecommunications
