### ISSUE TITLE
Update the version of the UP2 IoT Grove server install page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#3070]
I assume it will work and we should promote the latest LTS of the server. We should change the recommended version of Ubuntu server to 18.04:
![screenshot-2018-4-26 install ubuntu server on an up squared iot grove development kit ubuntu](https://user-images.githubusercontent.com/1413534/39300861-067911a6-4945-11e8-8c4f-353defc2be01.png)

**Comment by pmahnke** [comment]
it will, we need to wait for https://downloads.up-community.org/ to have a new image

**Comment by pmahnke** [comment]
@anthonydillon I have spoken to @caldav, he will tell us, or the community when an update is ready.  closing for now.
