### ISSUE TITLE
Contingency 18.04 takeover - Build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3085]
Breif with copy: https://docs.google.com/document/d/1MgypR5L-YWeIPvrokLKzcEElDWWVZ2O8vFnfyqG2e-U/edit

**Comment by anasereijo** [comment]
@steverydz 
background colour: #F7F7F7
image: [](https://assets.ubuntu.com/v1/1d2ab6ba-suru-background.png
)
