### ISSUE TITLE
Link broken for .torrent download of ubuntu server 18.04

### ISSUE THREAD

**Issue by it-libo-l10n** [canonical-websites/www.ubuntu.com#3088]
Link broken for .torrent file download of ubuntu server 18.04
Points to wrong file

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. We are just releasing a fix for this.

**Comment by anthonydillon** [comment]
The fix has been pushed live. Sorry for the inconvenience.

**Comment by it-libo-l10n** [comment]
Thank you :)
