### ISSUE TITLE
Ubuntu 16.04 download links not working

### ISSUE THREAD

**Issue by mathiasdevos** [canonical-websites/www.ubuntu.com#3092]
Since Ubuntu 18.4 has been added to the download page, the Ubuntu 16.04 download links on the alternative downloads page are not working anymore.

**Error**:
Not Found

The requested URL /16.04/ubuntu-16.04-desktop-amd64.iso.torrent was not found on this server.

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by anthonydillon** [comment]
Thank you very much for reporting this issue. The links have been updated and will be live shortly.

**Comment by anthonydillon** [comment]
The links should now be resolved.
