### ISSUE TITLE
No feedback mechanism for the Canonical Ltd ubuntu.com website.

### ISSUE THREAD

**Issue by TerryE** [canonical-websites/www.ubuntu.com#3095]
I am more than happy to give a contribution to Canonical with Paypal, but I object to paying £ to $ conversion charges to Paypal for a donation, so I haven't.  Surely local currency donations should be allowed?  And users should be allowed to vary the donation.  In my case I'd refer to give more.

But there isn't even a feedback form on the website -- that is whose scope is the website and not the Ubuntu OS itself -- where I can give this type of feedback.  This is an omission.

---
*Reported from: https://www.ubuntu.com/download/desktop/thank-you*

**Comment by pmahnke** [comment]
@TerryE sorry about paypal, we have plans to change that, but haven't had time yet.  Thanks for being willing to donate, that is much appreciated.

As for contacting the webteam, github is always fine, also on https://www.ubuntu.com/contact-us there is a form and the webmaster@canonical.com email that we do watch.

All the best,

Peter
VP, Web & Design

**Comment by TerryE** [comment]
@pmahnke Peter,  thanks for getting back to me.  The **Contact Us** link is (as you point out) on your standard footer, so this a "Close; not an issue" category, and I support your action.

You seem to be aware of the side issue: IMO in general, if you are seeking to maximise voluntary donations then you should make the process as simple and unconstrained for the donor: suggest $15, but don't insist 0 or 15; allow local currency donations.  I suspect the payback for putting the effort into addressing this will be quite short.  :smile:
