### ISSUE TITLE
Ubuntu 18.04 quick action menu doesn't contains short cut key to action

### ISSUE THREAD

**Issue by LaiHuanMin** [canonical-websites/www.ubuntu.com#3097]
Hello, I'm very happy that Ubuntu created a new amazing version 18.04. But there's something disappear in 18.04.   
When you working at a Chrome, you can tap alt+space combine key to invoke a sub quick action menu(like the menu in the picture), and In 16.04, I can just tap C key to close after I invoke alt+space. But in 18.04 version, there's no short cut key let me quickly to action, I only can move my cursor and close windows carefully.
I always working without mouse，and if there's no short cut key, it may be not very convenience for user. If there's a way to change short cut key to visible? like settings or sth? 
Thanks for your help!

![image](https://user-images.githubusercontent.com/24793529/39397675-dc914cf8-4b35-11e8-9989-6fa29beb4fb1.png)

---
*Reported from: https://www.ubuntu.com/community*

**Comment by anthonydillon** [comment]
Sorry to hear you are having a problem with missing short keys in 18.04. Unfortunately we cannot provide support for Ubuntu on this project as this is for the website.

If you could report an bug on Ubuntu at https://bugs.launchpad.net/ubuntu or ask your question on askubuntu.com you should receive a quick response.
