### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by AlanJAS** [canonical-websites/www.ubuntu.com#3098]
## Summary
Due to the growing popularity of Ubuntu, it's necessary provide a site in the language of each community.

## Current and expected result

Current: I only found a Chinese version at cn.ubuntu.com
Expected: See a translated version of the site in the system/browser base language.

**Comment by steverydz** [comment]
@AlanJAS Thanks for taking the time to file an issue. This will be discussed when we plan our road map.

**Comment by Rodhos** [comment]
Any updates?

**Comment by Rodhos** [comment]
Where can I find the roadmap? Because this site seems deprecated:
https://wiki.ubuntu.com/Roadmaps

**Comment by pmahnke** [comment]
@Rodhos sorry, @steverydz answered slightly incorrectly.  We have no plans or resources to localise ubuntu.com.  We do have a cn.u.c and jp.u.c site that are much smaller and more evergreen versions of www.u.c, but we likely will never have the resource to do more than minor localisation and translation.

That said, we have started doing some one off content for french and german languages that can be see on the homepage if your browser is set to one of these languages.

Sorry,

Peter

**Comment by fitojb** [comment]
> We have no plans _or resources_ to localise ubuntu.com

Yes, you do have resources, @pmahnke . They (us) are all here: https://translations.launchpad.net/+groups/ubuntu-translators/

**Comment by yarons** [comment]
@fitojb the resources are from i18n perspective, if you can handle such a task which requires a pretty basic knowledge of python/flask and i18n then you can probably go ahead and create a PR with all the required changes for i18n, later on we'll have to choose a localization platform (I'm sorry but I think Launchpad is falling behind the curve) and let all the resources you mentioned to join the effort.
