### ISSUE TITLE
Privacy notices - Contact Privacy Notice - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3123]
Copydoc: https://docs.google.com/document/d/1kQmhTCRSnx05oYEFcNr0Dq7UUFrznq-GvQlRxvNAZ9s/edit?usp=sharing_eil&ts=5af1c29d

**Comment by frankiegranato** [comment]
@steverydz   Katherine has given us this last outstanding copydoc: https://docs.google.com/document/d/1kQmhTCRSnx05oYEFcNr0Dq7UUFrznq-GvQlRxvNAZ9s/edit?usp=sharing_eil&ts=5af1c29d so we should be good to go :-)
