### ISSUE TITLE
Consent: Update Consent checkbox texts and privacy policy texts - Build 

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3124]

**Comment by frankiegranato** [comment]
@steverydz  please use the text as they appear in this "Consent texts" copydoc: https://docs.google.com/document/d/1mTubEW_aq9ncckjYFBOOH2NIqee-cIPjPf_R2_I_REs/edit#

**Comment by frankiegranato** [comment]
For ubuntu.com, the following pages have forms in them that need updating with the GDPR consent text:
https://www.ubuntu.com/legal/terms-and-policies/contact-us
http://www.ubuntu.com/cloud/contact-us 
https://docs.google.com/document/d/10lo3O2TKiR-cc48CqhH3Ghak0xZQaP2n4YthDtdIXpo/edit# 
https://www.ubuntu.com/server/contact-us
https://www.ubuntu.com/containers/contact-us?product=containers-overview
https://www.ubuntu.com/internet-of-things/contact-us
https://www.ubuntu.com/core/contact-us?product=core-overview
https://www.ubuntu.com/support/contact-us

IoT newsletter sign up in contextual footer: 
https://www.ubuntu.com/internet-of-things/digital-signage 
https://www.ubuntu.com/internet-of-things/gateways
https://www.ubuntu.com/internet-of-things/robotics
https://www.ubuntu.com/internet-of-things/appstore

Cloud Newsletter sign up in contextual footer: 
https://www.ubuntu.com/cloud/public-cloud
https://www.ubuntu.com/cloud/storage
https://www.ubuntu.com/cloud/foundation-cloud
https://www.ubuntu.com/telecommunications

Please remember to update copydocs where necessary.

**Comment by frankiegranato** [comment]
By the way, there are website that need Consent updates. They are listed below.

I have filed them under this new 'GDPR updates to other sites' epic: https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/558

https://maas.io/contact-us (https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/555)
https://partners.ubuntu.com/contact-us (https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/556)
https://shop.canonical.com/contact_us.php (https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/557)

No consent text needed, but some links need to be updated on this site: 
https://community.ubuntu.com/about (https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/554)

Sorry - I know the Repos aren't correct!
