### ISSUE TITLE
/server partner logos failed to load - Build

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3131]
<img width="1104" alt="screen shot 2018-05-09 at 13 26 43" src="https://user-images.githubusercontent.com/36884067/39814531-a2510150-538c-11e8-8b07-bce29eba5656.png">

**Comment by pmahnke** [comment]
@anasereijo - I think this was a blip when partners.ubuntu.com was down or busy. It all seems fine now
