### ISSUE TITLE
Searching on conjure-up.io never returns any results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3140]
(This issue concerns conjure-up.io, not www.ubuntu.com, but the link in conjure-up.io’s footer sent me here.)

1\. Go to [the Conjure-up documentation](https://docs.conjure-up.io/2.4.0/en/).
2\. In the “Search conjure-up docs” field, search for anything that you know should return results: for example, “[neutron](https://docs.ubuntu.com/search?q=neutron&domain=docs.conjure-up.io)”, “[summoning](https://docs.ubuntu.com/search?q=summoning&domain=docs.conjure-up.io)”, or “[conjure-up](https://docs.ubuntu.com/search?q=conjure-up&domain=docs.conjure-up.io)”

What happens: “Your search for 'conjure-up' returned 0 results”

What should happen: You get search results.

**Comment by pmahnke** [comment]
@nottrobin I can't even get staging to build... the css looks messed up on my computer as well... can you take a quick look?

**Comment by nottrobin** [comment]
Search now works - e.g. https://www.ubuntu.com/search?q=conjure-up&domain=docs.conjure-up.io
