### ISSUE TITLE
Search results pages are returned in search results

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3142]
1\. Go to ubuntu.com.
2\. [Search for “irc”](https://www.ubuntu.com/search?q=irc).

What happens: The first two results are search results pages, and [the second one](https://jujucharms.com/q/?requires=irc) is literally a page saying “Your search for irc returned 0 results”.

This issue is not about the fact that the results are from jujucharms.com: that is #2858. This issue is that search results pages should not be returned as results by _any_ search engine we control (and nor, if we can help it, by other search engines).

Two main reasons for this:

- Someone following a link on a search results page will likely be frustrated if it turns out to be just another search results page, not actual information.

- There are an infinite number of search results pages, so making them indexable decreases the chance that real pages will be indexed. [Google’s Webmaster guidelines](https://support.google.com/webmasters/answer/35769) say: “Use the robots.txt file on your web server to manage your crawling budget by preventing crawling of infinite spaces such as search result pages.”

---
*Reported from: https://www.ubuntu.com/search?q=irc*

**Comment by nottrobin** [comment]
Yep that's pretty trivial to do, we just need to add `<meta name="robots" content="noindex" />` to the search templates on www.ubuntu.com and docs.ubuntu.com.
