### ISSUE TITLE
Test Insights homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3149]
We have launched  a new and improved "Featured posts" section on the insights homepage. We want to measure the success of that new improved homepage. However, to do that we must first get a baseline reading of the previous version of the homepage to test against improved version.
We need to:
Decide if we are going to A/B test old and new versions
Alternatively, ask David Calle to get a manual reading of the previous featured posts

**Comment by pmahnke** [comment]
closing as this site is gone.
