### ISSUE TITLE
non-HTTPS

### ISSUE THREAD

**Issue by Pavel-Novikov** [canonical-websites/www.ubuntu.com#3151]
You have too much non-HTTPS links. for example http://releases.ubuntu.com/

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
@Pavel-Novikov thanks for filing an issue.

We cannot current make releases https or we will break all the mirrors.

We are looking at ways around this, but it is very complicated to explain here.

Also, this site is for www.ubuntu.com issues, so closing.
