### ISSUE TITLE
Lubuntu has evolved

### ISSUE THREAD

**Issue by tsimonq2** [canonical-websites/www.ubuntu.com#3161]
We have a new logo:

![New logo](https://pbs.twimg.com/profile_images/965283049968689152/8iy34E_U_200x200.jpg)

[Our website is now HTTPS.](https://lubuntu.me/)

A more accurate description of Lubuntu is now:

"Lubuntu is a light, fast, and modern Ubuntu flavor using LXQt as its default desktop environment. Lubuntu used to use LXDE as its default desktop environment."

Source for the LXQt switch: https://lubuntu.me/this-week-in-lubuntu-development-5/

**Comment by pmahnke** [comment]
@tsimonq2 do you have an svg version of you logo?

**Comment by pmahnke** [comment]
actually, I think we have one - https://assets.ubuntu.com/v1/600c73c4-Lubuntu.svg

**Comment by tsimonq2** [comment]
Actually, the logo should change as well.

I'll ask Lubuntu's artwork team to give me an SVG.

**Comment by wxl** [comment]
While I appreciate the changes to the description and link, the one glaringly obvious change that did not happen is the one to the logo. Can we please get that fixed?

**Comment by wxl** [comment]
@pmahnke thanks for the fix but the logo appears tiny relative to the other flavors. My guess is the reason is the fact it's not an SVG as requested. Can I email one to you? Where?

**Comment by anthonydillon** [comment]
@wxl thanks for pointing this issue out. Turns out all other images were mis-styled die to a SVG selector. I have mixed that and it should be live soon.

https://github.com/canonical-web-and-design/ubuntu.com/pull/6266

**Comment by wxl** [comment]
@anthonydillon I see your change has been implemented and seems to be live, but I don't see anywhere in that commit where the Lubuntu image has changed. It's still a PNG, so still apparently problematic. Again, I ask: is there somewhere I can email an SVG?

**Comment by anthonydillon** [comment]
@wxl I thought that now the logos are all the same size this would resolve the need for an SVG but we are happy to update the logo to an SVG. Please feel free to email me at anthony.dillon@canonical.com and I will ensure it is updated on the site.

**Comment by wxl** [comment]
@anthonydillon Sent! Thanks!

**Comment by anthonydillon** [comment]
The new SVG logo is now live

**Comment by wxl** [comment]
@anthonydillon Looks lovely, thanks! The only one other little itsy bitsy gripe I have is that the link to our website should ideally be HTTP*S*. I see Kylin suffers the same fate.
