### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#3175]
Under "BOOTSTACK FULLY MANAGED CLOUD CUSTOMERS" the Peer1 logo isn't working.

---
*Reported from: https://www.ubuntu.com/cloud/managed-cloud*

**Comment by pmahnke** [comment]
@cjohnston1158

are you still seeing this?

I see it

![image](https://user-images.githubusercontent.com/441217/40106250-268ac5a4-58ed-11e8-9512-ae4524685fbf.png)

**Comment by cjohnston1158** [comment]
Looked at this with Peter and Will, believe that there is something that corrupted the image on assets.

I'm still seeing this issue.
