### ISSUE TITLE
Not clear why “Resources” exists

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3180]
1\. Go to [ubuntu.com](https://www.ubuntu.com/).
2\. Try to guess what “Resources” will contain, before you click it.
3\. Try to guess what “Resources” is, after you click it.

What happens:

2\. “Resources” is too general a term to guess what it might contain. For example, [support sources](https://www.ubuntu.com/support/community-support) are sometimes referred to as “resources”, but it doesn’t contain those. And [downloadable logos](https://design.ubuntu.com/downloads/) could be “resources”, too, but it doesn’t contain those. When you hover over “Resources”, a balloon appears saying “Overview”, which is even more mysterious.

3\. The only clue is the text “Selected resources from blog.ubuntu.com”. There’s no explanation of how they are selected, or why they aren’t just a filter on blog.ubuntu.com itself.

What should happen: either
- the section does not exist, or
- it has a name and text that clarifies the reason for selecting some posts and not others.

(Apologies if this is a long-running debate I’m not aware of, or if we have data showing that most people really can guess these things.)

---
*Reported from: https://www.ubuntu.com/resources?content=case-studies

**Comment by steverydz** [comment]
@matthewpaulthomas Thank you. We'll hopefully have some time to look at this soon.

**Comment by matthewpaulthomas** [comment]
This is fixed with the new navigation. The only mention of “Resources” now is a heading in the footer, where the various resource types are listed.
