### ISSUE TITLE
Https for downloads

### ISSUE THREAD

**Issue by florian2833z** [canonical-websites/www.ubuntu.com#3182]
Hello,

Please make https available for you download page
http://releases.ubuntu.com/18.04/ubuntu-18.04-live-server-amd64.iso

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by pmahnke** [comment]
@florian2833z  thanks for filing an issue.

We cannot currently make releases https or we will break all the mirrors.

We are looking at ways around this, but it is very complicated to explain here.

Also, this site is for www.ubuntu.com issues, so closing.

**Comment by pmahnke** [comment]
This tutorial explains how to verify the download - https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu
