### ISSUE TITLE
Grey-bar and orange-bar menus can be open simultaneously

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3192]
1\. Go to ubuntu.com.
2\. In the grey bar at the top, click “More”.
3\. In the orange bar below, hover over “Support” or “Resources”.

What happens:

![ubuntu com-menus-overlap](https://user-images.githubusercontent.com/19801137/40278182-3a73c43c-5c24-11e8-908c-676866cf2add.png)

What should happen:
- the grey bar items don’t have any menus, or
- the orange bar items don’t have any menus, or
- whenever a menu opens, any other open menus close.

---
*Reported from: https://www.ubuntu.com/*

**Comment by steverydz** [comment]
@matthewpaulthomas Thank you. This is something we'll likely look at once the beta site is live.

**Comment by matthewpaulthomas** [comment]
The same happens with the new navigation, reported as #4436.
