### ISSUE TITLE
Build notification for beta

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3198]
![feedbackbutton](https://user-images.githubusercontent.com/36884067/41467514-b84ff3c4-709e-11e8-9b9f-941e85ab0c65.jpg)
![Design](https://user-images.githubusercontent.com/36884067/40844616-51cc6d82-65ac-11e8-98e6-6ca5375f3fab.jpg)
![Design](https://user-images.githubusercontent.com/36884067/40844618-539afe8a-65ac-11e8-889b-184aa0c9f83d.jpg)

**Comment by frankiegranato** [comment]
The design card: https://app.zenhub.com/workspace/o/ubuntudesign/www.ubuntu.com-design/issues/145

**Comment by anasereijo** [comment]
@steverydz this issue is not blocked any more. All designs are attached to this ticket.

- Feedback button:
our usual vanilla button style but with #333 background colour. 

- Modal: please check this link https://vanilla-framework.github.io/vanilla-framework/examples/patterns/modal/ please add a hr below the title

thanks

**Comment by steverydz** [comment]
@anasereijo Are the coloured icons on the asset server?

**Comment by steverydz** [comment]
@anasereijo How do you want the two buttons to work on mobile?

**Comment by anasereijo** [comment]
@steverydz sorry forgot to send you the links:
https://assets.ubuntu.com/v1/d20e84ba-Helpful-no.svg
https://assets.ubuntu.com/v1/e03275bf-Helpful-unsure.svg
https://assets.ubuntu.com/v1/04f445ea-Helpful-yes.svg

**Comment by anasereijo** [comment]
@steverydz mobile design:

![mobile feedback](https://user-images.githubusercontent.com/36884067/41467391-44fcb4b6-709e-11e8-85cb-3e745a3f4c26.jpg)

**Comment by frankiegranato** [comment]
I think this is designed & built so I'm closing this issue.
