### ISSUE TITLE
Website partner  logo need fix

### ISSUE THREAD

**Issue by nicoande** [canonical-websites/www.ubuntu.com#3204]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

The logos doesn't load

## Process

juste when on the ubuntu server page and scrolled down

**Comment by shivjoshi1996** [comment]
Hi, thanks for filing a bug. Could you please link the URL of the page you experienced this on? As they are loading fine for me on https://www.ubuntu.com/server. It would be great if you could double check, just in case it was a one-off. Thank you.

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
