### ISSUE TITLE
Error al iniciar sesión.

### ISSUE THREAD

**Issue by GabeSabe** [canonical-websites/www.ubuntu.com#3241]
Hay un bug al iniciar sesión en UBUNTU 18.4lts, al ingresar la contraseña, si tienes un error y la escribes mal, cuando te pida de nuevo la contraseña esta no iniciara a pesar de que la contraseña sea correcta. 
---
*Reported from: https://www.ubuntu.com/community*

**Comment by anthonydillon** [comment]
Closing due to lack of feedback. Please comment and reopen.
