### ISSUE TITLE
Clicking 'you can continue to the download' doesn't go to the download page

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/www.ubuntu.com#3245]
The 'you can continue to the download button' on the Contribute page (linked at the bottom of this Issue description) actually goes to the 'Thank you for your contribution' [page](https://www.ubuntu.com/download/desktop/thank-you?country=GB&version=&architecture=) which doesn't have links to downloads.

This is because the Contribute page can be reached ( by direct URL or from the link in the top-right of community.ubuntu.com ) without passing, e.g., `?version=18.04&architecture=amd64` in the URL.

Related to #3244 

In fact, the 'you can continue to the download' link shouldn't appear on Donate page by default (if I'm just going to that page to donate, I don't want a download, and having that option (phrased as it is) doesn't even make sense to read, because it assumes that you're coming to download), but only if `version` and `architecture` are passed to it.

---
*Reported from: https://www.ubuntu.com/download/desktop/contribute?_ga=2.52784416.984956362.1525128778-629454919.1504091901*

**Comment by steverydz** [comment]
Thank you. This has been fixed as part in https://github.com/canonical-websites/www.ubuntu.com/pull/3250
