### ISSUE TITLE
Build new takeover

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3254]
Dependent on https://app.zenhub.com/workspace/o/ubuntudesign/www.ubuntu.com-design/issues/148

**Comment by anasereijo** [comment]
Hi @steverydz you can see final designs here: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/148#issuecomment-395348622

- gradient
 background-image: linear-gradient(-36deg, #94310F 0%, rgba(233,84,32,0.90) 100%);

- logo
https://assets.ubuntu.com/v1/c54da84b-451-Research-NEG.png

- graph (please anchor to the left side)
https://assets.ubuntu.com/v1/13fdbc5b-graph.png

**Comment by frankiegranato** [comment]
@steverydz  please aim to launch this takeover at 10am (or earlier) on Wednesday 13th. 

We need to alert Rebecca Craddick as soon as it goes live (rebecca.cradick@canonical.com). Rebecca is going to launch the rest of her launch campaign once she's seen the live takeover (and reassured herself that all the links work etc).

**Comment by frankiegranato** [comment]
Hi Steve, The copy for the takeover is finalised. Please find it here: https://docs.google.com/document/d/1trccDAaYcapXudN-pvNKcUciRceIZhFA14uNSG3u8dg/edit?ts=5b0f2252

**Comment by kasiag** [comment]
@steverydz also, because this change of copy comes in after the design was finalised (with previous copy) by @anasereijo let's make sure that both Ana and @frankiegranato sign this off before pushing live
