### ISSUE TITLE
Beta nav - Styling updates

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3257]
Here are the copydocs that represent the drop down menus: 
Enterprise: https://drive.google.com/open?id=1YBdQvLuqEpEQr_QqyycxMhZr4OaLapMlNJyYKCmPJsQ
Community: https://drive.google.com/open?id=1TgsBJdGgsP4KrGiz5kU5QYkdGSlKqhAVnZGnCJgshYY
Developer: https://drive.google.com/open?id=1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY

**Quick fixes:**

- Remove login and company links from global nav (@pmahnke is this confirmed?)

- Close the drop-down menu when clicking outside

- Global Nav to be 32px height

- Add body overlay when the drop-down opens (color: #111111 40% opacity)

- Remove link focus (doted outline)

- Enterprise tab
   * change the sectors background to white and add a keyline to separate it from the section above
   * add keylines to separate links

![enterprise](https://user-images.githubusercontent.com/36884067/40727412-be86026e-641f-11e8-8918-a34d213442ec.jpg)

- Developer tab
   * change the resources background to white and add a keyline to separate it from the section.

![developer](https://user-images.githubusercontent.com/36884067/40727706-59852c68-6420-11e8-99db-84f54dd369c5.jpg)

- Download tab
   * change the light grey background to white and add a keyline to separate it from the section. 

![download](https://user-images.githubusercontent.com/36884067/40727785-8b8ba3c2-6420-11e8-9d3a-82acf1a1236f.jpg)

- Products tab
   * change body font from 16px to 14px
   *  stack logos (to look like what we have on Enterprise)
   * add line to separate matrix from bottom section
   * change bottom section background 262626
   * change bottom section copy to F7F7F7
   * remove resources divider line

![products](https://user-images.githubusercontent.com/36884067/40730925-c7ab8244-6427-11e8-8064-5219bf9b0f65.jpg)

**Comment by anasereijo** [comment]
@steverydz please see changes list here: https://github.com/ubuntudesign/web-squad/issues/588

**Comment by steverydz** [comment]
@anasereijo @frankiegranato Didn't we agree to keep the menu toggle on click/touch?
