### ISSUE TITLE
Search bar on MAAS ebook page wonky

### ISSUE THREAD

**Issue by squidsoup** [canonical-websites/www.ubuntu.com#3259]
## Summary

The search input is not rendering correctly on the MAAS eBook page, and doesn't appear to work.

## Process

Visit https://pages.ubuntu.com/eBook-MAAS.html

## Current and expected result

Search input is wonky (Chrome Version 66.0.3359.181 (Official Build) (64-bit) OSX).
Search input should be less wonky.

## Screenshot

![image](https://user-images.githubusercontent.com/130286/40952665-3f1f0cf4-68d0-11e8-8db9-2de36f099170.png)

**Comment by steverydz** [comment]
Thanks. We'll look at this in an upcoming iteration.
