### ISSUE TITLE
design.ubuntu.com/brand -  fix laptop image - DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3266]
## Summary

Can you please fix the laptop image as it is looking stretched.

## Screenshot

![Screen Shot 2018-06-07 at 17.24.02.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/2d6b2532-8962-4d3d-ab52-7bf7364da42d)

**Comment by steverydz** [comment]
@anasereijo Closing this as I've recreated in the correct repo: https://github.com/canonical-websites/design.ubuntu.com/issues/113
