### ISSUE TITLE
beta updates: build updated developer menu 

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3279]
Copy doc: https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit

**Comment by anthonydillon** [comment]
Copy doc: https://docs.google.com/document/d/1JzZPBydcdyV96Hu4xRpa7VDU_WREr6gb05bL7GlQaYY/edit
