### ISSUE TITLE
beta updates: login menu build

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3286]
copy doc: https://docs.google.com/document/d/1NIOGd2udYcjQ1xoKGR2UIMruWLXMIRf6R3aZwD7zk2o/edit?ts=5b1560a8

design issue: #3287

**Comment by anasereijo** [comment]
copy doc: https://docs.google.com/document/d/1NIOGd2udYcjQ1xoKGR2UIMruWLXMIRf6R3aZwD7zk2o/edit?ts=5b1560a8

**Comment by anasereijo** [comment]
**final design:** 

![login](https://user-images.githubusercontent.com/36884067/41539970-f2a95a64-7306-11e8-9cae-a57458b09054.jpg)

**Icons:** (size 32px by 32px)
- Ubuntu Advantage https://assets.ubuntu.com/v1/c5cb0f8e-picto-ubuntu.svg
- Landscape https://assets.ubuntu.com/v1/4964d639-landscape-logo.svg
- Livepatch https://assets.ubuntu.com/v1/3c1de878-canonical-logo.png
- Launchpad https://assets.ubuntu.com/v1/6b318257-launchpad-icon.png
- Snapcraft https://assets.ubuntu.com/v1/82dc2022-snapcraft-primary-icon.svg
- JAAS https://assets.ubuntu.com/v1/31c507a5-logo-juju-icon.svg

**Customer portals title**
same style as "other websites" title on Products dropdown: `<h5 class="p-muted-heading">`

**Links:**
links should be `.p-link--inverted `
