### ISSUE TITLE
beta updates: login menu design

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3287]
Copydoc: https://docs.google.com/document/d/1NIOGd2udYcjQ1xoKGR2UIMruWLXMIRf6R3aZwD7zk2o/edit?ts=5b1560a8

Pls note: once you are logged in 1 place, you are logged in everywhere

**Comment by anasereijo** [comment]
![Login.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/8be7efe6-fb8a-4b46-adff-666b153badac)

**Comment by anasereijo** [comment]
![Login.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/aac9a343-adcf-4377-99f7-69bb08ba9841)

**Comment by anasereijo** [comment]
@frankiegranato updated version:
![login](https://user-images.githubusercontent.com/36884067/41412084-c5d4e0a4-6fd6-11e8-8b59-f2ab92d868d1.jpg)

**Comment by spencerbygraves** [comment]
@anasereijo let's keep the title style consistent with the other pages. Thanks.

**Comment by anasereijo** [comment]
Final version:

![login 2](https://user-images.githubusercontent.com/36884067/41462285-45e3a790-708a-11e8-86d8-1deb5a7120d8.jpg)
