### ISSUE TITLE
Live News Feed Failed To Load

### ISSUE THREAD

**Issue by thegabeway** [canonical-websites/www.ubuntu.com#3298]
## Summary

[Live News Feed Failed To Load] 

## Process

[on page load]

## Current and expected result

[see above]

**Comment by anthonydillon** [comment]
Hello, Which URL/page did you spot this failure?

**Comment by thegabeway** [comment]
Www.ubuntu.com

**Comment by anthonydillon** [comment]
Thank you, do you still see the issue? I can not replicate it.

**Comment by thegabeway** [comment]
No and I can't replicate it, either. Thanks!
