### ISSUE TITLE
Updates to /plans-and-pricing page (from C Johnston)

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3306]
As per copydoc: https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#

**Comment by frankiegranato** [comment]
If the comments in the doc look unresolved, please talked to me before completing this work @steverydz

**Comment by shivjoshi1996** [comment]
Dupe of https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/3437
