### ISSUE TITLE
Beta: Build Kubernetes features page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#3361]
Copy doc: https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit

**Comment by frankiegranato** [comment]
Grafana dashboard asset from Kevin Monroe: 

![k8s-telegraf-light.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/8b512bb4-1f9f-4596-9c71-8029ee01be7b)
