### ISSUE TITLE
Beta: Build Kubernetes install page

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#3362]
Copy doc: https://docs.google.com/document/d/1oiD6UUomf2daZitS3UOosujYBXPbiOMzPtXVZBq-ph0/edit

**Comment by frankiegranato** [comment]
@anthonydillon & @steverydz This page is ready for you guys to build. 
@anasereijo Ana you can review and tweak after it's built or before - what ever works best with timings.

**Comment by frankiegranato** [comment]
@anthonydillon Peter and I just made a few more updates to the doc. just fyi :-)
