### ISSUE TITLE
Partner logo failed to load (ubuntu.com/server)

### ISSUE THREAD

**Issue by masiama** [canonical-websites/www.ubuntu.com#3373]
## Summary

On https://www.ubuntu.com/server in section "Deploys anywhere" partner logo failed to load

## Current and expected result

"Error:Our partner logos failed to load. Please report this bug and our team will fix the problem as soon as possible."

## Screenshot

![screen shot 2018-06-19 at 01 50 26](https://user-images.githubusercontent.com/14037820/41566199-302c2734-7363-11e8-98b2-198bb3021a7f.jpg)

**Comment by anthonydillon** [comment]
Thank you very much for taking the time to file this issue.

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
