### ISSUE TITLE
The styling looks a bit strange on this card.

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3377]
The styling looks a bit strange on this card. I feel like I've not seen this style before. It must have happened because of a Vanilla update to the site. Can you take a look please? 
![weird-card-styling](https://user-images.githubusercontent.com/17002826/41599183-4eb9b416-73ca-11e8-92be-51c041c3cbbb.png)

---
*Reported from: https://beta.ubuntu.com/public-cloud*

**Comment by anasereijo** [comment]
I think we should use the new card style I created.
(you can see it on openstack/storage page)

See a mockup below:
![Screen-Shot-2018-06-27-at-10.36.22.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/c1bcfa8e-0d2f-43be-b71c-05b51d8b1267)

**Comment by anasereijo** [comment]
@steverydz just noticed that we have another card style for the same page but on https://www.ubuntu.com/cloud/public-cloud maybe we should change on both sites?

**Comment by steverydz** [comment]
@anasereijo We really should be making changes to the live ubuntu.com at this point unless they are critical as it will add complexity to getting the beta work live.
