### ISSUE TITLE
Resources are not loading

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#3382]
The resources page is failing to load or process the feed from insights. 

![screenshot-2018-6-20 resources ubuntu](https://user-images.githubusercontent.com/1413534/41654626-f584fd7a-7481-11e8-97ee-75141b5f876a.png)

---
*Reported from: https://www.ubuntu.com/resources*

**Comment by nottrobin** [comment]
Duplicate of #3801
