### ISSUE TITLE
Beta update: Mobile global nav - UX

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3390]
I think we must look at the mobile global nav as a whole so I created issues (UX, Design and Dev).
I can work with you on this UX issue to find out what we should include on mobile or not and re-think the positioning on the page.

**Comment by frankiegranato** [comment]
Here is my sketch of how it should work (style to be the same as on current site![Screen Shot 2018-06-21 at 15.46.03.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/fcba948d-5188-45bf-988b-7e094422882b)):  ![footer menu sketch.JPG](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/ae9dcb24-8165-4554-acbb-9b3bf779a4e8)

**Comment by frankiegranato** [comment]
It should look and work  like the footer menu on u.com: ![Screen Shot 2018-06-21 at 15.46.03.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/a3cfb29f-4c86-4ab1-8ab7-b96c9a95c58a)
