### ISSUE TITLE
Footer > newsletter sign up: poor feedback when entering incorrect email format (Chrome/Mac)

### ISSUE THREAD

**Issue by ghost** [canonical-websites/www.ubuntu.com#344]
## Context

It's not a regression from live (same issue there) but I think it's pretty bad experience
## Process

1) On Cloud pages - no verification of email address input. You can enter whatever and you get to thank you page

2) on pages with Devices newsletter (phone, desktop, tablet, iot) incorrect input is rejected but it doesn't tell you why
## Expected result

Incorrect email format should not be accepted and user should get the message explaining what went wrong

**Comment by magdalena-mirowicz** [comment]
@barrymcgee not sure if this is live? I checked cloud and it looks fine now, on phone you still don't know why the input is incorrect

**Comment by Caleb-Ellis** [comment]
@deadlight those footer newsletter signup forms don't exist anymore. Is it safe to close this?

**Comment by deadlight** [comment]
@Caleb-Ellis yeah. Closing.

If anyone thinks that this is in error, please re-open and clarify.
