### ISSUE TITLE
Three different claims of which Ubuntu versions are covered by Livepatch

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3447]
[The code for ubuntu.com/support](https://github.com/canonical-websites/www.ubuntu.com/blob/master/templates/support/index.html) contains:
> `Canonical Livepatch Service, which enables you to apply kernel fixes without restarting your Ubuntu {{lts_release_full}} systems.`

This gets rendered as:
> Canonical Livepatch Service, which enables you to apply kernel fixes without restarting your Ubuntu 18.04 LTS systems.

But further down [the same page](https://www.ubuntu.com/support):
> the Canonical Livepatch Service enables you to apply critical kernel security fixes to your Ubuntu 16.04 LTS system without rebooting

Meanwhile, [the Livepatch site itself](https://auth.livepatch.canonical.com/) says:
> The service covers standard Canonical 64-bit x86 kernels on 14.04 LTS and 16.04 LTS.

What should happen: All places where Livepatch coverage is described should list the same versions.

One way of fixing this might be to create and use a `{{livepatch_releases}}` variable so that the list of releases can be maintained in one place.

---
*Reported from: https://www.ubuntu.com/support*

**Comment by anthonydillon** [comment]
Asked Brad Figg for the correct content.

**Comment by pmahnke** [comment]
@matthewpaulthomas I will fix for u.c, but can you update with the livepatch folks? - https://bugs.launchpad.net/livepatch-auth ... I am going to say

*top* 

>  Canonical Livepatch Service, which enables you to apply critical kernel fixes without restarting your Ubuntu systems.

*bottom*

> Canonical Livepatch Service enables you to apply critical kernel security fixes to your Ubuntu 16.04 LTS, Ubuntu 18.04 LTS and patched Ubuntu 14.04 LTS systems without rebooting, and it reduces downtime while maintaining compliance and security.

**Comment by matthewpaulthomas** [comment]
It’s a little unfortunate that the only specific version mentioned now is 14.04 … but that’s an improvement at least.

> @matthewpaulthomas I will fix for u.c, but can you update with the livepatch folks?

I’ve reported the livepatch-auth issue as [LP#1779668](https://launchpad.net/bugs/1779668).

**Comment by Roadmaster** [comment]
https://launchpad.net/bugs/1779668 is now fixed (check http://auth.livepatch.canonical.com/).
Cheers!
