### ISSUE TITLE
Takeover build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3497]

**Comment by anasereijo** [comment]
@steverydz this is now ready to build.
- check #152 for visuals
- you can re-use the takeover we have now - the only changes are:
  - [copy](https://docs.google.com/document/d/1cwtp4tRnf12g9EalvllPCzSZX8XgJ2bLk3MpZYaKBjc/edit)
  - gradient: 
`/* Background: */ background-image: linear-gradient(-36deg, #111111 0%, rgba(38,38,38,0.90) 100%);`

**Comment by steverydz** [comment]
Updating with correct issue: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/152
