### ISSUE TITLE
/Kubernetes/contact-us - Fix contact us - DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3528]
please fix on all contact us pages

![screencapture-beta-staging-ubuntu-kubernetes-contact-us-2018-07-03-12_06_14](https://user-images.githubusercontent.com/36884067/42216461-c6cf76bc-7eb9-11e8-85e2-b5b95f24846f.jpg)

---
*Reported from: https://beta.staging.ubuntu.com/kubernetes/contact-us?product=kubernetes-explorer*

**Comment by steverydz** [comment]
@anasereijo We don't have borders on fieldsets in Vanilla - is this something we want to add?
https://docs.vanillaframework.io/en/base/forms

**Comment by anasereijo** [comment]
@steverydz as discussed, please make the border `border: 1px solid #cdcdcd;`
