### ISSUE TITLE
/kubernetes overview - contextual footer link content not working- DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3539]
Try LXD link not working:

<img width="1336" alt="screen shot 2018-07-03 at 14 20 13" src="https://user-images.githubusercontent.com/36884067/42222252-842f332a-7ecc-11e8-9e09-9bd9e9df08c6.png">

---
*Reported from: https://beta.staging.ubuntu.com/kubernetes*

**Comment by steverydz** [comment]
This is an issue with linuxcontainers https://github.com/lxc/linuxcontainers.org/issues/315
