### ISSUE TITLE
/kubernetes/features - broken link - DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3540]
link not working on "Kubernetes fits perfectly on top of OpenStack, and VMware and MAAS Bare Metal" section : Learn more about Kubeflow ›

<img width="1251" alt="screen shot 2018-07-03 at 14 27 36" src="https://user-images.githubusercontent.com/36884067/42222512-5635037c-7ecd-11e8-9842-413f7c8af6a0.png">

---
*Reported from: https://beta.staging.ubuntu.com/kubernetes/features*

**Comment by steverydz** [comment]
This is as the [copy doc](https://docs.google.com/document/d/1mEOBW4pfsWJqTLm9Pn9myKtaslD-QB2RvUKcNQ52bXU/edit). This page will need to be created before we go live.
