### ISSUE TITLE
/server - MOBILE - UX & DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3561]
I think we should remove the graph (and it's title) from the mobile version as it is too small to read.
@frankiegranato what do you think from a UX perspective?

<img width="1050" alt="screen shot 2018-07-03 at 16 03 32" src="https://user-images.githubusercontent.com/36884067/42228264-6fcd1dc0-7edb-11e8-8abe-590073061fe0.png">

---
*Reported from: https://beta.staging.ubuntu.com/server*

**Comment by anasereijo** [comment]
I was just thinking about this because on my mobile phone we can't see the graph properly but I reckon we can zoom in and also many people will have bigger screens anyway. That said maybe it's better to keep the graph. 
We just need to swap the order and have it below the h1 and body copy. 
FYI @frankiegranato @steverydz

**Comment by steverydz** [comment]
@anasereijo That change will reverse them on desktop as well due to how the grid system works

**Comment by anasereijo** [comment]
@steverydz ok, in that case, can we have a bit more space between the graph and h1?
