### ISSUE TITLE
Add new "GPL Enforcement" page - build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3592]
Add this page as per copydoc: https://docs.google.com/document/d/1knhlbP0tsoxjfX4SpDrP8_OdTuqKNRBL_zNDB70cXfs/edit#heading=h.lzl8jnlqgjx7

Please note: Rebekka Cradick will announce this "GPL Enforcement commitment" at 8am ET on July 16th so she thinks we should publish the page on 15th of July (however this is a sunday so I'm not sure how we'll do that - I'll double check with her). 
 
Url must be "ubuntu.com/legal/gpl-enforcement" (despite the location of the page within the IA)

**Comment by frankiegranato** [comment]
@steverydz I suppose we'll need to add this page to the beta.u.com as well as to u.com.  This announcement sounds quite important and I don't want to risk this page getting lost in-between the cracks. Sorry about the repetition of tasks.
Fyi @shivjoshi1996 @anthonydillon

**Comment by steverydz** [comment]
@frankiegranato Yes of course - like the other updates I'll wait til this has passed review then cherry pick the relevant commits into beta. That way there's less duplication of effort and less chance of conflicts.

**Comment by frankiegranato** [comment]
We need to put this page live  in the UK morning on 16th July.

**Comment by frankiegranato** [comment]
+1 from me on this page. The signpost page (/legal/terms-and-policies) has a few typos but I assume there is a seperate PR for that.

**Comment by frankiegranato** [comment]
@steverydz This work has been cancelled. Do not publish!
