### ISSUE TITLE
/openstack/consulting - fix MOBILE table - DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3649]
![screen-shot-2018-07-06-at-12 04 37](https://user-images.githubusercontent.com/36884067/42376013-83dd61d0-8115-11e8-93e6-70709993431a.jpg)

---
*Reported from: http://mongoose.staging.ubuntu.com/openstack/consulting*

**Comment by steverydz** [comment]
Fixed by https://github.com/canonical-websites/www.ubuntu.com/pull/3641
