### ISSUE TITLE
Telecominfraproject logo is too small on telcos page

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3654]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

The telecominfraproject logo is way too small on the telco page, you can't read the writing.

## Process

Go to http://mongoose.ubuntu.com/telecommunications and go down to the telco programs logos section. See that the logo is too small.

![Telcoimage.png](https://images.zenhubusercontent.com/59f357068a75884b90851560/36abb410-e5f9-4df0-9336-d2d3a6baea37)

**Comment by anasereijo** [comment]
@shivjoshi1996 thanks for checking this.
I just had a look and the [logo](https://assets.ubuntu.com/v1/eeae998a-telecominfraproject-logo.svg)  is an .svg so I think we need to ask a developer to make it bigger on the page. @steverydz can you please have a look? Thanks
