### ISSUE TITLE
/data-privacy-enquiry looks like the 'parent' page in the legal nav

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3689]
[ ] When you arrive from /legal to /legal/terms-and-policies only one 'child' page appears in the secondary nav (there should be 8 pages I think)
[ ] Also, when you are within a 'child' page of the /terms-and-policies section, (eg. /legal/dataprivacy) the data-privacy-enquiry page looks as if it is the 'parent' page in the secondary nav bar

See screen shots to help illustrate the problems
![nav-legal-bug-02](https://user-images.githubusercontent.com/17002826/42447314-506d7ac0-8371-11e8-86ed-3efe1e12f6ce.png)
![nav-legal-bug](https://user-images.githubusercontent.com/17002826/42447315-508f1c3e-8371-11e8-8138-3b239bd8a777.png)

---
*Reported from: https://www.ubuntu.com/legal/dataprivacy*

**Comment by pmahnke** [comment]
looks like the navigation.yaml is messed up
