### ISSUE TITLE
Top navigation broken between 786px and 800px

### ISSUE THREAD

**Issue by barrymcgee** [canonical-websites/www.ubuntu.com#3690]
## Summary

Layout of top navigation broken when screen width is between 786px and 800px

## Expected result

All items should stay on one line regardless of screen width

## Screenshot

<img width="874" alt="screen shot 2018-07-09 at 12 31 59" src="https://user-images.githubusercontent.com/505570/42448168-3b6e2ac2-8374-11e8-95de-ce4be3d39ceb.png">

**Comment by steverydz** [comment]
Closing as this will be fixed by the beta/mongoose site.

**Comment by barrymcgee** [comment]
@steverydz I'd prefer if we kept issues open until they have been resolved via a specific PR or demonstrably resolved on production? 

This ensures that if a prediction of resolution in the future falls short, we can still keep track of the issue.

**Comment by shivjoshi1996** [comment]
This has now been fixed with the new nav. Tested the width and it doesn't break.
