### ISSUE TITLE
Ubuntu.com/server logo images not loading

### ISSUE THREAD

**Issue by cseanburns** [canonical-websites/www.ubuntu.com#3729]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Logo images not loading on https://www.ubuntu.com/server

## Process

Visit https://www.ubuntu.com/server

## Current and expected result

Expected logos. Didn't load and was requested to submit this form.

## Screenshot

![screenshot_2018-07-12 ubuntu server - for scale out workloads ubuntu 1](https://user-images.githubusercontent.com/1939389/42637358-f352109a-85b8-11e8-8eab-c4b81b1e0aa4.png)
![screenshot_2018-07-12 ubuntu server - for scale out workloads ubuntu](https://user-images.githubusercontent.com/1939389/42637360-f371820e-85b8-11e8-8c2d-5972e036d24d.png)

**Comment by pmahnke** [comment]
thanks, this is working now.
