### ISSUE TITLE
beta launch: Point mongoose.ubuntu.com at www.ubuntu.com host

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3736]

**Comment by anthonydillon** [comment]
Are to switching the DNS or merging the `beta-1.7.0` branch into master? If we switch DNS then www.ubuntu.com will be on kubernetes.

**Comment by anthonydillon** [comment]
This is difficult is estimate without knowing how it will be implemented?

**Comment by anthonydillon** [comment]
This has been done.
