### ISSUE TITLE
running under Windows 8.1

### ISSUE THREAD

**Issue by Brian-Howard** [canonical-websites/www.ubuntu.com#3749]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by steverydz** [comment]
Thanks for filing an issue. Would you please be able to provide more information?

**Comment by Caleb-Ellis** [comment]
Closing as I believe this is an issue regarding the Ubuntu OS. Please reopen @Brian-Howard if I'm wrong on this, thanks!
