### ISSUE TITLE
LiveChat button changed? Please fix- DEV

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#3750]
We recently redesigned LiveChat button to match our brand guidelines (please check issue #3336) and also to look nice next to the new Feedback button. For some reason now looks different (not sure if it was automatically updated?). It's also on top of the Feedback button and should be sitting next to it. 

![Screen Shot 2018-07-16 at 10.36.48.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/a0b1016b-a3a9-4327-8951-226a796763fe)

When opened there's is a light blue background and a blue button which we didn't pick. Can we please change this back to the light grey background and green button?

![Screen Shot 2018-07-16 at 10.36.58.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/77de3b80-4e78-4e16-8492-f99a9c0185cd)

Any questions let me know

**Comment by steverydz** [comment]
Looks like the code in the livechat iframe has changed so our overrides no longer apply. This is always a danger with third party code.

We can't change anything within that widget but should be able to change it's position again - although this could happen again so I think it would be safer to do something with the feedback button.

**Comment by anasereijo** [comment]
@steverydz can we change the positioning for now?

**Comment by steverydz** [comment]
@anasereijo I can try. I have to wait for it to appear though - only seems to be there at certain times of the day. It's likely to happen again though next time they change the ID of that bit of code. It's safer in my opinion to assume it will always appear bottom right and work around that somehow.
