### ISSUE TITLE
Partner logos not loading

### ISSUE THREAD

**Issue by symetric** [canonical-websites/www.ubuntu.com#3753]
https://mongoose.ubuntu.com/internet-of-things/robotics

<img width="1161" alt="screen shot 2018-07-17 at 11 35 47" src="https://user-images.githubusercontent.com/5683336/42812456-9caa691c-89b5-11e8-83b6-1669b9cef788.png">

---
*Reported from: https://mongoose.ubuntu.com/internet-of-things/robotics*

**Comment by steverydz** [comment]
Thanks for filing an issue. We'll hopefully have a fix for this soon.

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
