### ISSUE TITLE
Issue with ubuntu.com/server PARTNER LOGOS

### ISSUE THREAD

**Issue by InvincibleMiners** [canonical-websites/www.ubuntu.com#3764]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Partner logos on www.ubuntu.com/server are failing to load. (Can be found here: https://www.ubuntu.com/server#deploy-anywhere)

## Process

Visit: https://www.ubuntu.com/server#deploy-anywhere (takes you instantly to the problem area)

## Current and expected result

Didnt appear, should see the images.

## Screenshot

GYAZO: https://gyazo.com/6aa23e75fd2699f529f59c482ecd41f0

**Comment by steverydz** [comment]
Thanks for filing an issue. We'll hopefully have a fix for this soon.

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
