### ISSUE TITLE
Layout issues on mongoose homepage

### ISSUE THREAD

**Issue by steverydz** [canonical-websites/www.ubuntu.com#3771]
![screenshot-2018-7-19 the leading operating system for pcs iot devices servers and the cloud ubuntu](https://user-images.githubusercontent.com/1413534/42973651-d48a3b76-8bab-11e8-8399-79deed41dee9.png)

**Comment by anasereijo** [comment]
It should look like what we have on ubuntu.com

![Screen Shot 2018-07-20 at 09.47.29.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/4f52c87a-0644-43bc-8360-627c0f324fb4)
