### ISSUE TITLE
Fix design of the blog feed section on the mongoose homepage

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3773]
Can we please look at the styling of the blog feed section on the mongoose homepage. They look quite different and centred button is weird. 

Mongoose:
![blog button.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/b7a6f90e-0119-4f9a-8247-e22ae7dc71e4)
u.com:
![blog button 2.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/57e87bec-4184-4fc8-8938-fde62683db94)

**Comment by anasereijo** [comment]
Hi @frankiegranato 
this ticket is duplicate. I also created one https://github.com/ubuntudesign/web-squad/issues/728
