### ISSUE TITLE
Robotics Partners logos are not displayed on accessing Ubuntu robotics page

### ISSUE THREAD

**Issue by pras-kolar** [canonical-websites/www.ubuntu.com#3777]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[please describe the issue]

## Process
1.  From the page https://www.ubuntu.com/download/alternative-downloads#alternate-ubuntu-server-installer
2.  click on Robotics link, at the bottom of the page

## Current Result

The robotics page is displayed
but seems like the Partner logos are not displayed
Instead , in that area a text displaying that user should creating a bug

## Expected result

Logos of the related Robotics Partners need to be displayed;
If these Logos or icons have a link to the Partner site, it will be better

## Screenshot

[if relevant, include a screenshot]

**Comment by steverydz** [comment]
Thanks for filing an issue. We hope to have a fix for this soon.

**Comment by nottrobin** [comment]
This should now be fixed. (Also mentioned in #3778)
