### ISSUE TITLE
Typo in https://help.ubuntu.com/community/WifiDocs/Scan_for_Wireless_Network

### ISSUE THREAD

**Issue by acli** [canonical-websites/www.ubuntu.com#3783]
“Acuire” should be “Acquire”. The page is “immutable” so couldn’t fix it.

---
*Reported from: https://www.ubuntu.com/support/community-support*

**Comment by anthonydillon** [comment]
Login seems to be down at the moment. I will check again shortly.

**Comment by anthonydillon** [comment]
The typo has been fixed. Thanks.
