### ISSUE TITLE
Error:Our partner logos failed to load. On the containers page

### ISSUE THREAD

**Issue by MartyLanda** [canonical-websites/www.ubuntu.com#3784]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

Received the error - 
Error: Our partner logos failed to load. Please report this bug and our team will fix the problem as soon as possible.
toward the bottom of the containers page.

## Process
Simply navigate to the container page. https://www.ubuntu.com/containers

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
