### ISSUE TITLE
Missing Logo's

### ISSUE THREAD

**Issue by xmascreek** [canonical-websites/www.ubuntu.com#3789]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

Missing . Logo's

login to https://www.ubuntu.com/internet-of-things/gateways

Expected to see logo's - they are not there

<img width="1029" alt="screen shot 2018-07-25 at 11 13 14" src="https://user-images.githubusercontent.com/41680441/43195927-5fee4a8a-8ffe-11e8-91b7-6d9030452df2.png">

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
