### ISSUE TITLE
AI/ML webinar takeover - Build

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-websites/www.ubuntu.com#3805]
@anasereijo commented on [Fri Jul 20 2018](https://github.com/ubuntudesign/web-squad/issues/730)

copydoc:
https://docs.google.com/document/d/1ERb5EJPshFU7TtFEJWPdFyEGSP7OLSk9Kf3RuURYeG8/edit

webinar:
https://www.brighttalk.com/webcast/6793/330440

---

@anthonydillon commented on [Mon Jul 23 2018](https://github.com/ubuntudesign/web-squad/issues/730#issuecomment-407118481)

Can we add estimates please

**Comment by anasereijo** [comment]
final designs here #729

background gradient: 
`background-image: linear-gradient(-44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);`

illustration: https://assets.ubuntu.com/v1/7d33e0a1-AI+illustration+hero.svg

**Comment by anasereijo** [comment]
@Caleb-Ellis assets for the animation:
[dotted circle](https://assets.ubuntu.com/v1/9f3f2b68-dotted-circle.svg
)
[ubuntu logo](https://assets.ubuntu.com/v1/54e24b4c-ubuntu-logo.svg
)
[desktop icon](https://assets.ubuntu.com/v1/5e8d3f1a-desktop-icon.svg
)
[iot icon](https://assets.ubuntu.com/v1/c2715a27-iot-icon.svg
)
[cloud icon](https://assets.ubuntu.com/v1/82c26ccc-cloud-icon.svg)
[server icon](https://assets.ubuntu.com/v1/fd20f946-server-icon.svg)
