### ISSUE TITLE
minecraft launcher version 2.1.1218 doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by minecraftNewbee** [canonical-websites/www.ubuntu.com#3830]
We have minecraft launcher installed on our Ubunto for quite some time.
The latest update to the launcher, which was done on 7/23/18 or 7/24/18 caused the launcher to stop working. We click on the icon, but no screen pops up.
Current product versions are minecraft launcher version 2.1.1218 (stable), and Ubuntu version 18.04.1 LTS.

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
This issue list is for issues on the website. If you would like to file an issue on Ubuntu the operating system. Please file it here: https://help.ubuntu.com/community/ReportingBugs
