### ISSUE TITLE
Error showing partner logos

### ISSUE THREAD

**Issue by apathyuk** [canonical-websites/www.ubuntu.com#3837]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Partner logos fail to load at https://www.ubuntu.com/internet-of-things/robotics and the site requests opening a ticket

## Process

Go to https://www.ubuntu.com/internet-of-things/robotics

## Current and expected result

An error message is displayed saying that partner logos could not be displayed.

## Screenshot

[if relevant, include a screenshot]

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
