### ISSUE TITLE
Add copy docs metadata to more ubuntu.com pages

### ISSUE THREAD

**Issue by bartaz** [canonical-websites/www.ubuntu.com#3848]
## Summary

Follow up to hackday PR (https://github.com/canonical-websites/www.ubuntu.com/pull/3793) that added copy docs links to some of ubuntu.com pages.

Original PR only added metadata to some pages, for taking full benefit of the copy docs extension links to copy docs should be added to templates of all pages that have copydocs.

Assuming template page inherits from main template adding a copydoc is just about adding one block:

```
{% block meta_copydoc %}https://docs.google.com/document/d/1NvYOhOJzdY5ypifTPs73vH5Nb7rFABRWMzjXyDUQt_U/edit{% endblock meta_copydoc %}
```

The link could be either link to a folder (if there is no specific document for given page/url) or to a copy document.

For example use see #3793.

## QA

Firefox extension is now published and can be installed at: https://addons.mozilla.org/en-US/firefox/addon/ubuntu-copy-docs/

**Comment by Caleb-Ellis** [comment]
Bumping estimate to 3 because there are a loooooooooot of pages on ubuntu.com

**Comment by anthonydillon** [comment]
Estimations should not be based on the time they take but the complexity of
the task.

https://github.com/canonical-webteam/practices/blob/master/project-management/fibonacci-estimation-guide.md
