### ISSUE TITLE
Partner's logo failed to load

### ISSUE THREAD

**Issue by meticulousCraftman** [canonical-websites/www.ubuntu.com#3849]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

The partner's logo failed to load on the website.

## Process

Just open [https://www.ubuntu.com/containers](https://www.ubuntu.com/containers)

## Screenshot

![screenshot from 2018-08-01 18-19-09](https://user-images.githubusercontent.com/11087870/43522625-86e8fb9e-95b7-11e8-9ffc-307c85acce48.png)

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
