### ISSUE TITLE
Partner logos not visible ubuntu.com/internet-of-things/robotics

### ISSUE THREAD

**Issue by vaibhavkhulbe** [canonical-websites/www.ubuntu.com#3850]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

Partner Logos failed to load on robotics page

## Process

1. Visit [this page](https://www.ubuntu.com/internet-of-things/robotics)
2 On second div inside the div with id main-content, you will see the error

## Current and expected result

current result : message showing partner logos failed to load
expected result : show partner logos

## Screenshot

[
![screenshot from 2018-08-02 02-31-18](https://user-images.githubusercontent.com/9023801/43548972-00cd6496-95fd-11e8-98ad-3d1796567eca.png)
]

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
