### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by Robobloq2018** [canonical-websites/www.ubuntu.com#3851]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by anthonydillon** [comment]
Hello @Robobloq2018,

Could you please retry to load the site and let us know if it was a small outage. Also could you provide more details such as your location, browser and operating system.

**Comment by pmahnke** [comment]
we think we have fixed the partner feed issue.

also, there has been no response, so closing for now.

reopen if there are still issues
