### ISSUE TITLE
Problem with news feed

### ISSUE THREAD

**Issue by Sorren1969** [canonical-websites/www.ubuntu.com#3852]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

From landing page, clicked on "Resources" 

Page loaded with a problem with a single component: Error with news feed (failed to load).

Cheers.

**Comment by Sorren1969** [comment]
"Error:The live news feed failed to load. Please report this bug and our team will fix the problem as soon as possible."

https://www.ubuntu.com/resources

**Comment by nottrobin** [comment]
Thanks for alerting us. We are aware of the problem (originally in #3801) and hope to have a fix live today.
