### ISSUE TITLE
https://www.ubuntu.com/internet-of-things/robotics page not working

### ISSUE THREAD

**Issue by ratheeps** [canonical-websites/www.ubuntu.com#3855]
## Summary

https://www.ubuntu.com/internet-of-things/robotics

## Process

When I click the robotics under IoT menu

## Current and expected result

Error: Our partner logos failed to load. Please report this bug and our team will fix the problem as soon as possible.

## Screenshot

<img width="1680" alt="screen shot 2018-08-02 at 16 45 31" src="https://user-images.githubusercontent.com/15723397/43580579-8b215aa0-9673-11e8-9fa4-edb117de2b96.png">

**Comment by nottrobin** [comment]
This is now fixed. (Details in #3778)
