### ISSUE TITLE
500 Error for any search from landing page

### ISSUE THREAD

**Issue by slytherjen** [canonical-websites/www.ubuntu.com#3860]
>log on to https://ubuntu.com
>in search, search for ubuntu 6.04
>hit enter
>observe

EXPECTED:  That I would be taken to an area to download an iso of ubuntu 6.04
ACTUAL:  I received a 500 server error

NOTE:  This occurs for any search.  

ENVIRONMENT:  MacBook Pro 10.13.5, Firefox 61.0.1

---
*Reported from: https://www.ubuntu.com/?utm_expid=.92kIXiqDSpuSF35lE8FS1Q.0

**Comment by nottrobin** [comment]
Thanks for reporting this @slytherjen. I believe this is now fixed.
