### ISSUE TITLE
Ugly table styling

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3873]
These table styles look ugly. Can we please fix the spacing on the title rows? I think this is probably caused by a Vanilla update (fyi @kwm14 ) 
![screen shot 2018-08-09 at 10 43 09](https://user-images.githubusercontent.com/17002826/43891435-2faa4012-9bc1-11e8-873d-7036248d89c9.png)

---
*Reported from: https://mongoose.ubuntu.com/support/plans-and-pricing*

**Comment by kwm14** [comment]
@frankiegranato agree they do need some love 😄 they use Vanilla tables but has quite a lot of bespoke styling on top of it...

@anasereijo brought it up in our Visual review meeting last week so we had some suggestions for her especially a better mobile version too 👍
