### ISSUE TITLE
Searching returns http 500 internal server error

### ISSUE THREAD

**Issue by pzn1977** [canonical-websites/www.ubuntu.com#3879]
Steps to reproduce the bug:

1. open https://www.ubuntu.com/
1. on the search box (top right corner), put some text (for example "test") and click <enter>
1. it will redirect https://www.ubuntu.com/search?q=test and return a "500 server error" webpage

---
*Reported from: https://www.ubuntu.com/*

**Comment by anthonydillon** [comment]
Also returning 500: https://www.ubuntu.com/search?q=newsletter

**Comment by pmahnke** [comment]
I suspect one instance of u.c is running the old search service.  I think we should file and RT and check.  @nottrobin ?
