### ISSUE TITLE
Tablet navigation broken on Firefox

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#3884]
On Firefox a medium screen sizes the navigation is very broken:
![screenshot_2018-08-11 resources ubuntu](https://user-images.githubusercontent.com/1413534/43995874-393c8226-9daf-11e8-8059-c9debf75ee58.png)

**Comment by shivjoshi1996** [comment]
This seems to have been fixed. Closing.
