### ISSUE TITLE
 IoT app store takeover - Build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3894]
brief: https://docs.google.com/document/d/1gcvBmsTPoJFdLB4p8A92tbjWVHQEYQOlZugFrBBYnek/edit#

**Comment by frankiegranato** [comment]
@anthonydillon I'm assigning this to you because Caleb is likely to be away on holiday when this takeover is designed and ready to be built. If you (or one of your guys) can't do it, it's not a big deal - I'm sure David will be happy to build it as part of his landing page (even if it doesn't become a takeover on u.com for a while).

**Comment by anasereijo** [comment]
@anthonydillon as discussed here goes the piggy bank icon https://assets.ubuntu.com/v1/6d4f864b-Piggy+Bank+icon.svg
let me know if you need anything :) thanks
