### ISSUE TITLE
Search is broken on staging.ubuntu.com

### ISSUE THREAD

**Issue by caldav** [canonical-websites/www.ubuntu.com#3903]
## Summary

The search results page is returning `500` errors. It used to be fixed on www.ubuntu.com, it seems to be broken again on the beta.

## Process

Go to http://staging.ubuntu.com/search?q=foo

## Current and expected result

Current: Error 500
Expected: A few results

**Comment by Caleb-Ellis** [comment]
Fixed as of #3911 :+1:
