### ISSUE TITLE
Old image being used for representation of Juju charms on http://www.staging.ubuntu.com/public-cloud

### ISSUE THREAD

**Issue by kasiag** [canonical-websites/www.ubuntu.com#3904]
Please use an alternative image to visualise charms on http://www.staging.ubuntu.com/public-cloud in "Fast service deployment with Juju'

Current image uses squircles which have been phased out

See screenshot
![screen shot 2018-08-16 at 13 27 03](https://user-images.githubusercontent.com/4948563/44208393-1cf7dc80-a158-11e8-9ea3-33fce21efe12.png)

**Comment by kwm14** [comment]
Updated image to use circles 👍  - https://assets.ubuntu.com/v1/162002c2-charms_juju.svg

![screen shot 2018-08-22 at 10 09 55](https://user-images.githubusercontent.com/17748020/44454475-90d03400-a5f3-11e8-859c-f0a82af8dead.png)
