### ISSUE TITLE
Livepatch Overview has a typo

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#3925]
Livepatch Overview has a typo:

Every system covered by an Ubuntu Advantage support
contract is entitled to use the Canonical Livepatch Service
at no additional cost, starting at our entry level UA
Essential for $75/year for virtual machines, or $225/year
for **pnysical** machines.

https://assets.ubuntu.com/v1/ac3aa269-DS_Canonical_Livepatch_Service_screen-AW_08.17.pdf

---
*Reported from: https://www.ubuntu.com/server/livepatch*

**Comment by pmahnke** [comment]
@cjohnston1158 this has been fixed, thanks

**Comment by pmahnke** [comment]
oh, in the pdf... got it
