### ISSUE TITLE
Updates to release-cycle page - build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3933]
See notes in copydoc: https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit#
@anasereijo will provide you with the new diagram. 

---
*Reported from: https://www.ubuntu.com/about/release-cycle*

**Comment by anthonydillon** [comment]
This has been completed.
