### ISSUE TITLE
VMware to OS Webinar (German) takeover - Design

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3938]
brief https://docs.google.com/document/d/1UkzAev5PKY5iR1mJOGNzpclxayATiImqE1AFO5wqXhI/edit?ts=5b7ecc0b

landing page https://www.ubuntu.com/engage/de/vmware-to-openstack

**Comment by anasereijo** [comment]
@frankiegranato this (quick design) is ready for review :)

### desktop
![final - takeover-large-screen](https://user-images.githubusercontent.com/36884067/44731544-4bbc6e00-aadb-11e8-9fac-79e28ba85524.jpg)

### mobile
![takeover-small-screen](https://user-images.githubusercontent.com/36884067/44731546-4ced9b00-aadb-11e8-8502-e77382b7d020.jpg)

**Comment by frankiegranato** [comment]
@anasereijo The white could is barely visible on the pale grey background but I am not going to -1 for that - especially when we are so many other takeovers to get done and this one is not going to be widely seen.

**Comment by anasereijo** [comment]
@frankiegranato you are right, in some screens the white cloud is not that visible and I did try to change the colour but didn't look nice in a darker colour. So I decided to keep it on white as in some screens you can see it and if you can't it isn't problematic.
