### ISSUE TITLE
VMware to OS Webinar (German) takeover - Build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3939]
For users in germany, this takeover needs to alternate, per session, between this one (1st) and the IOT App store takeover (2nd).

**Comment by frankiegranato** [comment]
@Caleb-Ellis for users in germany, this takeover needs to alternate, per session, between this one (1st) and the IOT App store takeover (2nd).

**Comment by anasereijo** [comment]
@Caleb-Ellis 
Design [here](https://github.com/canonical-websites/www.ubuntu.com/issues/3938)
Icon [here](https://assets.ubuntu.com/v1/35515576-openstack-cloud.svg)
suru left-side [here](https://assets.ubuntu.com/v1/1d83c9a3-suru-left-side.svg)
suru right-side [here](https://assets.ubuntu.com/v1/dea0b0c3-suru-right-side.svg)
`background-color: #F7F7F7;
`
