### ISSUE TITLE
'Main' component license policy violations

### ISSUE THREAD

**Issue by tomreyn** [canonical-websites/www.ubuntu.com#3945]
As of today, https://www.ubuntu.com/licensing (snapshot at http://archive.is/tXMSI ) states that 

> all application software included in the Ubuntu main component 
> - must include source code AND
> - must allow modification and distribution of modified copies under the same license.

My understanding is that Intel 
* does not include source code for the opaque microcode update blobs they distribute, which, as we must assume, include executable / executed code
* does not permit modification or redistribution of microcode

This may also apply to other packages in the 'main' component, such as (but not limited to) 'amd64-microcode'.

So, at least in my interpretation, it would seem that either the licensing statement at https://www.ubuntu.com/licensing is incorrect / outdated or the current practice of including binary blobs in the 'main' component violates this license policy.

---
*Reported from: https://www.ubuntu.com/licensing*

**Comment by cjohnston1158** [comment]
This policy applies to application software. The packages indicated are microcode packages, which are not the same as application packages. Since microcode is not the same as application packages, this does fall inline with the stated policy. Additional information can be found in the bug filed for intel-microcode: [](https://bugs.launchpad.net/ubuntu/+source/intel-microcode/+bug/1738272)

**Comment by tomreyn** [comment]
Thanks for explaining, Chris. 

Personally I find it surprising and unexpected that different policies apply to application software vs. firmware and microcode, allowing both to be included in 'main'. I assume this will be similar for (most) other users, who just expect anything in main (not just 'application software') to be open source, allowing redistribution of modified works, and to be under a DFSG compatible or permissive license. I.e. personally I'd thought that any firmware and microcodes for which no source code is available would better fit into 'restricted'.

I do acknowledge, however, that this is a discussion Ubuntu developers (or Canonical) should probably have outside of this bug tracker and that, based on the explanation provided, there is no bug on https://www.ubuntu.com/licensing

**Comment by pmahnke** [comment]
closing as not related to ubuntu.com directly
