### ISSUE TITLE
/desktop/user-report - Visual design - review and refine 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3951]
live demo: https://github.com/canonical-websites/www.ubuntu.com/pull/3997

**Comment by anasereijo** [comment]
![FINAL-VERSION_.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/9340d73b-73d6-4492-ba68-4eb6164ac087)
