### ISSUE TITLE
Multicloud takeover build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#3957]
Whitepaper link:
https://drive.google.com/open?id=1ePPGbmuSEZy-WPCOxLl-X-cO8PuA3kLu

**Comment by anasereijo** [comment]
@anthonydillon this is ready to be built.

You can see the final designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/153#issuecomment-418085878)

- [ ] can you make the first line of copy uppercase and 16px?

- [ ] `background: #F7F7F7;`

- [ ] [Illustration](https://assets.ubuntu.com/v1/3899d03f-choosingacloud.svg)
 
- [ ] [suru right side](https://assets.ubuntu.com/v1/dea0b0c3-suru-right-side.svg)

- [ ] [suru left side](https://assets.ubuntu.com/v1/1d83c9a3-suru-left-side.svg)

- [ ] About the animation I was thinking doing what [Caleb suggested](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/153#issuecomment-418158747).

**Comment by caldav** [comment]
@anthonydillon if you don't mind, please use the branch for https://github.com/canonical-websites/www.ubuntu.com/pull/3996 as your target for the takeover PR, so the landing page can inherit the CSS from the takeover for its hero and have both pieces of code merged at the same time.
