### ISSUE TITLE
Small updates to /appstore page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3960]
Store Enterpirse Proxy becomes Snap Store Proxy
As per comments in copydoc: https://docs.google.com/document/d/1CKwmPDDtXOIgw-jSZFwzP-qLMc_rS_dUACpHQXlg0fA/edit#
See: https://www.ubuntu.com/internet-of-things/appstore
As requested by Adam Collard

**Comment by anthonydillon** [comment]
Closed via https://github.com/canonical-websites/www.ubuntu.com/pull/3984
