### ISSUE TITLE
Updates to /legal/ubuntu-advantage/service-description - UX

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3968]
https://docs.google.com/document/d/1JuxYXtJOdXwe7MbV1JlQmStUfRKakVR3Tjo6y0p5XqY/edit

**Comment by shivjoshi1996** [comment]
This has been done

**Comment by cjohnston1158** [comment]
Please use this doc instead:
https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit

**Comment by cjohnston1158** [comment]
I believe this is complete
