### ISSUE TITLE
Updates to /legal/ubuntu-advantage/service-description - Build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3969]
https://docs.google.com/document/d/1JuxYXtJOdXwe7MbV1JlQmStUfRKakVR3Tjo6y0p5XqY/edit

**Comment by shivjoshi1996** [comment]
Done.

**Comment by cjohnston1158** [comment]
Please use this doc instead:

https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit

**Comment by cjohnston1158** [comment]
I believe this is complete

**Comment by frankiegranato** [comment]
@anthonydillon I think there might be a few outstanding little updates to be done. See my comments in the copydoc: https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit#

**Comment by shivjoshi1996** [comment]
Closing as this is complete @anthonydillon
