### ISSUE TITLE
Updates to plans-and-pricing - UX

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3970]
https://docs.google.com/document/d/1R7FRZbfx_5YHFeZUD93HgT8RW4OCbbK4blOulB4D6EE/edit#

**Comment by shivjoshi1996** [comment]
@frankiegranato There are a few outstanding questions on the copydoc, something you may need to have a look at.

**Comment by frankiegranato** [comment]
This has been reviewed by me. My comments in the doc describe the changes.
