### ISSUE TITLE
UA Service Description 2018.07 

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3975]
Updates to /legal/ubuntu-advantage/service-description
Copydoc: https://docs.google.com/document/d/1mrNrsC1WDf6QTg3nrVCEZS8vJzGz1fokvoFDVC4s_mI/edit
Brief: https://docs.google.com/document/d/16tA2kIA9WCcQVAJJeHvN6a5R-u3dewslsn5lcXYvtAo/edit#

**Comment by cjohnston1158** [comment]
@frankiegranato I believe this is complete

**Comment by frankiegranato** [comment]
@shivjoshi1996 Please let me know when you've been through each of these issues and have a status update. Thanks.
