### ISSUE TITLE
Amends to global product menu

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#3976]
Close up space between logos and texts.  (mark request)
Include Canonical as a site. (Carla request)
Resources links need some consideration. 
See anoted screen shot attahched. 
links to certification
Copydoc: https://docs.google.com/document/d/1fmPEv9gi4kZZDDylGtUJg5KNwK7GktdMTYCF570WyYA/edit#heading=h.s107xu2kx7vo

**Comment by anthonydillon** [comment]
This work should be done on the global-nav project.

**Comment by kasiag** [comment]
@frankiegranato can you define "Resources links need some consideration"

**Comment by anthonydillon** [comment]
@frankiegranato can you add the annotated screenshot please.

**Comment by frankiegranato** [comment]
![global-nav-amends.png](https://images.zenhubusercontent.com/593552bf51aa2c3057806d8c/fd94437f-eecb-4e4b-96d9-5977530eb9f9)

**Comment by anthonydillon** [comment]
@frankiegranato there is no destination for all webinars, whitepapers, etc on blog. This view is what the resource centre is for. I think we should leave the links pointing at resources.

**Comment by anasereijo** [comment]
@anthonydillon design is ready, please check it [here](https://github.com/canonical-websites/www.ubuntu.com/issues/4049)
Can we please replace Canonical logo with a [white version](https://assets.ubuntu.com/v1/47ba7e44-picto-canonical-white.svg)?
