### ISSUE TITLE
Review template files

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-websites/www.ubuntu.com#399]
## Context

It looks like we have some extraneous template files that may not be needed. We should review them and remove any unneeded files.

For example, is `/templates/mu-b760b7ee-790eb464-8b1bbe62-de00513f.html` used anywhere?

**Comment by pmahnke** [comment]
that was to get access to google webmaster toolkit

**Comment by anthonydillon** [comment]
@WillMoggridge as your PR landed I'll close this issue but please reopen if not fully complete.
