### ISSUE TITLE
Desktop user report page - build charts structure

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-websites/www.ubuntu.com#3992]

**Comment by inuwa** [comment]
Supporting Document Links - detailing design specifications
[Ubuntu user report - supporting spec](https://docs.google.com/document/d/16MgiSRz1VMlChF4vRHmMAXxk04jgC2MZSgPUbWTSvTY/edit#heading=h.9zqhdegu0itz "Ubuntu user report - supporting spec")

[Ubuntu user statistics - Design Document](https://docs.google.com/document/d/153OkfZHM_eTfAoUZF3f38VMtiFzaa2txB9B2lvs8xXA/edit#heading=h.fd71o4tpypqn "Ubuntu user statistics - supporting spec")

**Comment by shivjoshi1996** [comment]
We won't be doing this chart anymore.
