### ISSUE TITLE
Being directed to content in the wrong language

### ISSUE THREAD

**Issue by DiogoConstantino** [canonical-websites/www.ubuntu.com#4017]
When going to ubuntu.com, I'm being sent to a page with content in a language I don't speak, don't understand at all, is not set on browser, and is also not set on my Ubuntu system.

I would like to be able to understand the content from the ubuntu.com page, so don't direct me to content in languages I don't understand.
Probably you're inferring language from an IP address. However, being on a country doesn't mean I understand that country language(s), and having an IP that you believe to be associated users from a certain country doesn't mean I can't be using a VPN. And worst, in this case you're even failing in identifying the country.

Content based on any other thing than the browser language, or user set preferences is a very bad idea (to put it nicely because I love you).

---
*Reported from: https://www.ubuntu.com/index_de*

**Comment by Caleb-Ellis** [comment]
Hi @DiogoConstantino, thanks for filing this issue!

You are correct, users are being redirected based on their IP address which is run through a geolocation database. Clearly one or more countries have been misidentified. Regardless, we'll look into updating content based on browser settings and have a fix for this issue soon. :)

**Comment by jayk-canonical** [comment]
This appears to be due to an out-of-date geo-location data file. Suggest converting to use browser language instead - Accept-Language header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

**Comment by pmahnke** [comment]
hello, we removed the ip based language guessing for brower language settings... thanks for pointing this all out.

closing
