### ISSUE TITLE
Can't change website language

### ISSUE THREAD

**Issue by pederbe** [canonical-websites/www.ubuntu.com#4025]
I accessed ubuntu.com and was automatically redirected to /index_de
There is no button or other functionality to change language to my own language, English.

I attempted to manually change the URL to /index_en but that leads to a 404 error page.

---
*Reported from: https://www.ubuntu.com/index_de*

**Comment by Caleb-Ellis** [comment]
Hi @pederbe , thanks for filing this issue!

Users are currently being redirected based on their IP address which is run through a geolocation database. Clearly one or more countries have been misidentified. Regardless, we will look into updating content based on browser settings and have a fix for this issue soon. :)

**Comment by shivjoshi1996** [comment]
Hi @pederbe, you should now only see content that is the same as your browser setting language, so your problem should now be fixed :) 

We're not planning on allowing users to choose language anytime soon, so I'm going to close this card. 

Thanks again for filing this issue!
