### ISSUE TITLE
German takeover rotation error

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#4033]
The German "VMware to OS" takeover should be rotating with the "Financial Services" takeover (not the Artificial intelligence & machine learning takeover as it is now). We should fix this asap. 
See master takeover spreadsheet for more details: https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit#gid=1263179056

**Comment by frankiegranato** [comment]
@caldav Please can you double check that you are in agreement with this Fix. I've been referring to your master takeover spreadsheet https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit#gid=1263179056. Would be great if you can help us to clarify this.

**Comment by caldav** [comment]
+1 with the change. Will try to clarify the spreadsheet to take languages into consideration.
