### ISSUE TITLE
Improve conversions on /download/desktop/thank-you page - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4039]
Ubuntu desktop thank you: https://docs.google.com/document/d/187Vg9I0Jjlp1_yAjYtHdoEwFCJeVOaz9Kzeb6kptMpA/edit#

**Comment by anasereijo** [comment]
Hi @anthonydillon 

You can start building the **Ubuntu Desktop Thank you page**.

- [Final design](https://github.com/ubuntudesign/web-squad/issues/816)

- [pictogram](https://assets.ubuntu.com/v1/cbae9a60-thank_you_orange_cmyk.svg
)

- leave 1 column between the contribution scrollers and the Newsletter card

- please make the newsletter card sticky like we have on blog

- can we make the final contribution an input so people can change it before they pay?

**Comment by frankiegranato** [comment]
@anthonydillon are you doing this?

**Comment by anthonydillon** [comment]
@frankiegranato yes, is scheduled for next week.

**Comment by shivjoshi1996** [comment]
Design is now done : https://github.com/ubuntudesign/web-squad/issues/848

**Comment by pmahnke** [comment]
Version C is the winner (white background)

https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/834
