### ISSUE TITLE
Printing UASD contains site feedback questions

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#4041]
When printing the UASD, at the bottom of the printout the site feedback is visible.

<img width="435" alt="screen shot 2018-09-11 at 10 01 18" src="https://user-images.githubusercontent.com/24707086/45349685-dc9a4b80-b5a9-11e8-8a47-4619af950711.png">

---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage/service-description*

**Comment by anthonydillon** [comment]
This was complete via #4045
