### ISSUE TITLE
Copydoc helper should not show up on printed pages

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#4042]
## Summary

If you have the copydoc helper extension installed (Chrome atleast), when printing a page, the copydoc text should not be shown.

## Current

Install the helper extension
View a page
Print the page

## Screenshot

<img width="438" alt="screen shot 2018-09-11 at 10 15 20" src="https://user-images.githubusercontent.com/24707086/45350410-a4940800-b5ab-11e8-824a-479286d2850b.png">

**Comment by pmahnke** [comment]
@bartaz will add to the plugin... I have added to u.c and the survey
