### ISSUE TITLE
Amends to global product menu - Design

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#4049]
Close up space between logos and texts. (mark request)
Include Canonical as a site. (Carla request)
Copydoc: https://docs.google.com/document/d/1fmPEv9gi4kZZDDylGtUJg5KNwK7GktdMTYCF570WyYA/edit#heading=h.s107xu2kx7vo

**Comment by anasereijo** [comment]
@frankiegranato I've done 2 versions to discuss on the design review meeting.

![products 1.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/fbe265f4-0981-48cb-89e1-49b63c6564c8)

![Products v2.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/723e134d-7179-42e4-b50c-78ca266536b2)

**Comment by anasereijo** [comment]
We discussed this on Design Review Meeting and agreed on the following version:

![products v2](https://user-images.githubusercontent.com/36884067/45490106-262b9780-b75e-11e8-840b-cf7c260a8308.jpg)
