### ISSUE TITLE
Amends to global product menu - Build

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#4051]
See link updates in copydoc: https://docs.google.com/document/d/1fmPEv9gi4kZZDDylGtUJg5KNwK7GktdMTYCF570WyYA/edit#
Ana is updating the layout.

**Comment by shivjoshi1996** [comment]
I also created a build task in the correct repo, not sure which one you would want me to close @anthonydillon 

https://app.zenhub.com/workspace/o/canonical-webteam/global-nav/issues/45

**Comment by anasereijo** [comment]
@anthonydillon design is ready, please check it [here](https://github.com/canonical-websites/www.ubuntu.com/issues/4049)
Can we please replace Canonical logo with a [white version](https://assets.ubuntu.com/v1/47ba7e44-picto-canonical-white.svg)?

**Comment by anasereijo** [comment]
@frankiegranato @anthonydillon I think we should make the same layout changes on Login tab (and replace canonical logo with a [white version](https://assets.ubuntu.com/v1/47ba7e44-picto-canonical-white.svg) too)

<img width="1081" alt="screen shot 2018-09-13 at 14 11 29" src="https://user-images.githubusercontent.com/36884067/45490430-f5982d80-b75e-11e8-928c-7cf1743de48b.png">

should we create an Epic for this? FYI @shivjoshi1996
