### ISSUE TITLE
Add UA datasheet to support page

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4062]
We need to add a new UA datasheet to the top of the support index page, as per the copydoc https://docs.google.com/document/d/1liY2ulrI3JiICSJquTn9cH0Hu-R6H3ufmEmYhive-QI/edit

**Comment by frankiegranato** [comment]
A small wording change  in the doc (I just wanted to add a more explanatory CTA)
