### ISSUE TITLE
LinkedIn button goes to a dead link

### ISSUE THREAD

**Issue by ScottBrenner** [canonical-websites/www.ubuntu.com#4065]
Clicking the LinkedIn button at the bottom of [this page](https://pages.ubuntu.com/kubernetes-month.html) goes to a dead link for some reason - it links to https://www.linkedin.com/company-beta/234280/?pathWildcard=234280 when it should link to https://www.linkedin.com/company/ubuntu/. Seems fine on a the other pages I tested (like the home page).

---
*Reported from: https://pages.ubuntu.com/kubernetes-month.html*

**Comment by pmahnke** [comment]
@ScottBrenner thanks for filing this.  It is on our Marketo site, and I have passed it along to the team that works on that site.

**Comment by caldav** [comment]
Fixed by refreshing that page to the new default template (which only has the Twitter link).
