### ISSUE TITLE
same download url for both NUC models "Dawson Canyon" and "June Canyon"

### ISSUE THREAD

**Issue by pkubangbang** [canonical-websites/www.ubuntu.com#4067]
## Summary

at /download/iot/intel-nuc-desktop, "Installation instructions".
same download url for both NUC models "Dawson Canyon" and "June Canyon".

From the naming, it seems specific to the Dawson model.

## Process

just go to the webpage and see the urls

## Current and expected result

Should these two differ?

## Screenshot

![image](https://user-images.githubusercontent.com/30206270/45683214-772ff700-bb75-11e8-8c4b-7055d48f44de.png)

**Comment by pmahnke** [comment]
@caldav do you know about the june iso?

**Comment by pmahnke** [comment]
@pkubangbang thanks for filing, indeed, they are the same.
