### ISSUE TITLE
New livepatch page

### ISSUE THREAD

**Issue by frankiegranato** [canonical-websites/www.ubuntu.com#4070]
Design and build new /livepatch page (UX is complete)
This new page will live under /support/livepatch 
Copydoc: https://drive.google.com/open?id=1Ofw9bQ4I40gy9hDIjuDMApz6sDK8qSdHI03-oY7xs-A
Be sure to delete old /server/livepatch copydoc 
NB: this page is phase 1 of a larger project (talk to @matthewpaulthomas for more details)

**Comment by matthewpaulthomas** [comment]
As requested by @carlaberkers, I will brief @kwm14 on this page.
