### ISSUE TITLE
Intel Joule Desktop Install page is wrong

### ISSUE THREAD

**Issue by anonymouse64** [canonical-websites/www.ubuntu.com#4075]
The Intel Joule 18.04 Desktop install page listing is incorrect on a couple of things:

1. The `First boot tips` banner at the bottom is wrong - this page is about using desktop, not core so console-conf doesn't apply
2. An Ubuntu SSO account isn't necessary as this is a desktop image that doesn't use console-conf
3. The line `Download and copy the image on an USB flash drive by following the installation media instructions.` is duplicated
4. The `Install and develop snaps` could be better here as it is a classic system, so mentioning the link for installing the classic snap is unnecessary.

---
*Reported from: https://www.ubuntu.com/download/iot/intel-joule-desktop*

**Comment by pmahnke** [comment]
@anonymouse64 wow, thanks for this, I wish I saw it sooner. I have submitted a PR will all the changes you suggest!
