### ISSUE TITLE
Remove bespoke global nav and replace with npm package

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4077]

**Comment by shivjoshi1996** [comment]
Hey @anthonydillon, we forgot about this card. I could move it into small tasks since we didn't know about it, or I could leave it here if you think you'll have enough time to do it by Monday. Let us know. Cheers.

**Comment by anthonydillon** [comment]
I'm off Monday but is a small task so that would work. Problem is, to deliver the other changes from this epic it needs to be done so we should leave it and I'll do it first thing Tues.
