### ISSUE TITLE
 Detect browser language for takeovers

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4081]

**Comment by anthonydillon** [comment]
Here is documentation on how to detect the preferred language server-side or client-side. I would prefer to do it server-side to avoid the takeover visibly switching but my not be possible with the caching on the homepage. If it must be client side then inline js may execute quick enough. My 2 cent.

**Comment by inuwa** [comment]
Takeovers now have lang attribute used to detect the browser language setting and changes the takeovers based on that.
