### ISSUE TITLE
AI webinar takeover - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4087]
https://docs.google.com/document/d/1P8BC483zp5bYS5SuKimBHSIBlLhyEL9O_AcH3-pAjVc/edit#

**Comment by shivjoshi1996** [comment]
@anthonydillon The design of this will be the same as https://app.zenhub.com/workspace/o/ubuntudesign/web-squad/issues/729 , so the code for that one can be reused. 

The text will be different, which can be found on the [copydoc](https://docs.google.com/document/d/1P8BC483zp5bYS5SuKimBHSIBlLhyEL9O_AcH3-pAjVc/edit#) . (This needs to go through UX first though).

**Comment by frankiegranato** [comment]
@anthonydillon I have prepared the copy for this takeover. See preferred version indicated in the brief: https://docs.google.com/document/d/1P8BC483zp5bYS5SuKimBHSIBlLhyEL9O_AcH3-pAjVc/edit#
By the way, I've assinged this to @pmahnke
