### ISSUE TITLE
Fingbox takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4088]
https://docs.google.com/document/d/1P8BC483zp5bYS5SuKimBHSIBlLhyEL9O_AcH3-pAjVc/edit#

**Comment by kwm14** [comment]
## Build
- Original design issue can be found here: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/160
- Image - https://assets.ubuntu.com/v1/3811386c-fingbox_w-shadow.png
- Suru fold left - https://assets.ubuntu.com/v1/4a240561-fingbox-left-overlay.png
- Suru fold right - https://assets.ubuntu.com/v1/d6f89a88-fingbox-right-overlay.png
- Gradient - background-image: linear-gradient(-32deg, #006BA1 0%, #009EEE 84%, #08ACFF 100%);

## Visual
![takeover-large-screen-007](https://user-images.githubusercontent.com/17748020/46417136-e46c8c00-c720-11e8-892d-ace58ff4b77e.png)
![takeover-small-screen-007](https://user-images.githubusercontent.com/17748020/46417137-e5052280-c720-11e8-8af7-16443b7cf775.jpg)
