### ISSUE TITLE
unable to change sudoers file mode

### ISSUE THREAD

**Issue by MandyDan** [canonical-websites/www.ubuntu.com#4089]
tb-user@ubuntu:/$ su -l root
Password:
su: Authentication failure
tb-user@ubuntu:/$ sudo -i
sudo: /etc/sudoers is world writable
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
tb-user@ubuntu:/$ ^C
tb-user@ubuntu:/$
tb-user@ubuntu:/$
tb-user@ubuntu:/$ sudo -i
sudo: /etc/sudoers is world writable
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
tb-user@ubuntu:/$ chmod 440 /etc/sudoers
chmod: changing permissions of '/etc/sudoers': Operation not permitted

---
*Reported from: https://www.ubuntu.com/index_kylin*

**Comment by anthonydillon** [comment]
This project is for the website www.ubuntu.com. We cannot provide support for the operating system.
