### ISSUE TITLE
Ubuntu Promise is not shown on the website anymore

### ISSUE THREAD

**Issue by ahayzen** [canonical-websites/www.ubuntu.com#4136]
There used to be the "Ubuntu Promise" shown on the Ubuntu website, which reflects the ethics, mission and culture of where the original ideas around Ubuntu came from.

This can be seen in the 2006 variant of the website [0] (although here it is referred to as "public commitment to its users").  It can also be seen in the official CD cover and marketing material for the first Ubuntu LTS release [1] in 2006.  Furthermore it has been referred to more recently on Ubuntu's Google Code-In organisation page from 2017 [2]. (it can also be found in other places such as "the official ubuntu book")

As you can see the text itself differs between these pages, but the core ideas and values remain between them. So a discussion should probably be had for what is the current official text.

It would be good to have the text of this promise written somewhere on the website as it is important to the values of the Ubuntu project, I was expecting it to be under the section Community -> Ethos.

0 - https://web.archive.org/web/20060209032124/http://www.ubuntu.com:80/
1 - https://wiki.ubuntu.com/DIYMarketing?action=AttachFile&do=get&target=Ubuntu_wallet.pdf
2 - https://codein.withgoogle.com/archive/2017/organization/6246837463810048/

---
*Reported from: https://www.ubuntu.com/community/mission*

**Comment by Greggless** [comment]
This must have been lost in amongst various redesigns. But rest assured that the Ubuntu Promise has not been forgotten. Thank you for bringing this to our attention and we'll work this back into Ubuntu.com 🥇

**Comment by Greggless** [comment]
Reading through your sources, this information has been rewritten is most accurate and current on under the [Ethos section] (https://www.ubuntu.com/community/mission)
