### ISSUE TITLE
Small screen footer fold outs are not working

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4140]
On small screens the footer fold outs do not work below sectors.

**Comment by CoryKelly** [comment]
I can work on this.. Can you explain your issue a little more?

**Comment by anthonydillon** [comment]
@CoryKelly great thank you very much. If you run the site locally and reduce your screen size down to a phone size. Then scroll to the footer. The lower accordion buttons do nothing when clicked. The highlighted links do nothing: 
![screenshot_2018-10-16 the leading operating system for pcs iot devices servers and the cloud ubuntu](https://user-images.githubusercontent.com/1413534/47025094-c9573e80-d15a-11e8-993e-a332fb64a3a0.png)

**Comment by CoryKelly** [comment]
@anthonydillon Would you mind assigning this task to someone else? I'm afraid I will not get this done in a timely manner apologies.

**Comment by anthonydillon** [comment]
@CoryKelly Sure, thank you for taking the time to look into this issue.
