### ISSUE TITLE
Juju whitepaper takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4145]
https://docs.google.com/document/d/1e2qjJUrcgZVsvYeR9GgCu6nHUWFMkcDEstAKTqE4k5M/edit#

**Comment by kwm14** [comment]
## Design
Original design issue can be found here: https://github.com/ubuntudesign/www.ubuntu.com-design/issues/162

### Assets
- Bundle SVG - https://assets.ubuntu.com/v1/bb31c685-juju-k8s-bundle.svg
- Suru folds background image - https://assets.ubuntu.com/v1/30c32559-juju-k8s-bundle-folds.png
- Gradient background color - background-image: linear-gradient(-121deg, #022935 0%, #044F66 57%, #067597 100%);

![takeover-large-screen-005](https://user-images.githubusercontent.com/17748020/47162165-5d581000-d2eb-11e8-89a2-35e77ee6ebc3.png)

**Comment by inuwa** [comment]
@kwm14 Thank you for the pointers. I  have added the suggested changes now. Cheers

![image.png](https://images.zenhubusercontent.com/5ba8e4705284310fd7e28876/d94aff21-da43-4fb6-a806-8b8924b17063)

**Comment by inuwa** [comment]
The **Read More** button/link has placeholder for now because the engage page link has been created yet. I spoke to @caldav and he said it'll be ready by Monday.
