### ISSUE TITLE
Update GTM to release Intercom popup

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4190]

**Comment by shivjoshi1996** [comment]
@anthonydillon @pmahnke Do we still need to do this? The epic was closed but this issue is still open

**Comment by anthonydillon** [comment]
Not sure, but I think the epic should not have closed off this task
remains. I think we should reopen then epic and complete it this iteration.

**Comment by shivjoshi1996** [comment]
This issue is not needed anymore as we are not going to continue using intercom.
