### ISSUE TITLE
Update Core page - Build

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4203]
DO NOT RELEASE UNTIL 7 NOV 2018 (I.E. UNTIL THE PRODUCT LAUNCHES)

**Comment by anasereijo** [comment]
Hi, this is ready to be built.

desktop image: https://assets.ubuntu.com/v1/79334500-Ubuntu_Classic_vs_Core_Desktop.svg

mobile image 1: https://assets.ubuntu.com/v1/8ed3b472-Ubuntu_Classic_vs_Core_-mobile1.svg

mobile image 2: https://assets.ubuntu.com/v1/c6a45f9c-Ubuntu_Classic_vs_Core_-mobile2.svg
