### ISSUE TITLE
German takeover - K8s Webinar - Design

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4231]
Design german takeover for K8s webinar. 
keep consistency with the webinar banner: 
![k8swebinar_de](https://user-images.githubusercontent.com/36884067/47355628-c65bd100-d6b9-11e8-9c9f-5c4d515644c4.png)

brief https://docs.google.com/document/d/114ZrN2RodlgiL7m3a-P0GYp10KlgAKMfRkuwAaXxcaU/edit#

**Comment by anasereijo** [comment]
Desktop version:

![takeover-large-screen-007](https://user-images.githubusercontent.com/36884067/47355604-b643f180-d6b9-11e8-9c8f-17956fa5f688.png)


Mobile version:

![takeover-small-screen-007](https://user-images.githubusercontent.com/36884067/47355647-cf4ca280-d6b9-11e8-8e11-a5835fa47650.jpg)

**Comment by anasereijo** [comment]
@pmahnke this needs to be built asap. Do you mind having a look UX/QA wise? :) thank you!

**Comment by anasereijo** [comment]
@anthonydillon Just to double check if everything is all right, do you mind having a look (QA needed)? Thanks
