### ISSUE TITLE
German takeover - K8s Webinar - Build

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4232]

**Comment by anasereijo** [comment]
Hi @inuwa this can be built.

- you can find the final designs here: https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/4231

- background colour is: #326DE6

- icon: https://assets.ubuntu.com/v1/73fe5532-business+icon.svg

any questions let me know :)
