### ISSUE TITLE
German takeover - OpenStack Made Easy - Design

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4247]
[Copy doc](https://docs.google.com/document/d/1Nlf3UixAxDKSrdJj8blThJ-QpWLkJOd6qjg_h2RKrM4/edit?ts=5bc07493#)

**Comment by anasereijo** [comment]
Desktop version:

![FINAL - Takeover-large-screen.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/2f4682e6-6656-43fd-8602-c55381d03b95)


Mobile version:

![Takeover-small-screen-007.jpg](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/f28999ea-2770-4746-8eba-b8b3eb558977)

**Comment by anasereijo** [comment]
@pmahnke ready for UX review

**Comment by pmahnke** [comment]
all good!
