### ISSUE TITLE
German takeover - OpenStack Made Easy - Build

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4249]
Bried: https://docs.google.com/document/d/1Nlf3UixAxDKSrdJj8blThJ-QpWLkJOd6qjg_h2RKrM4/edit?ts=5bc07493#
See #4247 for details

**Comment by anasereijo** [comment]
- final designs: https://app.zenhub.com/workspace/o/canonical-websites/www.ubuntu.com/issues/4247

- illustration please make it size 342x219px. use this image: 
https://assets.ubuntu.com/v1/2c91289c-openstack-cloud.svg

- background colour: #F7F7F7

- suru left hand side: https://assets.ubuntu.com/v1/d3edfcd5-left.png

- suru right hand side: https://assets.ubuntu.com/v1/17508275-right.png

**Comment by anasereijo** [comment]
@inuwa this is ready to be built :)

**Comment by inuwa** [comment]
@anasereijo thanks
