### ISSUE TITLE
Wrong explanation for 'Firmware'

### ISSUE THREAD

**Issue by tomreyn** [canonical-websites/www.ubuntu.com#4256]
The statistics page currently says this:

> Firmware
> 
> The display server controls the input and output of its clients to and from the rest of the operating system and the hardware.

The explanation text is a copy + paste bug from 'Display server' which has the identical explanation attached.

---
*Reported from: https://www.ubuntu.com/desktop/statistics*

**Comment by anthonydillon** [comment]
@tomreyn thank you very much for taking the time to report this issue. I have prepared a change to the content which should be live soon.
