### ISSUE TITLE
Infographic colors confusing on https://www.ubuntu.com/desktop/statistics

### ISSUE THREAD

**Issue by wandrewkeech** [canonical-websites/www.ubuntu.com#4266]
## Summary

The infographic https://www.ubuntu.com/desktop/statistics#where-are-users is very confusing 

## Process

N/A

## Current and expected result

It's difficult to know if more orange means more users or less users, and what the measure of colorfulness (or non-colorfulness?) indicates (percentage of reporting users? rate of reporting users per pop in country? etc). My expectation is that I would be able to immediately and clearly understand who is using Ubuntu in which countries of the world, and by what measure.

**Comment by anthonydillon** [comment]
@wandrewkeech thank you very much for taking the time to report this issue. I will assign this to the design team to update.
