### ISSUE TITLE
"Download 18.10 now" directs to a generic download page which offers 18.04 first

### ISSUE THREAD

**Issue by oSoMoN** [canonical-websites/www.ubuntu.com#4267]
On the homepage, there's currently a banner advertising the new release, 18.10.
There's a "Download 18.10 now" link that redirects to https://www.ubuntu.com/download, which isn't 18.10 specific. In fact, when clicking the "Ubuntu Desktop" option, the first, most prominent option for download is 18.04.

Either the wording of the link in the banner should be changed to something like "Download Ubuntu", or it should direct the user to downloading 18.10 directly.

---
*Reported from: https://www.ubuntu.com/download/desktop*

**Comment by shivjoshi1996** [comment]
Hi,

Thank you for filing this. We've now changed the takeover to a different topic, so this isn't a problem anymore. But thank you for filing it!
