### ISSUE TITLE
Change SCSS rendering of Takeovers to CSS In-Page Style Block

### ISSUE THREAD

**Issue by inuwa** [canonical-websites/www.ubuntu.com#4268]
## Summary

Made changes to the CSS rendering. CSS Rendering of takeovers has been moved from styles.scss to in-page style block and includes removed.
## Process
- Convert SCSS to CSS
- Move SCSS To in-page style block.
- Remove references from SCSS

**Comment by anasereijo** [comment]
@inuwa can you please estimate this issue?
