### ISSUE TITLE
"Where are Ubuntu users" map seems wrong

### ISSUE THREAD

**Issue by 8none1** [canonical-websites/www.ubuntu.com#4274]
North America is seemingly low on users, but North America is a very popular location for users.

I wonder if the map is not reflecting the data correctly.  Perhaps the colours are inverted?

---
*Reported from: https://www.ubuntu.com/desktop/statistics*

**Comment by inuwa** [comment]
@8none1 The data is incomplete for now. It will be updated soon.

**Comment by inuwa** [comment]
@anthonydillon I'm not sure if this should be closed. Since we do not have the complete data Ubuntu worldwide users yet?

**Comment by anthonydillon** [comment]
@inuwa no we need to update the map data with the latest results in the spreadsheet. I believe the country IDs may have been mixed up.

**Comment by inuwa** [comment]
@anthonydillon I just spoke with @pmahnke, he offered to retrieve some user data for the spreadsheet to make it more accurate.
