### ISSUE TITLE
Update /openstack/install page instructions

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4275]
per the [copy doc](https://docs.google.com/document/d/1eQ16jzv6YRGzG_k_C-tUnhM06k6_Ic6fZM-x_ARMzuc/edit#heading=h.c4pfpz5v1oh0)

**Comment by shivjoshi1996** [comment]
This is a dupe of https://github.com/canonical-websites/www.ubuntu.com/issues/4294
