### ISSUE TITLE
18.10 webinar takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4284]
https://drive.google.com/file/d/0B5Jc5K2-I_6xS1E4OWMwd0VNSkx5elJJZWpFMkdEUXhNQk5z/view?usp=sharing

**Comment by spencerbygraves** [comment]
@shivjoshi1996 you can find the svg asset here - https://drive.google.com/drive/folders/1SckCPxD1QzLHFfM3h1yCaFP0hJOWKP8Y?usp=sharing

And the gradient is shown below:

![image](https://user-images.githubusercontent.com/9105999/47580273-5e6dea80-d946-11e8-9461-ec2d47b90e8c.png)
