### ISSUE TITLE
It was only the website with the bug. I'm actually really enjoying ubuntu and I really want to thank you.

### ISSUE THREAD

**Issue by sydneyrec69** [canonical-websites/www.ubuntu.com#4290]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary

[please describe the issue]

## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by shivjoshi1996** [comment]
Hi @sydneyrec69, glad you are enjoying Ubuntu. Could you tell me what problem you were having with the website? 

Thanks
