### ISSUE TITLE
compliance webinar takover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4337]
brief https://docs.google.com/document/d/1qgaKjCP7HMmXIeiccSEppfYQHjfu0GNdBBnXGb7hLjI/edit

**Comment by anasereijo** [comment]
Ready to be built:

- designs [here](https://app.zenhub.com/workspaces/web-squad-5931746dba512f05402b61f6/issues/ubuntudesign/www.ubuntu.com-design/163) 

- background `background-image: linear-gradient(-44deg, #171717 0%, #181818 9%, #262626 34%, #2D2D2D 67%, #383838 88%, #2E2E2E 100%, #393939 100%);`

- icon[here](https://assets.ubuntu.com/v1/2217d1c8-Security.svg). please make it 152x152 px both on mobile and desktop
