### ISSUE TITLE
Ubuntu core 18 takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4341]
brief https://docs.google.com/document/d/1Wdz3mW5F2Ul64sO2dJBcaELFMN--ewC0fhhJDWxf4XU/edit#

**Comment by anasereijo** [comment]
this is ready to be built

- design [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/164)
- gradient: `background-image: linear-gradient(-135deg, #333333 0%, #111111 50%, #111111 100%);`
- illustration [here](https://assets.ubuntu.com/v1/635ce124-IOT_core_infographic+light.svg)
