### ISSUE TITLE
Appelix takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4380]
https://docs.google.com/document/d/1I8TUiG_u1tksV1ElqzTTaO5ECjdVhKiA1Y71HRAWfMc/edit

**Comment by anasereijo** [comment]
This is ready to be built.

### Assets
- final designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/166)
- background gradient: `background-image: linear-gradient(-46deg, #82A08D 0%, #9AAF55 100%);`
- drone icon [here](https://assets.ubuntu.com/v1/f42b7e29-drone.svg)
   - big drone: 250x250
   - smaller drone 1: 112x112
   - smaller drone 2: 95x95
- suru (please apply  `background-blend-mode: multiply;`)
   - [left](https://assets.ubuntu.com/v1/2eb4cbf6-left.svg)
   - [right 1](https://assets.ubuntu.com/v1/53ca89d2-right+1.svg)
   - [right 2](https://assets.ubuntu.com/v1/35352e1c-right+2.svg)

### Notes
- don't use suru on mobile
- don't make the animation on mobile

### Animation
@anthonydillon as discussed would be perfect to have an animation when loading the page. 
See below an example of how I would like it to be. I would like the big drone to be positioned as my [design](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/166) and not as a + shape as the following example. Let me know if this possible and I can join you while you do it if you want.

![3 sde_drone_03_60 _](https://user-images.githubusercontent.com/36884067/48707236-ab1bad00-ebf6-11e8-9800-e8ad6b783bbf.gif)


Many thanks.
