### ISSUE TITLE
Trilio takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4382]

**Comment by anasereijo** [comment]
- Final designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/167)
- background gradient: `background-image: linear-gradient(-45deg, #E4E4E4 0%, #FFFFFF 100%);`
- text should be `class="col-8"`
- image should be `class="col-4"`
- image size: 230x60px
- suru images (please apply `background-blend-mode: multiply;`)
   - [left side](https://assets.ubuntu.com/v1/13f3fdeb-suru-left.svg)
   - [right side 1](https://assets.ubuntu.com/v1/d15c2f0b-suru-right1.svg)
   - [right side 2](https://assets.ubuntu.com/v1/ef731339-suru-right2.svg)

**Comment by anasereijo** [comment]
@inuwa this is ready to be built
