### ISSUE TITLE
Microk8s takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4383]
https://docs.google.com/document/d/1v2EaBXgysqfAd-kdl7OGw-eF4Fh-e4-SqrAvM4DUQrs/edit?disco=AAAACXULefM&ts=5bfd9b26

**Comment by anthonydillon** [comment]
@shivjoshi1996 can you check this to required, please?

**Comment by Greggless** [comment]
Copy is final. We'd like to run a test on the two versions. 

What's the process? We build and @caldav configures the test?

**Comment by anasereijo** [comment]
The takeover is ready to be built. 

- Find designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/168).

- This should be pretty straight forward to build as the background is the same we have on [micrk8s homepage](https://microk8s.io/).

- Please use [this logo](https://assets.ubuntu.com/v1/96d35aa4-certified-kubernetes-logo.svg). Desktop 180x243 and Mobile 150x203

- Text should be` 7-col`

- As @Greggless said in his previous comment, we'd like to run a test on the 2 copy versions.
