### ISSUE TITLE
Spicule takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4386]

**Comment by anasereijo** [comment]
This is ready to be built 😃 

- designs [here](https://github.com/ubuntudesign/web-squad/issues/913#workspaces/web-squad-5931746dba512f05402b61f6/boards?repos=23468646,26759534,71002475,93173097,19344240,86689528,91588826,49962783,52790813,84430331,77880627,37585342,49675635,101283798,114984711,141186223,141185647,141201737)
- bundle [here](https://assets.ubuntu.com/v1/9834b392-test.svg)
- `background-color: #F2F2F2;`
- spicule logo [here](https://assets.ubuntu.com/v1/088af968-spiculelogo-spacingx2-01.svg). make it 140x51px
- on mobile please hide the bundle and leave the icon
