### ISSUE TITLE
Remove 'I would like to receive eBooks and whitepapers' option from /download/server

### ISSUE THREAD

**Issue by Lewciie** [canonical-websites/www.ubuntu.com#4400]
Please remove this "I would like to receive eBooks and White Papers by Canonical." from the form as this has not been use (never by me at least), unsure why this form has it but preceeds me.
Thank you,
Lucia

---
*Reported from: https://www.ubuntu.com/download/server/s390x*

**Comment by caldav** [comment]
First time I see it. As @Lewciie said, that's very likely a remnant of the past, fully replaced by the "occasional news" checkbox.
