### ISSUE TITLE
Printing UASD clean-up

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#4401]
Hello,

I noticed a couple of things when printing the UASD that it would be nice if they could be cleaned up:

- [x] At the very bottom "Products" and "Login" from the new nav show up.
- [x] All table borders are removed, making things appear to run together.
- [ ] Line spacing appears to vary across the printed pdf.
- [x] Some links end up showing the URL afterwards, others don't.
![url](https://user-images.githubusercontent.com/24707086/48640118-232d6d00-e982-11e8-8d46-28f9c21cd10f.png)

Thanks!
---
*Reported from: https://www.ubuntu.com/legal/ubuntu-advantage-service-description*

**Comment by pmahnke** [comment]
@cjohnston1158 	I fixed three of these... the lineheights are part of Vanilla I think
