### ISSUE TITLE
Extend the support end date of 18.04 LTS on the download page to April 2028

### ISSUE THREAD

**Issue by eaglersdeveloper** [canonical-websites/www.ubuntu.com#4403]
Mark Shuttleworth: «I’m also delighted to announce that Ubuntu 18.04 will be supported for a full 10 years»

![2018-11-17 10-15-19](https://user-images.githubusercontent.com/40228953/48657910-1ed08500-ea52-11e8-8ede-06506a9a5250.png)

---
*Reported from: https://www.ubuntu.com/download/desktop*

**Comment by pmahnke** [comment]
@eaglersdeveloper thanks for this; however, I think that 10 years is within the [ESM product](https://www.ubuntu.com/esm) (which we will have to update information)
