### ISSUE TITLE
/engage Landing page template - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4404]

**Comment by anasereijo** [comment]
@anthonydillon this is ready to be built. please check designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/170)
@caldav suggested A/B testing A/B testing `p-strip--dark` VS `p-strip--light` on the next landing page we do to find out if a dark background performs better than a light grey one. 
Any questions let me know 😃
