### ISSUE TITLE
Mir in Product menu points to an outdated location

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4419]
## Summary

Mir link in 'product' menu links to the [wiki](https://wiki.ubuntu.com/Mir)
The wiki then points to [mir-server.io](https://mir-server.io/)

## Fix
Point Mir to https://mir-server.io/

**Comment by fitojb** [comment]
For the time being, I [made that wiki page redirect directly to the intended destination](https://wiki.ubuntu.com/Mir?action=diff&rev1=11&rev2=12).
