### ISSUE TITLE
Kubernetes page discusses MicroK8s but doesn’t link to it

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#4429]
1\. Go to the Kubernetes page.
2\. Try to find a link to the MicroK8s site.

What happens: The page has a section about MicroK8s, and a link to [the snap page](https://snapcraft.io/microk8s), but no link to [the product site](https://microk8s.io/).

What should happen: There’s a link to the site.

**Comment by matthewpaulthomas** [comment]
Ok, it’s now linking to microk8s.io, but it’s a bit odd that it links to a point halfway down the page (which has a design where it’s not obvious that it _is_ halfway down a page). There’s no obvious path to answer questions like “What else does it contain?” or “Where do I ask questions?”, where there would be if it also/instead linked to the top of the page.

**Comment by Greggless** [comment]
Updated /kubernetes with https://github.com/canonical-websites/www.ubuntu.com/pull/4487 to reflect your comment
