### ISSUE TITLE
Canonical-bar and Ubuntu-bar menus can be open simultaneously

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#4436]
1\. Go to [ubuntu.com](https://www.ubuntu.com/).
2\. In the “Ubuntu” bar, click “Enterprise”, “Developer”, “Community”, or “Download”.
3\. In the “Canonical” bar, click “Products” or “Login” [sic].

What happens: The two mega-menus remain open simultaneously.

![ubuntu com-multiple-menus](https://user-images.githubusercontent.com/19801137/49078895-26a0de00-f237-11e8-9e5d-1302caa6f1b1.png)

(With some combinations, the bottom menu is obscured by the top one, but it is still open.) 

What should happen: either
- the “Canonical” bar doesn’t contain any menus, or
- the “Ubuntu” bar doesn’t contain any menus, or
- (most likely) opening a menu always closes any non-ancestor menus.

This is the sequel to #3192.

**Comment by anthonydillon** [comment]
The global nav is a completely different project/code base. We can not functionally close a menu that is outside of the scope of the global nav.  Personally I think it's clear what is going on and that clicking the darkened area will close the to menu.

I will need to close this one for now as I can't see a solution and believe it is not terrible.

**Comment by matthewpaulthomas** [comment]
Ah, sorry, I guess my use of “closes” could have been misinterpreted. I didn’t mean that each project should close _the other’s_ menus! For example, launch VLC and Firefox, right-click inside one, then right-click inside the other. Each app’s context menu closes as the other one opens, despite the fact that they’re completely different projects and codebases and even use different toolkits.

This works because a toolkit closes its own menu, not specifically because another menu is opening elsewhere, but generally because you’ve clicked anywhere outside the menu. For both the ubuntu.com-specific menus and the global nav menus, this works if you click below them. Weirdly, it does not work if you click above them. If that was fixed, this bug would be too.
