### ISSUE TITLE
Increase the z-index for the navigation

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical-websites/www.ubuntu.com#4442]
A couple of takeovers have been built that require z-indexes, and on two occasions these have gone above the navigation's z-index. We should just set it to 99, which is 1 below the global nav

**Comment by nottrobin** [comment]
The global nav actually uses 4 different z-indexes:

1. `100`: The global-nav container
2. `99`: The nav header
3. `98`: The nav drop-down
4. `97`: The "overlay" underneath the drop-down

So we should choose a `z-index` below `97`. However, I think this might be a problem we may run into in future, so maybe we should create some (loose or hard) standards around this. Basically, some ranges, like:

- 0-50: Core website content
- 51-100: Plugins
- 101+: Reserved for the core website to overlay plugins if needed

Thoughts?

**Comment by nottrobin** [comment]
It looks like this ticket isn't currently an issue, except for, possibly, `p-gaming`.

![image](https://user-images.githubusercontent.com/519935/49883746-4802ec00-fe2b-11e8-9d05-28ba3f5b5ee8.png)

But that we need to find a way to avoid this happening in future.

I'm not sure "Increase the z-index for the navigation", the current title, is the right solution, since no matter how high the z-index for navigation is, someone could override it by using a higher one.

So I'm going to:

- Fix `p-gaming`
- File a PR on practices to define the ranges specified above

**Comment by Caleb-Ellis** [comment]
@nottrobin Yeah they've either been removed or updated already. I think they were both takeovers with overlaying animation (hence it becomes pretty easy to go above the nav's z-index of 3/4/10). Anyway I like the idea of some loose standards for z-index, but I think an immediate fix for this issue would be to increase the different nav z-indexes "a bit" so we've got some leeway with takeover animations

**Comment by nottrobin** [comment]
@Caleb-Ellis I don't understand that - are you saying you *need* more than 97 discrete z-index layers? My suggested ranges would provide you with 30 for in-site stuff, which also seems like more than enough. Am I wrong? What's an example of where you need so many z-index layers?

**Comment by nottrobin** [comment]
I ask because I suspect that a z-index of 100 was used in takeovers just because they picked a high number, not because they needed it. And I don't see a reason to do extra work to change global nav unless there is actually an argument for doing so.

**Comment by Caleb-Ellis** [comment]
@nottrobin Don't get me wrong I think the z-index ranges are a good idea, and I definitely don't think we need more than 97 layers. But the main problem with the current nav's z-index is that it is too low for overlaying animations on takeovers (or anywhere). For example, you have something in the background (2), something in the middle (3) and something over the top (4), and you're already over some parts of the nav.

I feel like I should be clear this issue is to do with the dropdown mega menu on ubuntu.com and not the global nav?

**Comment by anthonydillon** [comment]
I agree and the z-index ranges seems reasonable. How can we inform and reenforce this range across projects. Applications such as [Juju](https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/assets/css/_variables.scss#L84) has a [Sass map to manage z-indexs](https://jonsuh.com/blog/organizing-z-index-with-sass/).

**Comment by nottrobin** [comment]
Cool. Created PR, and created issue on practices: https://github.com/canonical-webteam/practices/issues/144.
