### ISSUE TITLE
Should we consider URL paths case-insensitive?

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#4448]
One of the top 10 404s on ubuntu.com is http://www.ubuntu.com/download/Server (see https://github.com/canonical-webteam/practices/issues/127#issuecomment-442456028). This is only a 404 because of the capital "S". https://www.ubuntu.com/download/server Is a real page.

Should we look into supporting uppercase characters in URLs? We could do this by either:

- Displaying the page regardless of the case in the URL
- Redirecting to remove the capital *if* the path exists
- Redirecting to remove all capitals from all URLs

**Comment by Greggless** [comment]
Could you point this up pretty please?

**Comment by nottrobin** [comment]
@Greggless ta-done
