### ISSUE TITLE
18.04 server BitTorrent Link Not Found

### ISSUE THREAD

**Issue by victor23d** [canonical-websites/www.ubuntu.com#4458]
Not Found

The requested URL /18.04/ubuntu-18.04.1-live-server-amd64.iso.torrent was not found on this server.
Apache/2.4.18 (Ubuntu) Server at releases.ubuntu.com Port 80

I have tried other BitTorrent download links, they are working well, but only 18.04 server link is 404.

---
*Reported from: https://www.ubuntu.com/download/alternative-downloads*

**Comment by cjwatson** [comment]
https://bugs.launchpad.net/ubuntu-website/+bug/1806180 notes that it should be 18.04.1.0 instead (I guess the server images were re-released?).

**Comment by vorlonofportland** [comment]
Yes, server image has been rereleased to hotfix a bug in apt sources.list post-install.  Sorry, we accounted for compatibility with the old download link for the iso but not for the torrent.

We should change the iso download link as well to remove ambiguity.
