### ISSUE TITLE
Desktop developer takeover - build

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4483]

**Comment by Greggless** [comment]
@anthonydillon WIll you be building this?

**Comment by anasereijo** [comment]
This is ready to be built.

- [Designs](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/171#event-2012717388)

- Gradient: `background-image: linear-gradient(-225deg, #333333 0%, #111111 50%, #111111 100%);`

- Text 7 col

- [Image](https://assets.ubuntu.com/v1/b4b238f8-Dell+XPS+13-1804-1.png)
