### ISSUE TITLE
Improve Marketo form styling

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4484]
- [ ] Margin between some elements too close,
- [ ] excessive padding at the end of forms

![image](https://user-images.githubusercontent.com/23459065/49505155-101c0780-f873-11e8-838a-3f6ddae0c0df.png)

**Comment by pmahnke** [comment]
@Greggless 	is this in vanilla or just u.c?

**Comment by anasereijo** [comment]
FYI we had this issue before on other pages and got fixed.
