### ISSUE TITLE
Tooltips don't work

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4491]
### Expected behaviour
Hover on SLA, pointer changes to ❓, information is displayed as to what SLA is.

### Actual behaviour
Hover on SLA, pointer changes to ❓ but no information is displayed

---
*Reported from: https://www.ubuntu.com/kubernetes/managed*

**Comment by shivjoshi1996** [comment]
This works for me, what browser were you using?

**Comment by Greggless** [comment]
Chrome 71.0.3578.98
Mac

**Comment by Caleb-Ellis** [comment]
It's not actually a "tooltip" tooltip, but an `abbr`. Basically you have to hover over for a second for it to show because that's how browsers have chosen to do it, and since it's more an accessibility thing than anything else I don't think it's something we should switch to Vanilla tooltips.

**Comment by Greggless** [comment]
oohhh, 

That's me being impatient

# ⏳
