### ISSUE TITLE
CTO’s guide download page has no link to download the e-book

### ISSUE THREAD

**Issue by Austemagne** [canonical-websites/www.ubuntu.com#4497]
The page (listed below) is supposed to be the official download page for the e-book, but it contains no download link; only a synopsis of the book.

https://pages.ubuntu.com/CIO_Report.html?utm_source=Insights&utm_medium=blog&utm_campaign=FY17Q1_CIO_report&

Here is a link to a .pdf ofthe e-book:

https://pages.ubuntu.com/rs/066-EOV-335/images/eBook_Cio-guide_%28Tom%29_04.16_AW.pdf

---
*Reported from: https://pages.ubuntu.com/CIO_Report.html?utm_source=Insights

**Comment by Austemagne** [comment]
Thanks. I could not have been more proud to help contribute! A little as it may seem :p

**Comment by Greggless** [comment]
# 🦑 

The cosmic cuttlefish thanks you.
