### ISSUE TITLE
/core 18 - Design

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4512]
- [x] Do the design thing
- [x] Pair with dev
- [ ] ... 

@anasereijo could you give this some points, pretty please?

# 🚀 🍰 🐘 ☮️

**Comment by anasereijo** [comment]
@Greggless you can design attached. I will try to find better (and more) assets to use but I think it's in a good place for devs to use as a guide. Let me know your thoughts! 👍 

![desktop hd](https://user-images.githubusercontent.com/36884067/49868331-07907780-fe05-11e8-9ba5-70fef2bd7e08.jpg)

**Comment by anasereijo** [comment]
@Greggless I also this is now very useful for us to think if we need the sticky nav (like the one we have on statistics)

**Comment by Greggless** [comment]
# Great work 🔥 💯 🖖 

## Some changes
I've adopted a primary and secondary CTA pattern for the end strips of each section. I think this'll look tidier than having links in the matrices.

### General
- [ ] We use sentence case (this needs to be fixed in the copy doc)
- [ ] A sticky nav would be useful for 2 reasons:
   1. Allow users to see what content is in the (long) page, allowing them to get a preview of what's to come
   2. It allows a user to dive right into a section that is most important to them, and also cross navigate in an order which they see fit


### Hero
- [ ] The logos were specifically separated into two rows based on ODM and silicon
- [ ] `positive btn` should read 'Get to market faster'
- [ ] Include Text with `positive btn` 'Canonical and partners speed your device development.'

### Security first
- [ ] Add `neutral btn` for [Contact us] in Minimal core
- [ ] Add link to [Download Ubuntu Core](https://ubuntu.com/download/iot) in Minimal core

### Built for business
- [ ] Add a `neutral btn` to [Visit the Snap Store](https://snapcraft.io/store)  on 'software ecosystem'
- [ ] Move '[See what an app store can do for you »](https://www.ubuntu.com/internet-of-things/appstore)' link from 'app store included' to 'software ecosystem' 

### Devs ❤️ Ubuntu
- [ ]Add a `neutral btn` to link to [snapcraft.io](https://snapcraft.io) on 'One platform..'
- [ ] Move link from 'Deploy to devices' to 'One platform'
- [ ] Reword link to [Learn about CI/CD with Snapcraft »](snapcraft.io/build)

### Reliability
- [ ] Add a `positive btn` to link to contact us on 'Right-sized silicon..'
- [ ] Add link to '[See our supported boards »](https://ubuntu.com/download/iot)

**Comment by Greggless** [comment]
But I think this can all be addressed in the [PR](https://www-ubuntu-com-canonical-websites-pr-4509.run.demo.haus/core)
