### ISSUE TITLE
Markdownify Ubuntu Advantage Service Description

### ISSUE THREAD

**Issue by BryanQuigley** [canonical-websites/www.ubuntu.com#4530]
## Summary
We need to refer to old service descriptions for legal/support reasons.  It would be much cleaner to read from git if they were in markdown.

The https://github.com/canonical-websites/www.ubuntu.com/blob/master/templates/legal/ubuntu-advantage-service-description/index.html
and the includes at the bottom:
{% include "legal/shared/_appendix-support-scope.html" with number="1" %}
{% include "legal/shared/_appendix-support-process.html" with number="2" %}
{% include "legal/shared/_appendix-management-escalation.html" with number="3" %}

Happy to do the conversion if I get a +1/guidance.

Forked from #2395

**Comment by anthonydillon** [comment]
Thank you for the suggestion @BryanQuigley. @pmahnke is actively working on a branch to cover all the legal pages to markdown.
