### ISSUE TITLE
Grammar mistake on Ubuntu Core page

### ISSUE THREAD

**Issue by eaglersdeveloper** [canonical-websites/www.ubuntu.com#4533]
![2018-12-20 17-16-04](https://user-images.githubusercontent.com/40228953/50287333-d9054300-047b-11e9-87cc-038f08fa9742.png)

---
*Reported from: https://www.ubuntu.com/core*

**Comment by rbalint** [comment]
Also ... booth path ...

**Comment by Greggless** [comment]
Thanks for reporting these issue, the pa
