### ISSUE TITLE
Error in Ubuntu instructions

### ISSUE THREAD

**Issue by cloud-padawan** [canonical-websites/www.ubuntu.com#4540]
Hi,
I was following the instructions for copying the ubuntu core img into my raspberri pi 3 and noticed the xzcat command was not working. Looks like after the pipe & dd command, "of= is missing some sort of descriptor such as < drive address >

If the Ubuntu Core image file you have downloaded ends with an `.xz` file extension, run:

xzcat ~/Downloads/ < image file .xz > | sudo dd of= bs=32M

_Correction suggested_
xzcat ~/Downloads/ < image file .xz > | sudo dd of=< drive address > bs=32M

**Comment by Greggless** [comment]
Thanks for the report cloud-padawan.

@caldav would you be able to take a look at this?

**Comment by pmahnke** [comment]
@cloud-padawan 	I might be misunderstanding your bug report, but it does have the device address on the site

![image](https://user-images.githubusercontent.com/441217/51075129-7d476780-167f-11e9-9361-c9d2f1b03959.png)

**Comment by pmahnke** [comment]
this appears to be fixed, closing.  reopen if there is still an issue
