### ISSUE TITLE
Join Canonical product director Stephan Fabel What's new in 18.10

### ISSUE THREAD

**Issue by aqking** [canonical-websites/www.ubuntu.com#4542]
### **"WATCH THE WEBINAR"**
https://pages.ubuntu.com/rs/066-EOV-335/images/button_watch-the-webinar.png
https://www.ubuntu.com/engage/ubuntu-18-11?utm_source=Marketo&utm_medium=Email&utm_campaign=FY19_Cloud_Openstack_WBN_18.10&mkt_tok=eyJpIjoiTm1FMU9EWTFOemMwWkRZMCIsInQiOiJyNjFueHVOSm9MYTI3YllaajBKdGJ5YUxxeitteVRrMlE4SEhDYVdsXC8rb2J3MFpPZkdtTVwvWW1lT0dDQVI2U2owc2pmWEtVRlhoMEtiQWs3ckxaOTJtZ3hOeHJBK3NlbFlLckFCNFJyQjVZclVNWUhZOWNudTFpRTNXZGpUWjlsIn0%3D

    **### 404 - page not found**
---
*Reported from: https://www.ubuntu.com/engage/ubuntu-18-11?utm_source=Marketo

**Comment by Greggless** [comment]
Hi @aqking

Thanks for reporting an issue. 

If you could write a little more information about this issue... 

That'd be great.
