### ISSUE TITLE
Broken menu link in Ubuntu Advantage Service Description page

### ISSUE THREAD

**Issue by shoshin71** [canonical-websites/www.ubuntu.com#4547]
*Note - filling in this form will file an issue against the www.ubuntu.com website, not against Ubuntu itself, for Ubuntu bugs, please [go here](https://help.ubuntu.com/community/ReportingBugs)*

## Summary
Bad menu link in https://www.ubuntu.com/legal/ubuntu-advantage-service-description

Menu option 14 for Tecnical Account Manager links to https://www.ubuntu.com/legal/ubuntu-advantage-service-description#tam, but that link doesn't work. I believe the correct link should be https://www.ubuntu.com/legal/ubuntu-advantage-service-description#appendix-support-scope-tam 

## Process

See Summary. Broken link

## Current and expected result

See Summary. Broken link.

## Screenshot

N/A

**Comment by lborda** [comment]
It works in chrome (Version 71.0.3578.98 (Official Build) (64-bit)) but not in Firefox.

Name: Firefox
Version: 64.0
Build ID: 20181207224003
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by shoshin71** [comment]
It does not work in Chrome for me.

**Comment by pmahnke** [comment]
@shoshin71 	thanks, I had very recently move this doc to markdown and updated most internal anchors to be more consistent, and missed this.

thanks, PR in place.
