### ISSUE TITLE
Brand store takeover - build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4550]
https://docs.google.com/document/d/1P9iXXka1qGS1D_n14CiraIzIE-NDmMXMxQyM8v4A0T0/edit

Check this spreadsheet for the go-live date:

https://docs.google.com/spreadsheets/d/1MaFd-ZHWpRVjIP9Sj_dOCIGOtl-GJYbrXewt5EG4m80/edit#gid=564832475

**Comment by anasereijo** [comment]
please be aware that the copy used on my designs isn't the final version - check the [copydoc](https://docs.google.com/document/d/1P9iXXka1qGS1D_n14CiraIzIE-NDmMXMxQyM8v4A0T0/edit#heading=h.meo0azuz09li))

- check designs [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/174)
- gradient: `background-image: linear-gradient(-134deg, #2D6162 0%, #83BFA1 100%);
`
- text should be `8col`

-  [image](https://assets.ubuntu.com/v1/44fd30d7-Snap+Store+shopping+icon+darkhandle.svg)

- desktop image size: 229x200

- mobile image size: 180x157

- [suru](https://assets.ubuntu.com/v1/9a0310e3-suru-right-snapstore.svg) - don't show it on small screens.

**Comment by Greggless** [comment]
Updated the copy in the briefff
