### ISSUE TITLE
Broadsign & Arrow takeover - Build

### ISSUE THREAD

**Issue by shivjoshi1996** [canonical-websites/www.ubuntu.com#4552]
https://docs.google.com/document/d/1SdsdEujcUMGsVyguCRaJhxvyQxSEGgOXq8xLEs0DM9c/edit

**Comment by anasereijo** [comment]
Things to know:
- final designs are [here](https://github.com/ubuntudesign/www.ubuntu.com-design/issues/175)
- copy used on the design isn't the final copy (please check [copydoc](https://docs.google.com/document/d/1SdsdEujcUMGsVyguCRaJhxvyQxSEGgOXq8xLEs0DM9c/edit#)) 
- please don't use the lines on small screens just the gradient as a background
- copy should be `6col`

Assets:

- [logos](https://assets.ubuntu.com/v1/96f63d61-logos-takeover-digital-signage.svg)
- [logos with lines](https://assets.ubuntu.com/v1/3f59dacd-logos-lines-takeover-digital-signage.svg)
- [logo lines separated  ](https://assets.ubuntu.com/v1/26cb7ab6-logo+lines.svg)
- [left lines](https://assets.ubuntu.com/v1/621965fa-left-lines.svg)
- [right lines](https://assets.ubuntu.com/v1/3f540239-right-lines.svg)
- gradient: `background-image: linear-gradient(-64deg, #DEDEDE 0%, #FFFFFF 100%);`

**Comment by pmahnke** [comment]
@anthonydillon 	can you help?

I got this far, but the background position of the logos is moving around and the logo version with lines doesn't go to the section edge.

```html
<section class="p-strip--image js-takeover p-takeover--broadsign">
  <div class="row u-equal-height">
    <div class="col-6">
      <h1>Digital signage and smart displays</h1>
      <p class="p-heading--four">Secure, reliable and remotely upgradable. Learn how Ubuntu is powering new age advertising.</p>
      <p class="u-hide--small">
        <a href="https://www.brighttalk.com/webcast/6793/346565?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY19_IOT_Ubuntu Core_WBN_Digital Signage" class="p-button--positive u-no-margin--bottom">Register for the webinar</a>
      </p>
    </div>
    <div class="col-6 u-vertically-center u-align--center">
      <img src="{{ ASSET_SERVER_URL }}96f63d61-logos-takeover-digital-signage.svg" class="" alt="" />
      <p class="u-no-margin--bottom u-hide--large u-hide--medium">
        <a href="https://www.brighttalk.com/webcast/6793/346565?utm_source=Takeover&utm_medium=Takeover&utm_campaign=CY19_IOT_Ubuntu Core_WBN_Digital Signage" class="p-button--positive">Register for the webinar</a>
      </p>
    </div>
  </div>

  <style>
      .p-takeover--broadsign {
        background-color: #DEDEDE;
				background-image: linear-gradient(-64deg, #DEDEDE 0%, #FFFFFF 100%);
        background-image: url('{{ ASSET_SERVER_URL }}621965fa-left-lines.svg'),
        url('{{ ASSET_SERVER_URL }}26cb7ab6-logo+lines.svg'), url('{{ ASSET_SERVER_URL }}3f540239-right-lines.svg');
        background-repeat: no-repeat;
        background-size: inherit;
        background-position: center left, 90% 60%, center right;
      }
    </style>
</section>

```
