### ISSUE TITLE
#contact-us QA

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4566]
@anthonydillon @pmahnke 

1. Form's Z-index is lower than the Global nav
1. form title `h3`
1. questions `h4`
1. margin between checkboxes 8px
1. add form validation, with the correct error styling
1. de-activate 'next' until form completed
1. 'Please specify' text field should not be visible until 'other' is checked
1. When checking 'other' cursor should move into 'please specify' text field
1. CTA's should have `no-margin-bottom`, I.E 16px from the edge of the container
1. On the last page, there's no padding between the label and the field

**Comment by anthonydillon** [comment]
All done.
