### ISSUE TITLE
I guess wrong text in instruction

### ISSUE THREAD

**Issue by josefnorlin** [canonical-websites/www.ubuntu.com#4569]
Here at: https://www.ubuntu.com/download/iot/installation-media#macos

In the instructions step for flashing the img file to the drive you wrote the instruction to be:
sudo sh -c 'xzcat ~/Downloads/< image file > | sudo dd of=< drive address > bs=32m'< /drive >

I guess the last < /drive > was a mistake? If not, what should I fill in there?

---
*Reported from: https://www.ubuntu.com/download/iot/installation-media*

**Comment by pmahnke** [comment]
seems like someone's text editor was trying a bit too hard
