### ISSUE TITLE
https://www.ubuntu.com/download/iot/raspberry-pi-2-3  disclaimer needs an update

### ISSUE THREAD

**Issue by mvo5** [canonical-websites/www.ubuntu.com#4577]
On https://www.ubuntu.com/download/iot/raspberry-pi-2-3  the phrase `the older kernel shipped with this image can trigger Wi-Fi issues during first boot, a network cable is recommended.` is apparently no longer needed in UC18 images because that ships a 4.15 kernel world.

Thanks to om26er, cwayne 

---
*Reported from: https://www.ubuntu.com/download/iot/raspberry-pi-2-3*

**Comment by pmahnke** [comment]
@mvo5 thanks, we got an update from Pat G as well.

Update according to the [copy doc](https://docs.google.com/document/d/1Ig906jbgB39QHw61uHMvIsRbSBUjchJBDkMZl0WzlWM/edit?ts=5c41bf64#)
