### ISSUE TITLE
Page still has references to core 16, should be 18

### ISSUE THREAD

**Issue by popey** [canonical-websites/www.ubuntu.com#4587]
"xzcat /media/ubuntu/<disk label>/ubuntu-core-16-amd64.img.xz | sudo dd of=/dev/mmcblk0 bs=32M status=progress; sync"

Above should refer to core 18, not core 16

---
*Reported from: https://www.ubuntu.com/download/iot/intel-nuc*

**Comment by popey** [comment]
Nope. Step 6.

```
xzcat /media/ubuntu/<disk label>/ubuntu-core-16-amd64.img.xz | sudo dd of=/dev/mmcblk0 bs=32M status=progress; sync
```

Should not reference ubuntu-core-16

**Comment by pmahnke** [comment]
ah... and the pi compute module as well... yikes
