### ISSUE TITLE
Update list of copyrights

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4648]
We would like to update the list of trademarks owned by Canonical (https://www.ubuntu.com/legal/trademarks) to add the following:

BAZAAR
BOOTSTACK
JAAS
LAUNCHPAD 
LUBUNTU
LXD
MAAS
SNAPCRAFT
SNAPPY 

Please let me know if you need me to put this into a copydoc or if you need any further information.
Thanks

Allegra

**Comment by anasereijo** [comment]
should we show the logos too? happy to design something if needed

**Comment by pmahnke** [comment]
@anasereijo not sure, as the are legal pages, but you might ask Allegra?  also, might mean I need to go back to html over markdown.
