### ISSUE TITLE
Broken links in /kubernetes/docs

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#4655]
Link checking with drlinkcheck.com found these 404s in the Kubernetes docs:

404 Not found	
https://raw.githubusercontent.com/conjure-up/spells/master/canonical-kubernetes/addons/prometheus/steps/01_install-prometheus/prometheus-scrape-k8s.yaml
Linked from: https://www.ubuntu.com/kubernetes/docs/monitoring

404 Not found	
https://raw.githubusercontent.com/conjure-up/spells/master/canonical-kubernetes/addons/prometheus/steps/01_install-prometheus/grafana-k8s.json
Linked from: https://www.ubuntu.com/kubernetes/docs/monitoring

404 Not found	
https://docs.jujucharms.com/stable/en/charms-exposing
Linked from: https://www.ubuntu.com/kubernetes/docs/using-vault

404 Not found	
https://jujucharms.com/stable/en/hacluster
Linked from: https://www.ubuntu.com/kubernetes/docs/using-vault

404 Not found	
https://github.com/juju-solutions/charm-azure-integrator/issues/16
Linked from: https://www.ubuntu.com/kubernetes/docs/release-notes

404 Not found	
https://github.com/juju-solutions/charm-openstack-integrator/issues/10
Linked from: https://www.ubuntu.com/kubernetes/docs/release-notes

404 Not found	
https://github.com/juju-solutions/charm-flannel/issues/52
Linked from: https://www.ubuntu.com/kubernetes/docs/release-notes

**Comment by nottrobin** [comment]
@evilnick would you be able to take a look at these?

**Comment by evilnick** [comment]
yup, looks like some of the resources were moved/renamed or closed. I will fix
