### ISSUE TITLE
Broken links in /legal area

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#4657]
Found with https://www.drlinkcheck.com/:

404 Not found
http://uk.marketo.com/trust/privacy.php
Linked from: https://www.ubuntu.com/legal/data-privacy/2013-03-25 and 1 more

404 Not found
http://about.7digital.com/terms-and-conditions-use
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://privacy.microsoft.com/en-gb/bing.mspx
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://dribbble.com/site/privacy
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://www.encuentro.gov.ar/sitios/encuentro/condiciones/index
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://www.headweb.com/en/100234/integrity-policy
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://wikimediafoundation.org/wiki/Wikimedia:Privacy_policy
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
http://helloreverb.com/privacy/
Linked from: https://www.ubuntu.com/legal/data-privacy/third-parties

404 Not found
https://developer.ubuntu.com/en/publish/
Linked from: https://www.ubuntu.com/legal/developer-terms-and-conditions/2016-04-06

404 Not found
http://code.google.com/webfonts
Linked from: https://www.ubuntu.com/legal/font-licence/faq

**Comment by pmahnke** [comment]
on /legal/data-privacy/third-parties

- headweb is now https://www.plejmo.com ? - asked KO and AC
- http://helloreverb.com/ is dead? - asked KO and AC

old /legal/developer-terms-and-conditions/2016-04-06 links to old dev.u.c and myapps links - asked KO and AC
