### ISSUE TITLE
Ubuntu 14.04.5 typo on release-cycle

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#4691]
When viewing the text version of release-cycle it shows "Ubuntu 14.04.5 LTS LTS (v3.13)"

It should only say LTS once and the correct kernel version is 4.4.

---
*Reported from: https://www.ubuntu.com/about/release-cycle*

**Comment by pmahnke** [comment]
@cjohnston1158 	this appears fixed to me? I think you even put in the PR?

closing, reopen if I am crazy
