### ISSUE TITLE
Takeover - ESM Announcement - Design

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4695]

**Comment by anasereijo** [comment]
### Desktop

![final - takeover-large-screen](https://user-images.githubusercontent.com/36884067/52958064-35f17c80-338b-11e9-8a30-6e603a7da2a8.jpg)



### Mobile


![takeover-small-screen](https://user-images.githubusercontent.com/36884067/52958075-3d188a80-338b-11e9-916f-7ae5d48d5d08.jpg)

**Comment by anasereijo** [comment]
Visuals are ready. Waiting on [UX](https://github.com/canonical-websites/www.ubuntu.com/issues/4696) to be done. FYI @pmahnke
