### ISSUE TITLE
Takeover - ESM Announcement - UX

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4696]
brief: https://docs.google.com/document/d/1OY1C3rJeIlv4I_P6SmwWev5mx7d_gX0oZ22w9u1HgwY/edit#

**Comment by anasereijo** [comment]
@pmahnke are you happy using the following copy version?

https://github.com/canonical-websites/www.ubuntu.com/issues/4695

https://docs.google.com/document/d/1OY1C3rJeIlv4I_P6SmwWev5mx7d_gX0oZ22w9u1HgwY/edit?ts=5c669a79#heading=h.qtdd929h9j5s
