### ISSUE TITLE
Takeover - ESM Announcement - Social banners

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4698]
brief https://docs.google.com/document/d/1OY1C3rJeIlv4I_P6SmwWev5mx7d_gX0oZ22w9u1HgwY/edit#

**Comment by anasereijo** [comment]
Hi @Khutch25,
Find below the social media banners.

Can you please have a look and let me know if you need any changes?
Where do you think I should save them for you? 

## Facebook
#### Facebook Ad 1
![facebook ad 1 - outlines](https://user-images.githubusercontent.com/36884067/53086922-ef705f00-34fd-11e9-91d1-c04f37154b3c.jpg)
#### Facebook Ad 2
![facebook ad 2](https://user-images.githubusercontent.com/36884067/53086921-ef705f00-34fd-11e9-8937-fa3ee05228dd.jpg)
#### Facebook Ad 3
![facebook ad 3](https://user-images.githubusercontent.com/36884067/53086920-ef705f00-34fd-11e9-9b1b-b80cf30b2d4f.png)
#### Facebook Ad 4
![facebook ad 4](https://user-images.githubusercontent.com/36884067/53086916-ee3f3200-34fd-11e9-8d06-8e8c51883d6e.jpg)

## Google
#### Google Ad 1
![google ad 1](https://user-images.githubusercontent.com/36884067/53087033-2777a200-34fe-11e9-8b27-6fa9f7ed4050.jpg)
#### Google Ad 2
![google ad 2](https://user-images.githubusercontent.com/36884067/53087034-2777a200-34fe-11e9-8339-d9ba354b5970.jpg)
#### Google Ad 3
![google ad 3](https://user-images.githubusercontent.com/36884067/53087035-28103880-34fe-11e9-95ac-e987919a0e32.jpg)
#### Google Ad 4
![google ad 4](https://user-images.githubusercontent.com/36884067/53087036-28103880-34fe-11e9-8718-096315ee098d.jpg)

## Email banner in situ
#### Email banner 1
![email banner v1](https://user-images.githubusercontent.com/36884067/53087127-5857d700-34fe-11e9-8017-c4a9d79eecfc.png)

#### Email banner 2
![email banner v2](https://user-images.githubusercontent.com/36884067/53087132-5beb5e00-34fe-11e9-8c50-4dfb4d50f5fa.png)

#### Email banner 3
![email banner v3](https://user-images.githubusercontent.com/36884067/53087143-5f7ee500-34fe-11e9-86bc-4aaecb3e608d.png)

#### Email banner 4
![email banner v4](https://user-images.githubusercontent.com/36884067/53087147-6279d580-34fe-11e9-8e19-553297487265.png)

## Email banners
#### Email banner 1
![email banner 1](https://user-images.githubusercontent.com/36884067/53087179-702f5b00-34fe-11e9-874a-cd6d7d7c5374.jpg)

#### Email banner 2
![email banner 2](https://user-images.githubusercontent.com/36884067/53087198-77eeff80-34fe-11e9-9900-4e2acdac66f1.jpg)

#### Email banner 3
![email banner 3](https://user-images.githubusercontent.com/36884067/53087208-7d4c4a00-34fe-11e9-9c07-065bb3354b2e.jpg)

#### Email banner 4
![email banner 4](https://user-images.githubusercontent.com/36884067/53087217-8210fe00-34fe-11e9-9adf-2c46687a9569.jpg)

**Comment by Khutch25** [comment]
Thank you, @anasereijo ! Would it be possible to swap the charcoal/orange (or with different colors) of two of the Facebook ad images to switch it up and have some imagery with color? (with one of the question headline & one of the ESM headline images)

I was thinking it would be good to test dark vs. colored backgrounds with these ad versions.

Otherwise, looks good and thank you! 

Would you mind sharing the design files before Malta so I can drop in the German & French copy of for these ads once those are finalised next week? 

Please upload to this folder: https://drive.google.com/drive/folders/1nShxkFxffZR9ToRztttUUHQ0SsPquWoJ?usp=sharing

**Comment by anasereijo** [comment]
@Khutch25  changes done and banners saved 👍 
I also saved a copy of my sketch file (ping me if you need help!) but I think this should be an exception as we should always review the design before it gets published. 
Thank you!
