### ISSUE TITLE
Takeover - rerun VMware to OpenStack

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4700]

**Comment by anasereijo** [comment]
@Khutch25 I was going through our previous takeovers and the only one I could find related to VMware is the German one we did last August. Can you confirm if this design is okay to use? If so we will also copy in english. Thank you!

![final - takeover-large-screen](https://user-images.githubusercontent.com/36884067/52964129-7c4dd800-3399-11e9-95a0-e18ca82497e2.jpg)

**Comment by Khutch25** [comment]
> @Khutch25 I was going through our previous takeovers and the only one I could find related to VMware is the German one we did last August. Can you confirm if this design is okay to use? If so we will also copy in english. Thank you!
> 
> ![final - takeover-large-screen](https://user-images.githubusercontent.com/36884067/52964129-7c4dd800-3399-11e9-95a0-e18ca82497e2.jpg)

This design is okay to use IMO! Alex should get the brief with the English copy today :)

Cheers :)

**Comment by anasereijo** [comment]
@anthonydillon brief: https://docs.google.com/document/d/14Lzlydn9YNjTm-x-ACuKSE5xJaBe3xyHzFakQ1oRIVY/edit?ts=5c6e9927#
