### ISSUE TITLE
Takeover - Update core disk encryption to webinar

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4701]

**Comment by anasereijo** [comment]
Dev: please re-use the following takeover. 
@Khutch25: do you think we should have a brief with the changes?

![final - takeover-large-screen](https://user-images.githubusercontent.com/36884067/52964332-f1b9a880-3399-11e9-8de1-ee80b04c2c8a.jpg)

**Comment by anasereijo** [comment]
brief: [https://docs.google.com/document/d/1190jbINXoZVHqA8hgAu9xetCizvUaslsA8sfTrZVkJw/edit](https://docs.google.com/document/d/1190jbINXoZVHqA8hgAu9xetCizvUaslsA8sfTrZVkJw/edit)
