### ISSUE TITLE
Download pages do not offer checksums

### ISSUE THREAD

**Issue by pmatulis** [canonical-websites/www.ubuntu.com#4723]
There are no links to checksum files for the stuff that people download such as Server and Desktop ISO files. The user has to stumble their way to a mirror in order to find them. This is bad UX. Simply add a link to a reliable and trusted mirror page such as (for Bionic):

http://releases.ubuntu.com/bionic/

---
*Reported from: https://www.ubuntu.com/download/server*

**Comment by pmahnke** [comment]
@pmatulis  perhaps not the best UX, but on the thank-you pages we have a Verify your download CTA with a link to this tutorial - https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu

I will try and put a better UXer on the project!

**Comment by pmatulis** [comment]
@pmahnke That's not what people expect, so the vast majority will never go looking for it.

The tutorial uses a standard mirror listing of files so I'm not sure if that's the best resource to point people to. It can even be a source of confusion (see below). 

This issue (lack of checksums) was raised on the [ubuntu-doc mailing list](https://lists.ubuntu.com/archives/ubuntu-doc/2019-February/020642.html).

**Comment by mlda065** [comment]
> on the thank-you pages we have a Verify your download CTA with a link to this tutorial

That's a great start (I can never remember the gpg commands). But it's not good enough. The tutorial tells the user that the checksum and signature can be downloaded on the same page as the iso. This is a false statement.

@pmatulis just FYI, I'm the person who wrote that initial email. I never actually received your reply. I can see it [here](https://lists.ubuntu.com/archives/ubuntu-doc/2019-February/020643.html). So I think there's a problem with the mailing list. (I recall spotting a confirmation email in my spam filter several days after that. So perhaps my subscription was put on hold? I don't know.)

**Comment by mlda065** [comment]
Actually, I stand corrected. It seems the [verification tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-how-to-verify-ubuntu?_ga=2.64884655.1248685753.1547162864-1813460345.1547162864#2) has been updated since I sent that email.

> It is usually convenient to download these at the same time as downloading the distro. However, if you didn't, not to worry - the checksums and the signature are consistent for the image, so even if you downloaded your ISO file from a different source, as long as it is fresh and hasn't been updated in the interim, you can fetch these files from the http://releases.ubuntu.com page for the relevant release. For example, for the current version of Ubuntu, if you check in http://releases.ubuntu.com/bionic/ you will find these files near the top.

It would still be great to have the link on the thank you page. Especially if it's a direct link, not a link to the root of the download tree.

I'll have a look to see if I can make a pull request. (Although I'm not really a web guy, and I am not familiar with SaaS and whatever template tool this repo uses.)
