### ISSUE TITLE
Video Link not Working, Either Submitting Form

### ISSUE THREAD

**Issue by pradverma94** [canonical-websites/www.ubuntu.com#4770]
https://www.brighttalk.com/webcast/6793/339167?utm_source=Takeover&utm_medium=Takeover&utm_campaign=FY19_IOT_UbuntuCore_WBN_Core%2018

---> This link not working in Mac Safari Browser

---
*Reported from: https://www.ubuntu.com/*

**Comment by anasereijo** [comment]
Hi @pradverma94 is this still a problem? I just tested it seems to work fine. Please let us know if you still have issues. Thank you
