### ISSUE TITLE
Whitepaper on the web - UX

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#4781]
think about how to display content, interactions and user experience by creating initial wireframes

**Comment by anasereijo** [comment]
## Phase 1 - research identifying needs
We printed out a few whitepapers to identify elements/content and assets in common and started to list them.

### Navigation
By talking through the printed whitepapers we started to think about how to incorporate a navigation bar that not only helps the user move to another chapter but also helps tracker the progress.
After some research and sketches, we agreed that [Vanilla's sidebar nav](https://docs.vanillaframework.io/en/) can be a good option (with some adjustments needed). We then studied Vanilla's docs structure/behaviour: each link on the sidebar nav loads a new "page". We aren't sure if this behaviour is helpful on long whitepapers/articles as the reader might lose his attention when moving to a new page (?). Therefore, we decided to test a version where we keep all content in one single page using a sticky sidebar nav with anchor links.
- Sticky sidebar nav
- Achor links down the page
- 3 title levels
- Obvious selected state

### Functionalities
- Scroll to point
- Anchor links with animated scroll
- Social share
- Back to top link
- Images to open on click (lightbox modal with option to click and see all imagens within the article)
- Generate pdf
- Friendly html print

### Content
- Quotes
- Bullets lists
- Call out section
- Links
- Tables
- Code snippet
- Code block
- Action banner at the end.
e.g.: further reading, documentantion & support, references, contact us, ...
- Print/download buttons at the end

### Article elements
- Header:
   - Title
   - Sub copy
   - Date
   - suru background

- Footer:
   - Previous and next whitepapers
