### ISSUE TITLE
snap deltas - takeover - design

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4831]
https://docs.google.com/document/d/16hfrPcgaC8F0_od9iPW-2JNwvrmU7XhvlakwuUrz-aM/edit

**Comment by anasereijo** [comment]
- The illustration is taken from [ubuntu.com/core](https://www.ubuntu.com/core#reduce-the-cost)
- The background is taken from the new [Snapcraft homepage](https://snapcraft.io/)

@spencerbygraves I designed 3 versions, can you please let me know which one you prefer? I like the light grey version and maybe the mid-grey one too.

### Dark grey

![Takeover-large-screen - dark grey](https://user-images.githubusercontent.com/36884067/54548634-3b4ce180-49a0-11e9-95b5-6234bf5ba82c.jpg)


### Mid-grey

![Takeover-large-screen - mid grey](https://user-images.githubusercontent.com/36884067/54548655-456ee000-49a0-11e9-8ffc-980264d0b901.jpg)


### Light grey

![Takeover-large-screen - light grey](https://user-images.githubusercontent.com/36884067/54548666-4e5fb180-49a0-11e9-9bd3-e1f0f5c63df0.jpg)

**Comment by anasereijo** [comment]
## Final version

### Desktop

![Takeover-large-screen](https://user-images.githubusercontent.com/36884067/54599455-96c7af80-4a32-11e9-95cd-0b576b0b1266.jpg)

### Mobile

![Takeover-small-screen](https://user-images.githubusercontent.com/36884067/54599463-9cbd9080-4a32-11e9-82d9-16574218a77b.jpg)
