### ISSUE TITLE
snap deltas - takeover - build

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4832]
https://docs.google.com/document/d/16hfrPcgaC8F0_od9iPW-2JNwvrmU7XhvlakwuUrz-aM/edit

**Comment by anasereijo** [comment]
This is ready to be built:
- [Designs](https://github.com/canonical-websites/www.ubuntu.com/issues/4831)
- Background: `background-image: linear-gradient(-181deg, #106363 12%, #083333 100%);`
- [Suru](https://assets.ubuntu.com/v1/57c3b829-suru+-+snapcraft+-+left.svg)
- Hide suru on mobile version
- [Illustration](https://assets.ubuntu.com/v1/b511e965-Delta+updates.svg)
- Illustration on mobile should be 250x134px
- Text should be `7 col`
