### ISSUE TITLE
footer - sectors is a link but doesn't link anywhere

### ISSUE THREAD

**Issue by anasereijo** [canonical-websites/www.ubuntu.com#4849]
"Sectors" heading is a link but we don't have a page for ubuntu.com/sectors

![The leading operating system for PCs  IoT devices  servers and the cloud   Ubuntu](https://user-images.githubusercontent.com/36884067/54525761-d6c45f00-496c-11e9-9763-532990c688cb.png)

---
*Reported from: https://www.ubuntu.com/*

**Comment by pmahnke** [comment]
which is why there is no link... do you have a suggestion?

**Comment by anasereijo** [comment]
As we don't have a /sectors page I suggest removing the link
