### ISSUE TITLE
Daten sichern

### ISSUE THREAD

**Issue by lineal30** [canonical-websites/www.ubuntu.com#4859]
Es wird auf die Festplatte gewartet. Mehr tut sich beim Datensichern nicht.
Was kann ich tun, das es wieder funktioniert.
Grams

---
*Reported from: https://www.ubuntu.com/contact-us/form/thank-you?aliId=eyJpIjoiMXVoOUVEUmdxNEpORXRSMyIsInQiOiJjZXRCSVF0TklMUFkrWVdHVGhcL1RBZz09In0=*

**Comment by pmahnke** [comment]
You need to look on askubuntu.com or the ubuntu forum for help with the OS.

This is for ubuntu.com bugs.

Sorry
