### ISSUE TITLE
Create engage/ai-ml page- build

### ISSUE THREAD

**Issue by pmahnke** [canonical-websites/www.ubuntu.com#4898]
[brief](https://docs.google.com/document/d/1ERb5EJPshFU7TtFEJWPdFyEGSP7OLSk9Kf3RuURYeG8/edit)

**Comment by anasereijo** [comment]
@anthonydillon please use the same background as the AI/ML takeover. I don't think we should use the illustration because it will look the same as the takeover.

**Comment by anthonydillon** [comment]
Its live: https://www.ubuntu.com/engage/ai-ml-ubuntu
