### ISSUE TITLE
Live news field failed to load on the website

### ISSUE THREAD

**Issue by nanoquanta** [canonical-websites/www.ubuntu.com#4953]
## Summary
Live News Field failed to load

I just clicked on resources on homepage of ubuntu.com, and message popped up displaying The live news field failed to load and please report this bug and out team will fix the problem as soon as possible. I do not know if this needs to be reported or a general issue but though whatever it is, best is to let you know. 

## Process

1. Go to www.ubuntu.com
2. Click on Resources

## Current and expected result

According to the website, the live news field should have loaded but didn’t. 

## Screenshot

![DB03E5ED-0E7C-447E-BE0D-ABCB51F1957C](https://user-images.githubusercontent.com/45217133/56090593-1ef27680-5e72-11e9-8f5c-dddaf572ddc3.png)

**Comment by anthonydillon** [comment]
Thank you for reporting this issue. It seems resources was temporarily out of service. This issue has been resolved.
