### ISSUE TITLE
Minify JavaScript

### ISSUE THREAD

**Issue by anthonydillon** [canonical-websites/www.ubuntu.com#653]
Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.

Minify JavaScript for the following resources to reduce their size by 2.1KiB (25% reduction).
- Minifying https://assets.ubuntu.com/v1/2c8fd8c9-Imager.js could save 1.2KiB (37% reduction) after compression.
- Minifying http://www.ubuntu.com/static/js/scratch.js?v=b32fc00 could save 873B (17% reduction) after compression.

**Comment by huwshimi** [comment]
Superseded by https://github.com/canonical-websites/www.ubuntu.com/issues/4773
