### ISSUE TITLE
Cloud > Overview: ticks in lists not showing [IE9, Win 7]

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#71]
I can see the ticks on the live site. Would it have anything to do with the load safe scripts thing?

**Comment by anthonydillon** [comment]
@yaili This will be resolved by Vanilla v1. This issue is coming from ubuntu-vanilla-theme which has been discontinued.

**Comment by barrymcgee** [comment]
Should be fixed by https://github.com/canonical-websites/www.ubuntu.com/pull/1886

**Comment by grahambancroft** [comment]
I've had a look at IE9 on Win 7 on Browserstack and ubuntu.com has no styles at all. We don't support this browser, as per the upcoming addition to our best practices https://github.com/anthonydillon/practices/blob/fc624f5a6815be8fff545c34026c24eddffcc26e/coding/browser-support.md so this will not be fixed, however, the sites content is accessible.
