### ISSUE TITLE
Update the SASS parser to provide a relevant include-path

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#824]
We need to support the new way that the [incoming version of ubuntu-vanilla-theme](https://github.com/ubuntudesign/ubuntu-vanilla-theme/blob/3060de2a3c82b5a3f27541c745c64b0b759ff212/scss/_theme.scss#L7) will include vanilla-framework.

This mean we need to provide the folder containing `vanilla-framework` (currently `node_modules`) to the SASS parser as an include-path where it will search for modules.

We will also need to start using NPM 3 or newer, so that vanilla-framework is pulled directly into `node_modules` rather than some sub-folder.

**Comment by deadlight** [comment]
I think that this is no longer an issue
