### ISSUE TITLE
language

### ISSUE THREAD

**Issue by adammaj1** [canonical-websites/www.ubuntu.com#885]
## Summary

On the polish verion of ubuntu there is a difference of output from testing 
## Process

locale
LANG=pl_PL.UTF-8
LANGUAGE=pl
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=

then 

  sha256sum -c SHA256SUMS 2>&1 | grep OK

gives nothing but 

$ sha256sum -c SHA256SUMS 

gives : 
sha256sum: ubuntu-16.04-desktop-amd64.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04-desktop-amd64.iso: FAILED open or read
sha256sum: ubuntu-16.04-desktop-i386.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04-desktop-i386.iso: FAILED open or read
sha256sum: ubuntu-16.04-server-amd64.img: Nie ma takiego pliku ani katalogu
ubuntu-16.04-server-amd64.img: FAILED open or read
sha256sum: ubuntu-16.04-server-amd64.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04-server-amd64.iso: FAILED open or read
sha256sum: ubuntu-16.04-server-i386.img: Nie ma takiego pliku ani katalogu
ubuntu-16.04-server-i386.img: FAILED open or read
sha256sum: ubuntu-16.04-server-i386.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04-server-i386.iso: FAILED open or read
ubuntu-16.04.1-desktop-amd64.iso: DOBRZE
sha256sum: ubuntu-16.04.1-desktop-i386.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04.1-desktop-i386.iso: FAILED open or read
sha256sum: ubuntu-16.04.1-server-amd64.img: Nie ma takiego pliku ani katalogu
ubuntu-16.04.1-server-amd64.img: FAILED open or read
sha256sum: ubuntu-16.04.1-server-amd64.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04.1-server-amd64.iso: FAILED open or read
sha256sum: ubuntu-16.04.1-server-i386.img: Nie ma takiego pliku ani katalogu
ubuntu-16.04.1-server-i386.img: FAILED open or read
sha256sum: ubuntu-16.04.1-server-i386.iso: Nie ma takiego pliku ani katalogu
ubuntu-16.04.1-server-i386.iso: FAILED open or read
sha256sum: UWAGA: 11 podanych plików nie mogło być odczytane

so : 
 ls

gives 
SHA256SUMS  SHA256SUMS.gpg  ubuntu-16.04.1-desktop-amd64.iso

and finally 

sha256sum -c SHA256SUMS 2>&1 | grep DOBRZE

ubuntu-16.04.1-desktop-amd64.iso: DOBRZE
## Current and expected result

So not OK but DOBRZE is result from testing

**Comment by pmahnke** [comment]
@adammaj1 I think you are saying that the Polish version of sha256sum command isn't 'OK' but 'DOBRZE'?

Is that correct?

And this is in reference to the text and examples on: http://www.ubuntu.com/download/how-to-verify ?

**Comment by pmahnke** [comment]
no response, so closing
