### ISSUE TITLE
auto-load from the paypal goes to an un-renewed URL site.

### ISSUE THREAD

**Issue by wildoracle** [canonical-websites/www.ubuntu.com#897]

**Comment by pmahnke** [comment]
@nottrobin 

hard to understand this issue; however, do you think they mean that one of the mirrors is dead?

**Comment by nottrobin** [comment]
@pmahnke Yes that sounds like the most likely explanation. @wildoracle can you still produce the issue? If so, could you let us know what URL you end up on?

**Comment by deadlight** [comment]
No response, closing. Please re-open if the issue can be reproduced.
