### ISSUE TITLE
Clean up takeovers folder

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#924]
The takeovers folder has 114 files, 1 or maybe 2 of which are probably being used.

The should be removed, we shouldn't have unused files littering the repository. If there are patterns that we need to be preserved for use in future takeovers, we should keep them elsewhere, in a wiki page or in gists.

**Comment by nottrobin** [comment]
Over on #916, @deadlight said:

> That's not practical at all for most of our use-cases. 90% of the time a takeover is based on or very similar to another. We often re-use them but there's no pattern in when we might do that. The ability to quickly slap them out and check them visually is invaluable.
>
> That said we can probably cull a lot of them and I agree that a better way of handling repeating/generic takeovers would make things tidier.
>
> IMO this is library code, not unused code. My preference is for keeping them but organising the file structure, culling entirely useless code and naming the files better. Also stand-alone CSS files for bespoke elements would avoid the problem we have in the homepage sass file of variously-kept/removed CSS.

**Comment by WillMoggridge** [comment]
One way to move forward with this, is to move all unused takeovers to a `takeovers/archive` folder. We can leave the current takeover and the rotating takeovers in the current folder.

**Comment by pmahnke** [comment]
I did this work - they now live here: https://github.com/ubuntudesign/ubuntu.com-takeover-archive
