### ISSUE TITLE
Small screen footer navigation, when you open a section, it creates a horizontal bar on the page

### ISSUE THREAD

**Issue by yaili** [canonical-websites/www.ubuntu.com#954]
## Summary

See title
## Process
- Go to any ubuntu.com
- Scroll down to footer
- Open "Cloud" section
- Try to swipe the screen to the right
- Now there is a gap between the right edge of content and the window
## Current and expected result

Expected result: no horizontal bar

**Comment by deadlight** [comment]
I can't replicate this bug. We can consider it fixed by the various work in this section in the last month.
