### ISSUE TITLE
/cloud/overview events design is off

### ISSUE THREAD

**Issue by ghost** [canonical-websites/www.ubuntu.com#979]
Spacing and alignment is off. speak to Yaili how to improve it

**Comment by yaili** [comment]
@magdalena-mirowicz do you mean about the spacing between event items, and between the titles and metadata?

**Comment by magdalena-mirowicz** [comment]
It was a note from our 16.10 release updates review, I can't see if it's still the case. If you think it looks fine we can close it @yaili

**Comment by yaili** [comment]
This should be covered when moving to Vanilla. We can come back to it later to make sure it's been done.

**Comment by pmahnke** [comment]
this was fixed with the homepage layout... closing
