### ISSUE TITLE
cloud/openstack Autopilot/landscape image not repositioning correctly

### ISSUE THREAD

**Issue by magdalena-mirowicz** [canonical-websites/www.ubuntu.com#981]
## Summary

[please describe the issue]
## Process

[list the steps to replicate the issue]
## Current and expected result

[describe what happened and what you expected]
## Screenshot

[if relevant, include a screenshot]

**Comment by pmahnke** [comment]
I think this was fixed... can you confirm @magdalena-mirowicz

**Comment by magdalena-mirowicz** [comment]
@yaili can you confirm please

**Comment by yaili** [comment]
Mmm… not really, yes and no. Both this page and MAAS https://www.ubuntu.com/server/maas were supposed to have their images full height and bleeding out the right edge of the grid. It's not terrible now, but it would be good to put it back as it was.
